version: "3.8"
services:
  floci:
    image: floci/floci:latest
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  floci-az:
    image: floci/floci-az:latest
    ports:
      - "4577:4577"
      - "5672:5672"   # Event Hubs AMQP
      - "5673:5673"   # Service Bus AMQP

  floci-gcp:
    image: floci/floci-gcp:latest
    ports:
      - "4588:4588"
