name: academia_cloud_local

services:
  aws-local:
    image: floci/floci:latest
    container_name: floci-aws
    ports:
      - "4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./data/aws:/var/lib/floci

  stackport:
    image: davireis/stackport:latest
    container_name: floci-stackport
    depends_on:
      - aws-local
    ports:
      - "8080:8080"
    environment:
      - AWS_ENDPOINT_URL=http://aws-local:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1

  azure-local:
    image: floci/floci-az:latest
    container_name: floci-azure
    ports:
      - "4577:4577"

  gcp-local:
    image: floci/floci-gcp:latest
    container_name: floci-gcp
    ports:
      - "4588:4588"
