import { CourseModule, createModule as m } from '../course-module.model';

export const ANDROID_MODULES: CourseModule[] = [
  m(0, 'Kotlin aplicado a Android', 'Kotlin en Android', 'Fundamentos', '2 h', '#3ddc84',
    'Arranca un proyecto Android moderno y entiende su estructura antes de escribir UI.',
    ['Estructura de un proyecto Android Studio', 'Gradle y módulos de app', 'AndroidManifest.xml', 'Recursos (strings, dimens, drawables)'],
    [
      'Crea un proyecto nuevo en Android Studio con la plantilla "Empty Activity" y ejecútalo en un emulador',
      'Recorre la estructura generada: app/src/main/java, AndroidManifest.xml, res/',
      'Agrega un string a res/values/strings.xml y úsalo desde un composable en vez de hardcodear texto',
      'Modifica el AndroidManifest.xml para cambiar el ícono y el nombre visible de la app',
      'Agrega un módulo Gradle nuevo (ej. :core) y haz que :app dependa de él',
    ],
    ['¿Por qué externalizar strings a un archivo de recursos en vez de hardcodearlos en el código?', '¿Qué declara el AndroidManifest.xml que el sistema operativo necesita saber antes de instalar la app?'],
    ['Android Studio'],
    'Proyecto Android nuevo corriendo en un emulador con un recurso propio.'),
  m(1, 'Ciclo de vida: Activities y ViewModel', 'Ciclo de vida', 'Fundamentos', '2 h 30 min', '#3ddc84',
    'El ciclo de vida es la fuente más común de bugs en Android. Domínalo desde el principio.',
    ['Ciclo de vida de Activity/Fragment', 'ViewModel y supervivencia a rotación', 'SavedStateHandle', 'Lifecycle-aware components'],
    [
      'Imprime logs en onCreate, onStart, onResume, onPause, onStop y onDestroy de una Activity, y observa el orden al rotar la pantalla',
      'Guarda un contador en una variable simple del composable y rota la pantalla — observa que se pierde el valor',
      'Mueve ese contador a un ViewModel y confirma que sobrevive a la rotación',
      'Usa SavedStateHandle en el ViewModel para que el valor sobreviva incluso si el sistema mata el proceso por falta de memoria',
      'Identifica qué evento del ciclo de vida deberías usar para liberar un recurso costoso (ej. una cámara)',
    ],
    ['¿Por qué un ViewModel sobrevive a una rotación de pantalla pero no a que el sistema mate el proceso completamente?', '¿Qué diferencia hay entre lo que sobrevive un ViewModel y lo que sobrevive SavedStateHandle?'],
    ['Android Architecture Components'],
    'Pantalla que sobrevive a rotación de pantalla sin perder estado, usando ViewModel.'),
  m(2, 'Jetpack Compose: UI declarativa', 'Jetpack Compose', 'Fundamentos', '3 h', '#3ddc84',
    'La UI moderna de Android se describe como función del estado, igual que React o SwiftUI.',
    ['Composables y recomposición', 'State hoisting', 'Modifiers y layout (Row, Column, Box)', 'remember y rememberSaveable', 'LazyColumn, LazyRow y LazyVerticalGrid', 'Scaffold, TopAppBar y FloatingActionButton'],
    [
      'Crea un composable TarjetaTarea(titulo: String) que reciba datos como parámetros, sin estado interno',
      'Usa remember { mutableStateOf(0) } para un contador local y observa la recomposición en cada click',
      'Eleva ese estado al padre (state hoisting): el composable hijo recibe value y onValueChange, no maneja el estado él mismo',
      'Construye un layout combinando Row, Column y Box con distintos Modifiers (padding, fillMaxWidth, weight)',
      'Cambia remember por rememberSaveable y verifica que el valor sobrevive a una rotación de pantalla',
    ],
    ['¿Por qué Compose vuelve a ejecutar (recomponer) una función composable, y qué la dispara?', '¿Qué problema resuelve elevar el estado (state hoisting) a un componente padre?'],
    ['Jetpack Compose'],
    'Pantalla Compose con estado elevado (state hoisting) correctamente aplicado.'),
  m(3, 'Navegación con Navigation Compose', 'Navegación', 'Aplicación', '2 h', '#3ddc84',
    'Estructura una app con múltiples pantallas y paso de argumentos tipado.',
    ['NavHost y NavController', 'Argumentos de navegación tipados', 'Deep links', 'Navegación anidada (bottom nav + stack)'],
    [
      'Define un NavHost con al menos 4 destinos (rutas) y navega entre ellos con un NavController',
      'Pasa un argumento tipado (ej. un ID de tarea) de una pantalla de lista a una de detalle',
      'Configura un deep link que abra directamente la pantalla de detalle desde un link externo',
      'Implementa una bottom navigation bar con 3 secciones, cada una con su propio stack de navegación',
    ],
    ['¿Qué ventaja da pasar argumentos tipados en vez de un Bundle genérico como antes?', '¿Por qué cada sección de un bottom navigation suele necesitar su propio stack independiente?'],
    ['Navigation Compose'],
    'App con al menos 4 pantallas, navegación con argumentos y un bottom navigation.'),
  m(4, 'Estado con StateFlow y Compose', 'Gestión de estado', 'Aplicación', '2 h 30 min', '#3ddc84',
    'Conecta tu capa de datos con la UI de forma reactiva y testeable.',
    ['StateFlow en el ViewModel', 'collectAsStateWithLifecycle', 'UDF (Unidirectional Data Flow)', 'Eventos de un solo uso (SharedFlow)'],
    [
      'Expón un StateFlow<EstadoUI> desde un ViewModel y obsérvalo en Compose con collectAsStateWithLifecycle',
      'Implementa el flujo UDF completo: el usuario hace click → el composable llama a una función del ViewModel → el ViewModel actualiza el StateFlow → la UI se recompone',
      'Usa un SharedFlow para emitir un evento de un solo uso (ej. mostrar un Snackbar) que no debe repetirse en una recomposición',
      'Verifica con collectAsStateWithLifecycle que la recolección se pausa automáticamente cuando la app va a background',
    ],
    ['¿Por qué collectAsStateWithLifecycle es más seguro que collectAsState a secas en una app real?', '¿Por qué un evento de "mostrar Snackbar" debería modelarse con SharedFlow y no con StateFlow?'],
    ['StateFlow'],
    'Pantalla con UDF completo: eventos de usuario → ViewModel → StateFlow → UI.'),
  m(5, 'Networking con Retrofit/Ktor', 'Networking', 'Aplicación', '2 h 30 min', '#3ddc84',
    'Consume APIs REST reales con manejo de errores y estados de carga explícitos.',
    ['Retrofit + OkHttp', 'Coroutines para llamadas suspendidas', 'Manejo de errores HTTP', 'Interceptores (logging, auth)'],
    [
      'Define una interfaz Retrofit con un método suspend que consuma un endpoint GET real',
      'Llama a ese endpoint desde un ViewModel dentro de un viewModelScope.launch y actualiza el StateFlow con el resultado',
      'Modela explícitamente los 3 estados (Cargando, Exito, Error) y muestra cada uno en la UI',
      'Agrega un interceptor de OkHttp que loguee cada request/response',
      'Agrega un interceptor que incluya un header de autenticación en cada llamada',
    ],
    ['¿Por qué Retrofit + coroutines es más simple de leer que el Retrofit clásico con Callback?', '¿Qué pasa con tu pantalla si nunca modelas explícitamente el estado de error?'],
    ['Retrofit'],
    'App que consume una API real con estados loading/error/success explícitos.'),
  m(6, 'Persistencia local con Room', 'Room', 'Integración', '2 h 30 min', '#3ddc84',
    'Persiste datos localmente con SQL tipado y Flow reactivo sobre la base de datos.',
    ['Entities, DAOs y Database', 'Migraciones de esquema', 'Room + Flow para datos reactivos', 'Estrategia offline-first básica'],
    [
      'Define una @Entity Tarea y un @Dao con métodos insert/update/delete y una query que devuelva Flow<List<Tarea>>',
      'Observa ese Flow desde el ViewModel y confirma que la UI se actualiza automáticamente cuando cambian los datos en Room',
      'Agrega una migración de esquema (Migration) que añada una columna nueva sin perder datos existentes',
      'Implementa una estrategia simple offline-first: la UI siempre lee de Room, y un repositorio sincroniza Room con la API en segundo plano',
    ],
    ['¿Qué ventaja da que un DAO devuelva Flow en vez de una lista simple?', '¿Por qué offline-first mejora la experiencia incluso con buena conexión?'],
    ['Room'],
    'App con caché local en Room que funciona sin conexión a internet.'),
  m(7, 'Inyección de dependencias con Hilt', 'Hilt', 'Integración', '2 h', '#3ddc84',
    'Desacopla dependencias en una app Android de forma estándar en la industria.',
    ['Hilt: módulos y componentes', '@Inject, @Provides, @Binds', 'Scopes de Hilt (ViewModelScoped, SingletonComponent)', 'Testing con Hilt', 'Koin como alternativa más ligera a Hilt'],
    [
      'Anota tu Application con @HiltAndroidApp y un ViewModel con @HiltViewModel',
      'Inyecta un repositorio en el ViewModel con @Inject en el constructor',
      'Crea un @Module con @Provides para una dependencia que no puedes anotar directamente (ej. una instancia de Retrofit)',
      'Usa @Binds para mapear una interfaz a su implementación concreta',
      'Configura un módulo de test que reemplace una dependencia real por un fake al correr tests instrumentados',
    ],
    ['¿Qué problema de acoplamiento resuelve Hilt frente a instanciar dependencias manualmente en cada clase?', '¿Cuándo usarías @Provides en vez de @Inject directo en el constructor?'],
    ['Hilt'],
    'App con todas sus dependencias (repos, servicios) inyectadas vía Hilt.'),
  m(8, 'Trabajo en segundo plano', 'Background work', 'Integración', '2 h', '#3ddc84',
    'Ejecuta tareas diferidas o periódicas que sobreviven incluso si la app se cierra.',
    ['WorkManager: tareas únicas y periódicas', 'Constraints (red, batería)', 'Coroutines en background con scopes correctos', 'Notificaciones desde background work'],
    [
      'Crea un CoroutineWorker que sincronice datos con un servidor remoto',
      'Encólalo como trabajo periódico (cada 15 minutos, el mínimo permitido) con WorkManager',
      'Agrega constraints: que solo corra con conexión a red y batería no muy baja',
      'Dispara una notificación local desde el Worker cuando la sincronización se completa',
      'Verifica con adb shell dumpsys que el trabajo persiste incluso después de cerrar la app',
    ],
    ['¿Qué garantiza WorkManager que un simple coroutine lanzado desde la Activity no garantiza?', '¿Por qué WorkManager respeta constraints de batería en vez de ejecutar el trabajo inmediatamente siempre?'],
    ['WorkManager'],
    'Tarea periódica con WorkManager que sincroniza datos con constraints de red.'),
  m(9, 'Testing en Android', 'Testing', 'Experto', '2 h 30 min', '#3ddc84',
    'Prueba lógica, ViewModels y UI con las herramientas estándar del ecosistema.',
    ['JUnit + Coroutines Test para ViewModels', 'Compose UI Testing', 'Espresso para flujos end-to-end', 'Fakes vs mocks en Android'],
    [
      'Escribe un test de ViewModel con un repositorio fake, verificando que el StateFlow expone el estado correcto tras una acción',
      'Usa runTest de kotlinx-coroutines-test para probar lógica suspend sin esperas reales',
      'Escribe un test de Compose UI que verifique que un texto aparece en pantalla tras un click, usando ComposeTestRule',
      'Escribe un test end-to-end con Espresso que recorra un flujo completo de la app',
      'Documenta cuándo preferirías un fake sobre un mock para un repositorio en tus tests',
    ],
    ['¿Por qué probar un ViewModel con un repositorio fake es más rápido y confiable que con la API real?', '¿Qué cubre un test de Compose UI que un test de ViewModel solo no cubre?'],
    ['Compose Testing', 'Espresso'],
    'Suite de tests: ViewModel con coroutines test + al menos un test de Compose UI.'),
  m(10, 'Performance, Material 3 y accesibilidad', 'Performance y UX', 'Experto', '2 h 30 min', '#3ddc84',
    'Una app rápida y accesible no es opcional: es lo que distingue una app profesional.',
    ['Material 3 theming', 'Recomposición innecesaria: cómo detectarla', 'Baseline profiles', 'Accesibilidad en Compose (semantics)', '@Stable, @Immutable y derivedStateOf', 'SideEffect, DisposableEffect y rememberUpdatedState', 'Interop con Views: AndroidView y ComposeView'],
    [
      'Aplica un MaterialTheme 3 completo (colores, tipografía, formas) a tu app',
      'Usa el Layout Inspector para detectar recomposiciones innecesarias en una pantalla con scroll',
      'Corrige al menos una causa de recomposición innecesaria (ej. una lambda recreada en cada render)',
      'Agrega contentDescription a elementos interactivos sin texto visible, para soporte de TalkBack',
      'Genera un Baseline Profile para tu app y documenta qué optimiza',
    ],
    ['¿Qué causa típicamente una recomposición innecesaria en Compose?', '¿Por qué la accesibilidad no es "opcional" sino parte del estándar de una app profesional?'],
    ['Material 3'],
    'Auditoría de performance de una pantalla con el Layout Inspector y al menos una mejora aplicada.'),
  m(11, 'Publicación en Google Play', 'Publicación', 'Experto', '2 h', '#3ddc84',
    'Lleva tu app del emulador a usuarios reales.',
    ['Firma de la app y App Bundles', 'Play Console: tracks de release', 'Versionado semántico de la app', 'Políticas de Google Play'],
    [
      'Genera una keystore y configura la firma de release en build.gradle.kts',
      'Genera un Android App Bundle (.aab) firmado en vez de un APK',
      'Crea una cuenta de Play Console (o revisa el proceso) y sube el .aab a un track de pruebas internas',
      'Define el versionCode y versionName siguiendo versionado semántico',
      'Revisa al menos 3 políticas de Google Play relevantes para tu app (privacidad, permisos, contenido)',
    ],
    ['¿Por qué Google Play requiere un App Bundle en vez de un APK universal?', '¿Qué diferencia hay entre versionCode y versionName, y por qué ambos importan?'],
    ['Google Play Console'],
    'App Bundle firmado, listo para subir a un track de pruebas internas en Play Console.'),
  m(12, 'Proyecto integrador: app Android completa', 'Proyecto final', 'Experto', '7 h', '#3ddc84',
    'Une Compose, Room, Retrofit, Hilt y testing en una app real.',
    ['Arquitectura MVVM con UDF', 'Persistencia offline-first', 'Inyección de dependencias con Hilt', 'Tests de ViewModel y UI'],
    [
      'Diseña la arquitectura MVVM completa: UI Compose → ViewModel (StateFlow) → Repositorio → Room + Retrofit',
      'Implementa persistencia offline-first: la UI siempre lee de Room, sincronizado en background con la API',
      'Inyecta todas las dependencias (repositorios, servicios) con Hilt, sin instanciación manual',
      'Escribe tests del ViewModel principal y al menos un test de Compose UI',
      'Genera el App Bundle firmado listo para Play Console',
    ],
    ['¿Qué decisión de arquitectura cambiarías si la app tuviera que soportar 10 pantallas más?', '¿Qué parte del proyecto (Compose, Room, Hilt) fue la más difícil de integrar correctamente con las demás?'],
    ['Jetpack Compose', 'Room', 'Hilt'],
    'App Android con Compose, datos reales, persistencia offline y tests.'),
  m(13, 'Android en producción: seguridad, sincronización y calidad', 'Producción Android', 'Experto', '8 h', '#3ddc84',
    'Endurece la app offline-first para dispositivos y redes hostiles: minimiza datos y permisos, protege claves y componentes, resuelve conflictos de sincronización, diagnostica ANR/crashes y despliega gradualmente con rollback y privacidad verificables.',
    [
      'Threat model móvil, permisos, componentes exportados, deep links y red segura',
      'Android Keystore, datos sensibles, backups, logs, screenshots y secretos',
      'Outbox local, idempotencia, versiones, conflictos, WorkManager y reconciliación',
      'ANR, crashes, StrictMode, Macrobenchmark, vitals, staged rollout y rollback',
    ],
    [
      'Explota/corrige un deep link y demuestra mínimo privilegio en manifest/permisos',
      'Protege una clave no exportable y prueba backup, logout y dispositivo restaurado',
      'Simula dos dispositivos offline y demuestra una política de conflicto sin perder cambios',
      'Provoca un ANR, identifica el bloqueo y opera un rollout mediante métricas por versión',
    ],
    [
      '¿Por qué una API key incluida en el APK no puede considerarse secreta?',
      '¿Cuándo last-write-wins pierde intención del usuario?',
      '¿Por qué capturar crashes no permite diagnosticar todos los ANR?',
    ],
    ['Android Keystore', 'Room', 'WorkManager', 'Macrobenchmark', 'Play Console'],
    'App con threat model, almacenamiento y enlaces endurecidos, sincronización idempotente con conflictos probados, diagnóstico ANR/crash y release gradual recuperable.'),
  m(14, 'Compose Master: pruebas, accesibilidad y animación', 'Compose Master', 'Experto', '8 h', '#3ddc84',
    'Verifica UI Compose con semántica accesible y movimiento medido, adaptable y respetuoso de preferencias.',
    ['ComposeTestRule', 'finders, assertions y actions', 'semantics y clearAndSetSemantics', 'AccessibilityService y TalkBack', 'animateXxxAsState y AnimatedVisibility', 'AnimatedContent, transitions y AnimationSpec'],
    ['Prueba texto y click', 'Crea matcher semántico', 'Audita TalkBack', 'Anima estado', 'Prueba reloj', 'Respeta escala de animación'],
    ['¿Qué prueba encuentra un nodo fusionado?', '¿Cuándo una animación perjudica accesibilidad?'], ['ComposeTestRule','Semantics','TalkBack','AnimationSpec'], 'Feature Compose probada con árbol semántico y animaciones accesibles.'),
];
