import { CourseModule, createModule as m } from '../course-module.model';

export const ANGULAR_MODULES: CourseModule[] = [
  m(0, 'Fundamentos y Angular CLI', 'Fundamentos', 'Fundamentos', '2 h', '#dd0031',
    'Arranca con la última versión LTS de Angular y entiende qué genera realmente el CLI antes de tocar código.',
    ['ng new, ng generate y estructura de proyecto', 'Standalone components por defecto (desde Angular 17+)', 'Interpolación y property binding', 'Ciclo de build y dev server', 'TypeScript a fondo: unknown vs any vs never, uniones/intersecciones, utility types (Partial, Pick, Omit, Record)', 'ng generate component/service/directive/pipe/guard/interceptor', 'Compilador AOT vs JIT'],
    [
      'Crea un proyecto con ng new mi-app y recorre la estructura generada: src/app, angular.json, tsconfig',
      'Genera un componente con ng generate component tarjeta y observa que NO se crea ningún NgModule',
      'Interpola una variable del componente en su template con {{ }} y enlaza un atributo con [property]',
      'Levanta el dev server con ng serve y modifica el componente para ver hot-reload en acción',
      'Ejecuta ng build y revisa los archivos generados en dist/ — identifica qué archivo es el bundle principal',
    ],
    ['¿Qué genera ng new que ya no formaba parte del Angular de hace unos años (NgModules)?', '¿Qué diferencia hay entre interpolación {{ }} y property binding [ ]?'],
    ['Angular CLI'],
    'Proyecto Angular nuevo con un componente propio renderizando datos dinámicos.'),
  m(1, 'Componentes, plantillas y data binding', 'Componentes', 'Fundamentos', '2 h 30 min', '#dd0031',
    'El componente es la unidad básica de Angular: input, output y la sintaxis de control de flujo moderna.',
    ['@Input/@Output e input()/output() basados en signals', 'Control de flujo nativo (@if/@for/@switch)', 'Content projection (ng-content)', 'Ciclo de vida de un componente', 'Hooks completos: ngOnChanges, ngDoCheck, ngAfterContentInit/Checked, ngAfterViewInit/Checked', 'Pipes integrados (Date, Currency, Async, Json) y pipes personalizados con @Pipe', 'ngClass, ngStyle y directivas personalizadas'],
    [
      'Crea un componente Tarjeta con un input() titulo y un output() click que el padre pueda escuchar',
      'Reemplaza un *ngFor/*ngIf antiguo por la sintaxis nativa @for/@if y observa la mejora de legibilidad',
      'Usa @for con la cláusula track por id y explica qué problema de rendimiento evita',
      'Crea un componente Modal que use <ng-content> para proyectar contenido arbitrario del padre',
      'Implementa ngOnInit y ngOnDestroy en un componente y registra en consola cuándo se llaman',
    ],
    ['¿Por qué @for exige (o recomienda fuertemente) una clave de track?', '¿Qué ventaja tiene input()/output() basado en signals sobre los decoradores @Input/@Output clásicos?'],
    ['Angular'],
    'Componente reutilizable (tarjeta/lista) parametrizado con inputs y outputs.'),
  m(2, 'Signals: el nuevo modelo de reactividad', 'Signals', 'Fundamentos', '2 h 30 min', '#dd0031',
    'Desde Angular 17, signals reemplazan gran parte del rol histórico de Zone.js. Entiende el modelo mental nuevo.',
    ['signal(), computed() y effect()', 'Mutación vs actualización inmutable', 'Signals vs Observables: cuándo usar cada uno', 'Camino hacia zoneless change detection', 'WritableSignal: update(), set(), mutate(), asReadonly()', 'linkedSignal para estado derivado y reseteable', 'model() para two-way binding basado en signals'],
    [
      'Crea un signal contador = signal(0) y dos botones que llamen a contador.update(v => v + 1) y contador.set(0)',
      'Deriva un computed() doble a partir de contador y verifica que se recalcula solo cuando contador cambia',
      'Usa effect() para loguear en consola cada vez que contador cambia, y observa cuándo se dispara exactamente',
      'Convierte un array mutado in-place (push) a una actualización inmutable con spread dentro de un signal',
      'Compara el mismo estado implementado con un BehaviorSubject de RxJS y con un signal — mide líneas de código y claridad',
    ],
    ['¿Por qué mutar un array dentro de un signal con push() no dispara la actualización de la UI?', '¿Cuándo seguirías prefiriendo un Observable sobre un signal?'],
    ['Angular Signals'],
    'Componente con estado derivado completamente con signals y computed, sin RxJS.'),
  m(3, 'Servicios e inyección de dependencias', 'DI', 'Fundamentos', '2 h', '#dd0031',
    'Comparte lógica y estado entre componentes sin acoplarlos directamente.',
    ['@Injectable y providedIn: root', 'inject() function vs inyección por constructor', 'Jerarquía de inyectores', 'Tokens de inyección personalizados', 'providedIn: platform/any y diferencias prácticas', '@Optional, @SkipSelf, @Self, @Host'],
    [
      'Crea un TareasService con @Injectable({ providedIn: "root" }) que mantenga un signal de tareas compartido',
      'Consume ese servicio desde 3 componentes distintos usando inject(TareasService) en vez de inyección por constructor',
      'Provee el mismo servicio a nivel de una ruta específica (no root) y observa que cada navegación crea una instancia distinta',
      'Crea un InjectionToken personalizado para inyectar un valor de configuración (ej. API_URL) en vez de hardcodearlo',
      'Explica con un diagrama la jerarquía de inyectores: root → ruta → componente',
    ],
    ['¿Qué diferencia práctica hay entre inject() y la inyección por constructor?', '¿Qué pasa si provees el mismo servicio en root Y en un componente — cuál gana?'],
    ['Angular DI'],
    'Servicio compartido de estado consumido por al menos tres componentes distintos.'),
  m(4, 'Routing y navegación', 'Routing', 'Aplicación', '2 h 30 min', '#dd0031',
    'Estructura una aplicación con múltiples vistas, carga perezosa y rutas protegidas.',
    ['Router config con rutas standalone', 'Guards funcionales (CanActivate)', 'Lazy loading con loadComponent', 'Parámetros de ruta y query params', 'CanDeactivateFn, CanMatchFn, canActivateChild y ResolveFn', 'ActivatedRouteSnapshot, RouterStateSnapshot y fragment'],
    [
      'Define al menos 4 rutas en app.routes.ts: home, lista, detalle/:id y una 404 con redirectTo',
      'Carga una de las rutas de forma perezosa con loadComponent y verifica en la pestaña Network que solo se descarga al navegar',
      'Implementa un guard funcional canActivate que bloquee el acceso a una ruta si no hay "sesión" (un signal booleano simulado)',
      'Lee un parámetro de ruta (:id) con ActivatedRoute o input binding de rutas, y úsalo para cargar el detalle correspondiente',
      'Agrega un query param de filtro (?estado=pendiente) y sincronízalo con un signal del componente',
    ],
    ['¿Qué ventaja real da loadComponent frente a importar todos los componentes de forma estática?', '¿Por qué un guard funcional es más simple de testear que una clase guard clásica?'],
    ['Angular Router'],
    'Aplicación con al menos 4 rutas, una protegida por guard y una cargada de forma perezosa.'),
  m(5, 'Formularios reactivos y template-driven', 'Formularios', 'Aplicación', '3 h', '#dd0031',
    'Valida entradas de usuario de forma predecible y testeable.',
    ['Reactive Forms: FormGroup, FormControl, FormArray', 'Validadores síncronos y asíncronos', 'Formularios anidados y dinámicos', 'Template-driven forms: cuándo siguen siendo válidos'],
    [
      'Crea un FormGroup con nombre, email y contraseña, cada uno con Validators.required y Validators.email donde aplique',
      'Muestra mensajes de error específicos por campo según qué validador falló (required vs email vs minlength)',
      'Agrega un validador asíncrono que verifique (simulado con delay) si un email ya está registrado',
      'Construye un FormArray para agregar/quitar dinámicamente teléfonos de contacto',
      'Implementa el mismo formulario simple con template-driven forms (ngModel) y documenta cuándo seguirías esa opción',
    ],
    ['¿Por qué Reactive Forms es más fácil de testear que template-driven forms?', '¿Cuándo seguiría siendo razonable usar template-driven forms hoy?'],
    ['Angular Forms'],
    'Formulario multi-paso con validación reactiva y mensajes de error claros.'),
  m(6, 'RxJS esencial para Angular', 'RxJS', 'Aplicación', '3 h', '#dd0031',
    'Angular sigue apoyándose en RxJS para flujos asíncronos complejos. Aprende lo justo y necesario.',
    ['Observable vs Promise', 'Operadores clave: map, switchMap, debounceTime, combineLatest', 'Manejo de suscripciones (async pipe, takeUntilDestroyed)', 'toSignal/toObservable como puente con Signals', 'Subject, BehaviorSubject, ReplaySubject y AsyncSubject', 'mergeMap, concatMap, exhaustMap y shareReplay'],
    [
      'Crea un buscador: un input cuyo valueChanges pase por debounceTime(300) y distinctUntilChanged antes de disparar la búsqueda',
      'Usa switchMap para cancelar automáticamente la petición anterior cuando el usuario escribe una nueva búsqueda',
      'Combina dos Observables (filtro y orden) con combineLatest para recalcular una lista derivada',
      'Suscríbete a un Observable en el template con el async pipe en vez de subscribe() manual, y explica por qué evita fugas de memoria',
      'Convierte un Observable a signal con toSignal() y úsalo en un computed()',
    ],
    ['¿Por qué switchMap cancela la petición anterior y mergeMap no?', '¿Qué fuga de memoria evita el async pipe que un subscribe() manual sin unsubscribe no evita?'],
    ['RxJS'],
    'Buscador con debounce y cancelación de peticiones previas usando switchMap.'),
  m(7, 'HttpClient e interceptores', 'HttpClient', 'Aplicación', '2 h', '#dd0031',
    'Consume APIs reales con manejo centralizado de errores y autenticación.',
    ['HttpClient con fetch backend (Angular 17+)', 'Interceptores funcionales', 'Manejo centralizado de errores HTTP', 'Tipado de respuestas con interfaces', 'HttpParams, HttpHeaders y observe: "response"', 'GET, POST, PUT, DELETE, PATCH y responseType'],
    [
      'Configura provideHttpClient(withFetch()) y haz un GET tipado contra una API pública',
      'Define una interface para la respuesta y verifica que TypeScript marca error si accedes a un campo que no existe',
      'Escribe un interceptor funcional que agregue el header Authorization a cada request saliente',
      'Escribe un interceptor que capture errores 401 globalmente y redirija a /login',
      'Maneja un error 500 mostrando un mensaje genérico al usuario sin exponer detalles técnicos',
    ],
    ['¿Qué ventaja da centralizar el manejo de errores HTTP en un interceptor en vez de en cada llamada?', '¿Por qué tipar la respuesta de una API no garantiza que los datos reales cumplan ese tipo?'],
    ['Angular HttpClient'],
    'Cliente HTTP con interceptor de autenticación y manejo centralizado de errores 401/500.'),
  m(8, 'Standalone components y arquitectura sin NgModules', 'Standalone', 'Integración', '2 h', '#dd0031',
    'La arquitectura moderna de Angular eliminó NgModule como requisito. Entiende cómo se organiza un proyecto hoy.',
    ['Bootstrap de aplicación standalone', 'Providers a nivel de ruta vs aplicación', 'Organización por features sin módulos', 'Migración de NgModules a standalone'],
    [
      'Revisa main.ts y app.config.ts de un proyecto generado por el CLI reciente — identifica que no hay un solo NgModule',
      'Organiza componentes por feature (carpetas tareas/, usuarios/) en vez de por tipo (components/, services/)',
      'Provee un servicio solo para las rutas de una feature específica, no globalmente',
      'Si tienes o encuentras un proyecto Angular antiguo con NgModules, identifica los pasos que tomaría migrarlo a standalone',
    ],
    ['¿Qué problema real resolvían los NgModules que hoy resuelven los standalone components de otra forma?', '¿Por qué organizar por feature escala mejor que organizar por tipo de archivo?'],
    ['Angular'],
    'Proyecto reorganizado 100% standalone, sin un solo NgModule.'),
  m(9, 'Gestión de estado', 'Estado', 'Integración', '3 h', '#dd0031',
    'Compara el enfoque nativo con signals contra una librería de estado dedicada.',
    ['Estado local con signals vs estado global', 'Patrón store con signals', 'NgRx: cuándo se justifica su complejidad', 'Selectors y derivación de estado', 'NgRx Entities y DevTools', 'Alternativas: Akita, Elf y NGXS'],
    [
      'Implementa un store propio basado en signals (estado, computed derivados, métodos de actualización) para una feature de carrito',
      'Conecta el store a 3 componentes distintos sin pasar props manualmente entre ellos',
      'Instala NgRx en un proyecto de práctica y replica el mismo carrito con actions, reducers y selectors',
      'Compara ambas implementaciones: líneas de código, curva de aprendizaje, debugging (Redux DevTools vs signals)',
      'Documenta un criterio propio: ¿a partir de qué tamaño/complejidad de app usarías NgRx?',
    ],
    ['¿Qué problema resuelve NgRx que un store de signals bien diseñado no resuelve igual de bien?', '¿Cuándo la complejidad adicional de NgRx vale la pena?'],
    ['NgRx'],
    'Store de estado propio basado en signals para una feature con varias vistas.'),
  m(10, 'Testing en Angular', 'Testing', 'Integración', '2 h 30 min', '#dd0031',
    'Prueba componentes, servicios y signals de forma rápida y mantenible.',
    ['TestBed y harnesses de Angular Material', 'Migración de Karma/Jasmine a Vitest', 'Testing Library para pruebas centradas en el usuario', 'Mocking de HttpClient en pruebas', 'fakeAsync, tick() y flush() para código asíncrono', 'ComponentFixture, DebugElement y By.css()'],
    [
      'Escribe un test con TestBed que cree un componente y verifique que renderiza el texto esperado',
      'Escribe un test de un servicio con signals: actualiza el estado y verifica el valor del signal directamente',
      'Usa Angular Testing Library para escribir un test que simule un click de usuario y verifique el resultado visible, no detalles internos',
      'Mockea HttpClient con HttpTestingController y verifica que tu servicio hace la petición correcta',
      'Configura el proyecto para correr tests con Vitest en vez de Karma/Jasmine y compara la velocidad',
    ],
    ['¿Por qué Testing Library empuja a probar "lo que el usuario ve" en vez de detalles de implementación?', '¿Qué ventaja de velocidad ofrece Vitest sobre Karma para este tipo de proyecto?'],
    ['Vitest', 'Testing Library'],
    'Suite de pruebas de componentes y servicios con cobertura razonable.'),
  m(11, 'Performance, SSR y zoneless', 'Performance y SSR', 'Experto', '3 h', '#dd0031',
    'Angular moderno apunta a aplicaciones rápidas desde el primer render.',
    ['Server-Side Rendering con Angular Universal', 'Hydration', 'Detección de cambios zoneless (sin Zone.js)', 'Lazy loading y deferred views (@defer)', 'ChangeDetectionStrategy.OnPush y ChangeDetectorRef.markForCheck()', 'Triggers de @defer: on viewport, on interaction, on hover, on idle, on timer', 'TransferState y provideClientHydration()', 'Análisis de bundle: ng build --stats-json y webpack-bundle-analyzer'],
    [
      'Habilita SSR en un proyecto existente con ng add @angular/ssr y verifica que el HTML inicial llega ya renderizado (ver curl al servidor)',
      'Observa en DevTools cómo ocurre la hydration: el HTML estático se vuelve interactivo sin re-renderizar todo',
      'Usa @defer en una sección pesada de la página (ej. un gráfico) para que cargue después del contenido principal',
      'Configura un trigger @defer (on viewport) para que el contenido difiera hasta que sea visible en pantalla',
      'Investiga y documenta qué significa "zoneless" y qué cambia respecto al modelo con Zone.js',
    ],
    ['¿Qué problema de rendimiento percibido resuelve SSR que el CSR puro no resuelve?', '¿Qué gana una aplicación al eliminar Zone.js del bundle?'],
    ['Angular SSR'],
    'Aplicación con SSR activado y al menos una vista usando @defer.'),
  m(12, 'Apéndice: qué cambió entre versiones mayores', 'Migraciones', 'Experto', '2 h', '#dd0031',
    'Angular evoluciona rápido. Esta lección resume los saltos que importan para mantener proyectos vivos.',
    ['AngularJS → Angular 2: reescritura total', 'Angular 9: motor de renderizado Ivy', 'Angular 14-17: standalone components y Signals', 'Cómo leer un Angular Update Guide y planear una migración'],
    [
      'Lee la tabla comparativa de este apéndice y ubica en qué versión se introdujo cada feature que usaste en módulos anteriores',
      'Usa update.angular.io con un proyecto "desde" una versión antigua hasta la actual y lee el plan de migración generado',
      'Ejecuta ng update paso a paso (una versión mayor a la vez) sobre un proyecto de práctica desactualizado',
      'Documenta, para un hipotético proyecto en Angular 12, los pasos y riesgos de migrar hasta la versión actual',
    ],
    ['¿Por qué Angular recomienda migrar una versión mayor a la vez y no saltar varias de golpe?', '¿Qué cambio entre versiones mayores tuvo el impacto más grande en cómo se escribe Angular hoy?'],
    ['Angular'],
    'Plan de migración documentado de un proyecto Angular antiguo hacia la versión actual.'),
  m(13, 'Proyecto integrador: aplicación standalone completa', 'Proyecto final', 'Experto', '6 h', '#dd0031',
    'Une signals, routing, formularios y HttpClient en una aplicación real.',
    ['Arquitectura por features standalone', 'Estado con signals', 'Consumo de API real con interceptores', 'Tests de componentes clave', 'Qué sigue: Micro Frontends (Module Federation), Web Components (@angular/elements), Domain-Driven Design', 'Dockerización (multi-stage + Nginx) y CI/CD con GitHub Actions'],
    [
      'Diseña la estructura de carpetas por feature para una app de gestión de tareas',
      'Implementa routing con al menos una ruta protegida por guard y una cargada de forma perezosa',
      'Implementa un store de signals para el estado de tareas, consumido por al menos 3 componentes',
      'Conecta HttpClient a una API real (puede ser la del track Node) con un interceptor de autenticación',
      'Escribe tests de al menos los 2 componentes más críticos de la aplicación',
    ],
    ['¿Qué decisión de arquitectura cambiarías si reescribieras este proyecto desde cero?', '¿Qué parte de Angular moderno (signals, standalone, @defer) tuvo el mayor impacto en tu código?'],
    ['Angular', 'RxJS', 'Vitest'],
    'Aplicación Angular standalone con routing, formularios, consumo de API y tests.'),
  m(14, 'Angular en producción: accesibilidad, seguridad e i18n', 'Producción frontend', 'Experto', '7 h', '#dd0031',
    'Audita y endurece la aplicación standalone para usuarios, idiomas, dispositivos y amenazas reales mediante semántica y foco correctos, sanitización contextual, CSP, traducciones verificadas y presupuestos de entrega.',
    [
      'Accesibilidad: HTML nativo, foco, routing, formularios, CDK/Angular Aria y pruebas',
      'Seguridad: sanitización, contextos DOM, CSP, Trusted Types, auth y SSR',
      'i18n: mensajes, ICU, locales, RTL, fechas, moneda y traducciones',
      'Performance budgets, Core Web Vitals, caché, service worker y releases observables',
    ],
    [
      'Completa un flujo solo con teclado y lector, corrige foco y anuncia navegación',
      'Explota y corrige un sink inseguro y aplica CSP sin bypass injustificado',
      'Extrae y despliega dos locales con plurales, moneda, zona horaria y RTL probados',
      'Define budgets y comprueba una actualización segura, métricas y rollback',
    ],
    [
      '¿Por qué agregar role=button no convierte un div en un botón completo?',
      '¿Cuándo bypassSecurityTrustHtml introduce una vulnerabilidad?',
      '¿Por qué traducir strings no basta para internacionalizar una aplicación?',
    ],
    ['Angular', 'Angular CDK', 'Angular Aria', 'Playwright', 'Lighthouse'],
    'Aplicación Angular auditada con flujo accesible, CSP y Trusted Types, dos locales, RTL, budgets de build, estrategia de actualización y evidencia de rendimiento real.'),
  m(15, 'Angular Master: pruebas, animación y SSR', 'Angular Master', 'Experto', '9 h', '#dd0031',
    'Prueba Signals y componentes, automatiza E2E, diseña movimiento accesible y opera SSR con hidratación.',
    ['Jasmine/Vitest, TestBed y ComponentFixture', 'Pruebas de Signals', 'Cypress y Playwright E2E', 'CSS/Angular animations y reduced motion', 'SSR, TransferState e hidratación', 'provideServerRendering y diagnóstico'],
    ['Prueba signal derivada', 'Aísla componente', 'Automatiza flujo', 'Respeta reduced motion', 'Evita doble fetch', 'Diagnostica hydration mismatch'],
    ['¿Qué debe probarse sin TestBed?', '¿Por qué SSR no garantiza rendimiento?'], ['Angular','TestBed','Playwright','Cypress','SSR'], 'Aplicación Angular probada, animada de forma accesible e hidratada sin divergencias.'),
];
