import { CourseModule, createModule as m } from '../course-module.model';

export const DEVOPS_MODULES: CourseModule[] = [
  m(0, 'Linux y shell scripting para DevOps', 'Linux y shell', 'Fundamentos', '3 h', '#475569',
    'La base de todo pipeline: navegar, automatizar y depurar desde la terminal sin depender de una interfaz gráfica.',
    ['Sistema de archivos y permisos (chmod/chown)', 'Procesos, señales y jobs en segundo plano', 'Pipes, redirección y filtros (grep, awk, sed)', 'Variables de entorno y scripts bash robustos (set -euo pipefail)', 'Cron y tareas programadas', 'Hardening: SSH sin contraseña, firewalls (ufw/iptables), SELinux/AppArmor', 'Redes: modelo OSI, TCP/IP, DNS y balanceadores de carga', 'Cultura DevOps y ciclo Plan→Code→Build→Test→Release→Deploy→Operate→Monitor'],
    [
      'Crea un archivo y cambia sus permisos con chmod para que solo el dueño pueda escribir, y verifica con ls -l',
      'Escribe un script bash con set -euo pipefail que falle inmediatamente si un comando intermedio falla',
      'Combina grep, awk y sed en un solo pipe para extraer y transformar líneas de un archivo de log',
      'Lanza un proceso en background con &, listalo con jobs, y termínalo con kill',
      'Programa una tarea con cron que ejecute un script cada 5 minutos y verifica su ejecución en los logs',
    ],
    ['¿Por qué set -euo pipefail debería ser el estándar en cualquier script de CI/CD?', '¿Qué diferencia hay entre una señal SIGTERM y SIGKILL?'],
    ['Bash', 'Linux'],
    'Script bash idempotente que prepara un entorno de desarrollo desde cero.'),
  m(1, 'Git avanzado y estrategias de branching', 'Git avanzado', 'Fundamentos', '2 h 30 min', '#475569',
    'Más allá de add/commit/push: history rewriting, branching a escala de equipo y resolución de conflictos sin miedo.',
    ['Trunk-based development vs GitFlow', 'Rebase interactivo vs merge', 'Bisect para encontrar regresiones', 'Hooks de Git y commits firmados', 'Monorepos vs polyrepos', 'git cherry-pick, git stash, git reset vs git revert', 'git reflog, git worktree y git submodule'],
    [
      'Crea 3 commits desordenados y límpialos en uno solo con git rebase -i',
      'Provoca un conflicto de merge intencional entre dos ramas y resuélvelo manualmente',
      'Usa git bisect para encontrar el commit exacto que introdujo un bug en un repositorio con varios commits',
      'Configura un pre-commit hook que bloquee un commit si el código no pasa el linter',
      'Documenta en una página la diferencia entre trunk-based development y GitFlow, y cuál usarías para un equipo de 5 personas',
    ],
    ['¿Por qué rebase produce un historial más limpio que merge, y qué riesgo tiene en ramas compartidas?', '¿Qué problema resuelve git bisect que revisar commits uno por uno no resuelve eficientemente?'],
    ['Git'],
    'Repositorio con historial limpio usando rebase y una estrategia de branching documentada.'),
  m(2, 'Docker: imágenes y buenas prácticas', 'Docker', 'Fundamentos', '3 h', '#475569',
    'Empaqueta cualquier aplicación en una imagen reproducible. Entiende capas, cache de build y por qué el tamaño de imagen importa.',
    ['Dockerfile multi-stage', 'Capas e invalidación de cache', 'Imágenes base distroless/alpine', 'Volúmenes vs bind mounts', 'Redes en Docker', 'Registries: Docker Hub, AWS ECR, Azure Container Registry, Harbor'],
    [
      'Escribe un Dockerfile de una sola etapa para una API propia y mide el tamaño final de la imagen',
      'Reescríbelo como multi-stage y compara el tamaño — documenta la diferencia',
      'Reordena las instrucciones del Dockerfile para maximizar el cache de capas (copia package.json antes que el resto del código)',
      'Cambia la imagen base a una variante alpine o distroless y verifica que la app sigue funcionando',
      'Monta un volumen para persistir datos entre reinicios del contenedor y verifica que sobreviven a un docker rm',
    ],
    ['¿Por qué el orden de las instrucciones en un Dockerfile afecta directamente la velocidad de build?', '¿Qué riesgo de seguridad reduce una imagen distroless frente a una basada en Ubuntu completo?'],
    ['Docker'],
    'Imagen Docker optimizada (multi-stage, <100MB) de una API propia.'),
  m(3, 'Docker Compose y orquestación local', 'Docker Compose', 'Fundamentos', '2 h', '#475569',
    'Levanta arquitecturas completas con un solo comando, igual que ya haces con Cloud Local en este mismo proyecto.',
    ['Servicios, dependencias y healthchecks', 'Variables de entorno y .env', 'Redes y descubrimiento por nombre de servicio', 'Perfiles para distintos entornos'],
    [
      'Escribe un docker-compose.yml con una app, una base de datos y una caché Redis',
      'Agrega un healthcheck a la base de datos y configura depends_on con condition: service_healthy en la app',
      'Externaliza la configuración sensible en un archivo .env y verifica que docker compose la inyecta correctamente',
      'Verifica que la app puede llamar a la base de datos por su nombre de servicio (no localhost) gracias a la red interna de Compose',
      'Configura perfiles para levantar solo un subconjunto de servicios según el entorno (dev vs test)',
    ],
    ['¿Por qué depends_on sin healthcheck no garantiza que el servicio dependiente ya esté listo para recibir tráfico?', '¿Cómo resuelven los contenedores el nombre de otro servicio sin IPs hardcodeadas?'],
    ['Docker Compose'],
    'docker-compose.yml que levanta app + base de datos + caché con healthchecks.'),
  m(4, 'CI: pipelines automatizados', 'CI', 'Aplicación', '3 h', '#475569',
    'Cada commit se construye, prueba y valida solo. Aprende a diseñar pipelines rápidos y confiables.',
    ['Jobs, steps y matrices de build', 'Cache de dependencias en CI', 'Artifacts y reportes de cobertura', 'Pipelines como código (GitHub Actions/GitLab CI)'],
    [
      'Crea un workflow de GitHub Actions que corra lint y tests en cada pull request',
      'Agrega cache de node_modules (o el gestor de paquetes que uses) y mide la mejora de velocidad',
      'Configura una matriz de build que corra los tests en 2 versiones distintas del runtime',
      'Sube el reporte de cobertura como artifact descargable desde la ejecución del workflow',
      'Haz que el pipeline falle intencionalmente (rompe un test) y verifica que bloquea el merge del PR',
    ],
    ['¿Qué gana un equipo al tener CI obligatorio en cada PR, más allá de "atrapar bugs"?', '¿Por qué cachear dependencias reduce significativamente el tiempo de un pipeline?'],
    ['GitHub Actions', 'GitLab CI'],
    'Pipeline CI que corre lint, tests y build en cada pull request.'),
  m(5, 'CD: estrategias de despliegue', 'CD', 'Aplicación', '3 h', '#475569',
    'Despliega sin downtime y con capacidad de revertir en segundos cuando algo sale mal.',
    ['Blue-green deployment', 'Canary releases', 'Rolling updates', 'Feature flags vs branches por entorno', 'Rollback automático por métricas'],
    [
      'Documenta con un diagrama la diferencia entre blue-green, canary y rolling update',
      'Configura un pipeline de CD que despliegue automáticamente a un entorno de staging tras pasar CI',
      'Simula un canary release: despliega una nueva versión a un subconjunto pequeño de instancias antes que al resto',
      'Implementa un feature flag simple (variable de entorno o servicio externo) que active una funcionalidad sin un nuevo deploy',
      'Diseña (sin implementar completo) un rollback automático que revierta el deploy si la tasa de error supera un umbral',
    ],
    ['¿Cuándo elegirías blue-green sobre canary, y viceversa?', '¿Qué ventaja da un feature flag sobre desplegar directamente el código nuevo a todos los usuarios?'],
    ['GitHub Actions', 'Argo CD'],
    'Pipeline CD que despliega con estrategia canary y rollback automático.'),
  m(6, 'Kubernetes: fundamentos', 'Kubernetes I', 'Integración', '4 h', '#475569',
    'El orquestador de contenedores estándar de la industria. Pods, deployments y services explicados desde cero.',
    ['Pod, ReplicaSet, Deployment', 'Service (ClusterIP, NodePort, LoadBalancer)', 'ConfigMaps y Secrets', 'kubectl esencial', 'Namespaces', 'StatefulSets, DaemonSets, Jobs y CronJobs', 'Persistent Volumes, PVCs y StorageClasses'],
    [
      'Crea un cluster local con kind o minikube y verifica con kubectl get nodes',
      'Despliega tu propia app con un Deployment de 3 réplicas y verifica con kubectl get pods',
      'Expón el Deployment con un Service tipo ClusterIP y accede a él con kubectl port-forward',
      'Crea un ConfigMap y un Secret, e inyéctalos como variables de entorno en el Pod',
      'Elimina un Pod manualmente y observa cómo el ReplicaSet lo recrea automáticamente',
    ],
    ['¿Qué diferencia hay entre un Pod, un ReplicaSet y un Deployment — por qué necesitas los tres conceptos?', '¿Por qué guardas información sensible en un Secret y no en un ConfigMap?'],
    ['Kubernetes'],
    'Aplicación desplegada en un cluster Kubernetes local (kind/minikube) con su Service expuesto.'),
  m(7, 'Kubernetes avanzado: Helm e Ingress', 'Kubernetes II', 'Integración', '3 h 30 min', '#475569',
    'Empaqueta tus manifiestos como charts reutilizables y expón tu cluster a internet de forma controlada.',
    ['Helm charts y values', 'Ingress Controllers y reglas de enrutamiento', 'HorizontalPodAutoscaler', 'Probes de liveness y readiness', 'RBAC en Kubernetes', 'Service Mesh: Istio, Linkerd, Envoy y mTLS', 'startupProbe y estrategias Recreate vs RollingUpdate'],
    [
      'Convierte tus manifiestos YAML del módulo anterior en un Helm chart con values.yaml parametrizable',
      'Instala un Ingress Controller en tu cluster local y crea una regla que enrute un dominio a tu Service',
      'Configura un HorizontalPodAutoscaler que escale tu Deployment según uso de CPU',
      'Agrega probes de liveness y readiness a tu Deployment y verifica con kubectl describe pod que Kubernetes las usa',
      'Crea un Role y un RoleBinding que limiten qué puede hacer una cuenta de servicio específica',
    ],
    ['¿Qué diferencia hay entre un readiness probe y un liveness probe?', '¿Qué ventaja real da Helm sobre aplicar YAMLs sueltos con kubectl apply?'],
    ['Helm', 'Kubernetes'],
    'Helm chart propio con autoscaling e Ingress configurado.'),
  m(8, 'Infraestructura como código con Terraform', 'Terraform', 'Integración', '3 h 30 min', '#475569',
    'Describe tu infraestructura completa en archivos versionables, con estado y plan de cambios antes de aplicar.',
    ['Providers, resources y data sources', 'State remoto y locking', 'Módulos reutilizables', 'terraform plan vs apply', 'Workspaces para múltiples entornos', 'Ansible: playbooks, roles, inventory y módulos', 'Pulumi como alternativa a HCL (IaC con lenguajes de programación)'],
    [
      'Escribe un archivo .tf que provisione un recurso simple (puede ser contra AWS local) y ejecuta terraform plan antes de aplicar',
      'Aplica el cambio con terraform apply y verifica el recurso creado',
      'Modifica el recurso y observa cómo terraform plan muestra exactamente el diff antes de aplicar',
      'Extrae la definición en un módulo reutilizable con variables de entrada',
      'Configura un backend de estado remoto (o documenta cómo lo harías) para evitar conflictos entre miembros del equipo',
    ],
    ['¿Por qué nunca deberías editar el archivo de estado de Terraform a mano?', '¿Qué problema resuelve el locking del estado remoto cuando trabajas en equipo?'],
    ['Terraform'],
    'Módulo Terraform que provisiona la infraestructura base de un proyecto en un proveedor cloud.'),
  m(9, 'Observabilidad: Prometheus y Grafana', 'Observabilidad', 'Experto', '3 h', '#475569',
    'Sin métricas no sabes si tu sistema está sano. Aprende el modelo de series temporales y cómo alertar antes del incidente.',
    ['Modelo de métricas de Prometheus (counter, gauge, histogram)', 'PromQL esencial', 'Dashboards en Grafana', 'Alertmanager y reglas de alerta', 'SLI/SLO/SLA', 'OpenTelemetry como estándar de instrumentación', 'Métricas DORA: Lead Time, Deployment Frequency, MTTR, Change Failure Rate'],
    [
      'Expón una métrica counter de requests totales desde tu propia API y verifica que Prometheus la scrapea',
      'Escribe una query PromQL que calcule la tasa de requests por segundo en los últimos 5 minutos',
      'Crea un dashboard en Grafana que visualice esa métrica en tiempo real',
      'Configura una regla de alerta que dispare si la tasa de error supera el 5% durante 2 minutos',
      'Define un SLO propio (ej. 99% de requests bajo 200ms) y documenta cómo lo medirías',
    ],
    ['¿Qué diferencia hay entre un counter y un gauge en Prometheus?', '¿Por qué un SLO es más útil para el negocio que solo monitorear "está caído / no está caído"?'],
    ['Prometheus', 'Grafana'],
    'Dashboard de Grafana con métricas reales de una app y una alerta configurada.'),
  m(10, 'Logging centralizado', 'Logging', 'Experto', '2 h 30 min', '#475569',
    'Centraliza logs de múltiples servicios para poder buscarlos y correlacionarlos en segundos, no en horas.',
    ['Logging estructurado (JSON)', 'Pipeline ELK/EFK', 'Loki + Grafana como alternativa ligera', 'Correlation ID a través de servicios'],
    [
      'Configura tu app para loguear en formato JSON estructurado en vez de texto libre',
      'Levanta Loki + Grafana (o ELK) en Docker Compose y envía los logs de tu app ahí',
      'Busca y filtra logs por un campo específico (ej. nivel de error) desde Grafana',
      'Propaga un correlation ID entre dos servicios que se comunican entre sí, y búscalo en el sistema centralizado para ver el flujo completo',
    ],
    ['¿Por qué buscar en logs centralizados es mucho más rápido que entrar a cada contenedor con docker logs?', '¿Qué ventaja tiene Loki (indexa solo metadata) frente a Elasticsearch (indexa todo el contenido)?'],
    ['Loki', 'Elasticsearch'],
    'Stack de logging centralizado que correlaciona logs de al menos dos servicios.'),
  m(11, 'Seguridad DevSecOps', 'DevSecOps', 'Experto', '2 h 30 min', '#475569',
    'La seguridad no es un paso final: se integra en cada etapa del pipeline.',
    ['Gestión de secretos (Vault, SOPS)', 'Escaneo de imágenes y dependencias (Trivy, Snyk)', 'Principio de menor privilegio en CI/CD', 'SBOM y supply chain security', 'SAST, DAST y SCA: diferencias y herramientas (OWASP ZAP, Burp Suite)'],
    [
      'Escanea tu propia imagen Docker con Trivy y revisa las vulnerabilidades reportadas',
      'Agrega el escaneo de Trivy como un paso del pipeline de CI que bloquee el merge si hay vulnerabilidades críticas',
      'Configura secretos del pipeline (tokens, credenciales) usando los secrets nativos de GitHub Actions, nunca hardcodeados',
      'Revisa los permisos del token por defecto de tu pipeline de CI y redúcelos al mínimo necesario',
      'Genera un SBOM (lista de dependencias) de tu proyecto y documenta para qué sirve ante una vulnerabilidad reportada en una librería',
    ],
    ['¿Por qué escanear la imagen en CI es mejor que descubrir la vulnerabilidad ya en producción?', '¿Qué es el principio de menor privilegio aplicado a un pipeline de CI/CD?'],
    ['Trivy', 'Vault'],
    'Pipeline que escanea vulnerabilidades de la imagen y bloquea el deploy si hay críticas.'),
  m(12, 'DevOps y este curso: del laboratorio a la nube', 'DevOps + Cloud', 'Experto', '2 h', '#475569',
    'Conecta todo lo aprendido aquí con el track Cloud Local: cómo el mismo pipeline despliega a AWS, Azure o GCP reales.',
    ['De cloud local a un proveedor cloud real', 'Gestión de secretos cloud-native (Secrets Manager/Key Vault)', 'IaC multi-nube', 'Checklist de salida a producción', 'GitOps con ArgoCD y FluxCD', 'Platform Engineering: Internal Developer Platforms (IDPs)'],
    [
      'Toma un módulo Terraform escrito contra AWS local y documenta los cambios mínimos para apuntarlo a AWS real',
      'Compara cómo gestionarías secretos en este pipeline usando Secrets Manager (AWS) en vez de variables de entorno locales',
      'Construye una checklist de salida a producción propia: observabilidad, rollback, seguridad, costos',
      'Aplica esa checklist a un proyecto real tuyo (de este curso o de otro track) y documenta qué falta',
    ],
    ['¿Qué tan parecido es realmente desplegar en cloud local vs a un proveedor cloud real, según lo que viste en el track Cloud?', '¿Qué ítem de tu checklist de producción consideras más fácil de pasar por alto?'],
    ['Terraform', 'Kubernetes'],
    'Documento de checklist de producción aplicado a un proyecto propio.'),
  m(13, 'Proyecto integrador: pipeline CI/CD completo', 'Proyecto final', 'Experto', '8 h', '#475569',
    'Construye un pipeline de punta a punta: commit → build → test → escaneo de seguridad → despliegue a Kubernetes → observabilidad.',
    ['Pipeline end-to-end', 'Despliegue a Kubernetes con Helm', 'Observabilidad integrada', 'Rollback automatizado'],
    [
      'Diseña el pipeline completo en un diagrama antes de implementarlo: commit → build → test → escaneo → deploy → observabilidad',
      'Implementa cada etapa como un job de CI/CD, encadenadas correctamente',
      'Empaqueta el despliegue como un Helm chart y despliégalo a tu cluster local desde el pipeline',
      'Expón métricas de la app desplegada en un dashboard de Grafana',
      'Documenta el procedimiento de rollback manual (y si es posible, automatízalo por una métrica de error)',
    ],
    ['¿Qué etapa del pipeline fue la más difícil de automatizar correctamente y por qué?', '¿Qué le falta a este pipeline para considerarlo listo para un equipo de producción real?'],
    ['GitHub Actions', 'Kubernetes', 'Helm', 'Prometheus'],
    'Pipeline CI/CD funcional que construye, prueba, escanea y despliega una app a un cluster con métricas visibles.'),
];
