import { CourseModule, createModule as m } from '../course-module.model';

export const FLUTTER_MODULES: CourseModule[] = [
  m(0, 'Fundamentos de Dart', 'Fundamentos', 'Fundamentos', '2 h 30 min', '#02569b',
    'Dart es el lenguaje detrás de Flutter: null safety, async y orientación a objetos con sintaxis familiar.',
    ['Null safety (sound null safety)', 'Clases, mixins y herencia', 'Futures y async/await', 'Colecciones y funciones de orden superior'],
    [
      'Declara una variable nullable (String?) e intenta usarla sin verificar null — observa el error del analizador',
      'Crea una clase Animal y una subclase Perro que la extienda, y aplica un mixin a la subclase',
      'Escribe una función async que simule una petición con Future.delayed y espérala con await',
      'Transforma una lista de objetos con map, where y reduce encadenados',
      'Ejecuta dart analyze sobre tu código y corrige cualquier advertencia de null safety',
    ],
    ['¿Qué garantiza el "sound null safety" de Dart que JavaScript no garantiza por defecto?', '¿Qué diferencia hay entre herencia simple y un mixin en Dart?'],
    ['Dart'],
    'Programa de consola en Dart con manejo asíncrono y null safety estricta.'),
  m(1, 'Widgets: stateless vs stateful', 'Widgets', 'Fundamentos', '3 h', '#02569b',
    '"En Flutter todo es un widget". Entiende el árbol de widgets antes de construir pantallas complejas.',
    ['StatelessWidget vs StatefulWidget', 'Árbol de widgets y reconstrucción (rebuild)', 'Widgets de layout (Row, Column, Stack)', 'Keys: cuándo importan', 'initState(), dispose() y didUpdateWidget()', 'Expanded, Flexible, SizedBox y AspectRatio'],
    [
      'Crea un StatelessWidget TarjetaTarea que reciba datos por constructor, sin estado interno',
      'Crea un StatefulWidget con un contador local y observa cómo setState() dispara la reconstrucción',
      'Construye un layout combinando Row, Column y Stack',
      'Reordena una lista de widgets con estado interno (ej. checkboxes) sin Key y observa el bug; corrígelo con una Key apropiada',
      'Documenta la diferencia entre "rebuild" (Flutter) y "re-render" (React) en tus propias palabras',
    ],
    ['¿Cuándo necesitas realmente una Key, más allá de "Flutter lo pide"?', '¿Por qué un StatelessWidget puede seguir siendo "dinámico" si sus datos vienen de un padre que sí tiene estado?'],
    ['Flutter'],
    'Pantalla compuesta por widgets propios reutilizables, con estado local mínimo.'),
  m(2, 'Layout y diseño responsive', 'Layout responsive', 'Fundamentos', '2 h 30 min', '#02569b',
    'Adapta tu UI a teléfonos, tablets y web desde un mismo código.',
    ['MediaQuery y LayoutBuilder', 'Constraints: cómo Flutter calcula tamaños', 'Breakpoints para distintos tamaños de pantalla', 'SafeArea e insets'],
    [
      'Usa MediaQuery.of(context).size para adaptar el padding según el ancho de pantalla',
      'Usa LayoutBuilder para mostrar una columna en teléfono y dos columnas lado a lado en tablet',
      'Define al menos 2 breakpoints propios y aplica un layout distinto en cada rango',
      'Envuelve una pantalla con SafeArea y verifica que el contenido no queda detrás del notch o la barra de estado',
    ],
    ['¿Cómo calcula Flutter el tamaño final de un widget a partir de las constraints que recibe de su padre?', '¿Por qué SafeArea importa más en algunos dispositivos que en otros?'],
    ['Flutter'],
    'Pantalla que se adapta correctamente entre un teléfono y una tablet.'),
  m(3, 'Navegación y rutas', 'Navegación', 'Aplicación', '2 h 30 min', '#02569b',
    'Estructura una app con múltiples pantallas usando enrutamiento declarativo.',
    ['Navigator 1.0 (push/pop) vs 2.0 (declarativo)', 'go_router: rutas, parámetros y guards', 'Deep linking', 'Transiciones personalizadas'],
    [
      'Navega entre dos pantallas con Navigator.push/pop (estilo imperativo clásico)',
      'Reescribe la misma navegación con go_router definiendo rutas declarativas',
      'Pasa un parámetro de ruta (ej. un ID) y léelo en la pantalla de destino',
      'Configura un guard (redirect) que bloquee el acceso a una ruta sin sesión activa',
      'Configura un deep link que abra directamente una pantalla específica desde un link externo',
    ],
    ['¿Qué problema de navegación declarativa resuelve go_router frente al Navigator 1.0 imperativo?', '¿Por qué el deep linking es más directo de configurar con un router declarativo?'],
    ['go_router'],
    'App con rutas declarativas (go_router), una ruta protegida y deep linking.'),
  m(4, 'Gestión de estado', 'Gestión de estado', 'Aplicación', '3 h', '#02569b',
    'Flutter no impone una solución de estado: aprende cuándo usar cada enfoque del ecosistema.',
    ['setState: cuándo es suficiente', 'Provider: inyección y notificación simples', 'Riverpod: providers seguros en tiempo de compilación', 'Bloc/Cubit: estado predecible basado en eventos', 'GetX como alternativa todo-en-uno', 'get_it e injectable para inyección de dependencias'],
    [
      'Implementa una feature simple con setState y documenta sus límites al crecer',
      'Reimplementa la misma feature con Riverpod, usando un Provider para exponer el estado',
      'Consume ese provider desde 2 widgets distintos sin pasar el estado manualmente',
      'Implementa la misma feature una tercera vez con Bloc/Cubit y compara la cantidad de código y la curva de aprendizaje',
      'Documenta un criterio propio: ¿cuándo usarías setState, Riverpod o Bloc?',
    ],
    ['¿Qué garantiza Riverpod "en tiempo de compilación" que Provider no garantiza?', '¿Qué ventaja da el modelo de eventos de Bloc/Cubit para apps con lógica de negocio compleja?'],
    ['Riverpod', 'Bloc'],
    'Feature completa implementada con Riverpod (o Bloc) en vez de setState.'),
  m(5, 'Networking', 'Networking', 'Aplicación', '2 h 30 min', '#02569b',
    'Consume APIs REST reales con manejo de errores y estados de carga explícitos.',
    ['http vs dio', 'Serialización con json_serializable', 'Interceptores (auth, logging)', 'Manejo de errores y estados de carga'],
    [
      'Haz una petición GET con el paquete http contra una API pública',
      'Repite el ejercicio con dio y compara la ergonomía (interceptores, cancelación, timeouts)',
      'Genera clases de modelo con json_serializable para deserializar la respuesta de forma tipada',
      'Modela explícitamente los 3 estados (cargando, éxito, error) en la UI',
      'Agrega un interceptor de dio que incluya un header de autenticación en cada request',
    ],
    ['¿Qué ventajas tiene dio sobre el paquete http nativo para una app de tamaño real?', '¿Por qué generar modelos con json_serializable es más seguro que parsear JSON manualmente con Map<String, dynamic>?'],
    ['dio'],
    'App que consume una API real con estados loading/error/success explícitos.'),
  m(6, 'Persistencia local', 'Persistencia', 'Integración', '2 h 30 min', '#02569b',
    'Guarda datos localmente según la necesidad: clave-valor simple o base de datos estructurada.',
    ['shared_preferences para configuración simple', 'sqflite para datos relacionales', 'Hive como base NoSQL ligera embebida', 'Estrategia offline-first', 'Firebase: Authentication, Firestore, Cloud Functions y FCM'],
    [
      'Guarda una preferencia simple (ej. tema oscuro activado) con shared_preferences y recupérala al iniciar la app',
      'Define una tabla con sqflite y realiza operaciones CRUD básicas',
      'Repite el mismo modelo de datos con Hive y compara la ergonomía frente a sqflite',
      'Implementa una estrategia offline-first simple: la UI lee siempre de la caché local, sincronizada en segundo plano con la API',
    ],
    ['¿Cuándo elegirías Hive sobre sqflite, y viceversa?', '¿Por qué shared_preferences NO es apropiado para guardar una lista grande de objetos estructurados?'],
    ['Hive', 'sqflite'],
    'App con caché local que funciona sin conexión a internet.'),
  m(7, 'Integración con plataformas nativas', 'Platform channels', 'Integración', '2 h', '#02569b',
    'Cuando un plugin no existe, habla directamente con el código nativo de Android e iOS.',
    ['MethodChannel: Dart ↔ Kotlin/Swift', 'Plugins federados', 'Permisos de plataforma', 'Cuándo escribir un platform channel propio'],
    [
      'Crea un MethodChannel simple que invoque código nativo Kotlin desde Dart (ej. obtener la versión del SO)',
      'Implementa el lado Android (Kotlin) que responde a esa invocación',
      'Implementa el lado iOS (Swift) del mismo MethodChannel',
      'Solicita un permiso de plataforma (ej. cámara) y maneja el caso donde el usuario lo rechaza',
    ],
    ['¿Cuándo deberías escribir un platform channel propio en vez de buscar un plugin existente?', '¿Qué hace un "plugin federado" distinto de un plugin simple?'],
    ['Platform Channels'],
    'Platform channel propio que invoca una API nativa simple desde Dart.'),
  m(8, 'Animaciones y rendimiento', 'Animaciones', 'Experto', '2 h 30 min', '#02569b',
    'Flutter renderiza su propio motor gráfico: aprovéchalo para animaciones fluidas a 60/120fps.',
    ['AnimationController y Tween', 'Animaciones implícitas vs explícitas', 'Flutter DevTools: detectar jank', 'const widgets y rebuilds innecesarios', 'RepaintBoundary y shouldRepaint', 'Key especializadas: ValueKey, ObjectKey, UniqueKey y GlobalKey'],
    [
      'Implementa una animación implícita simple con AnimatedContainer',
      'Implementa la misma animación con AnimationController + Tween (animación explícita) y compara el control que da cada enfoque',
      'Abre Flutter DevTools y graba el rendimiento de una pantalla con scroll, identificando frames perdidos (jank)',
      'Marca widgets estáticos como const y mide con DevTools la reducción de rebuilds innecesarios',
    ],
    ['¿Cuándo una animación implícita es suficiente y cuándo necesitas el control de una explícita?', '¿Por qué marcar un widget como const puede mejorar el rendimiento de forma medible?'],
    ['Flutter DevTools'],
    'Animación fluida propia auditada con DevTools sin frames perdidos.'),
  m(9, 'Testing en Flutter', 'Testing', 'Experto', '2 h 30 min', '#02569b',
    'Prueba widgets, lógica e interacción completa de extremo a extremo.',
    ['Unit tests de lógica pura', 'Widget tests con WidgetTester', 'Integration tests end-to-end', 'Mocking de dependencias (mocktail)'],
    [
      'Escribe un unit test de una función pura (ej. validación de formulario) con flutter_test',
      'Escribe un widget test que monte un widget con WidgetTester.pumpWidget y verifique que un texto aparece',
      'Simula un tap en un botón dentro del widget test y verifica el cambio de estado resultante',
      'Mockea una dependencia (ej. un repositorio) con mocktail para aislar el widget test',
      'Escribe un integration test que recorra un flujo completo de la app en un dispositivo/emulador real',
    ],
    ['¿Qué diferencia hay entre un widget test (entorno simulado) y un integration test (dispositivo real)?', '¿Por qué aislar dependencias externas con mocktail hace los widget tests más rápidos y confiables?'],
    ['flutter_test'],
    'Suite de widget tests sobre una feature completa de la app.'),
  m(10, 'Theming, accesibilidad y Material/Cupertino', 'Theming', 'Experto', '2 h', '#02569b',
    'Una app pulida se siente nativa en ambas plataformas sin duplicar código.',
    ['ThemeData y Material 3', 'Adaptación Material vs Cupertino', 'Accesibilidad (Semantics, soporte de lectores de pantalla)', 'Dark mode'],
    [
      'Define un ThemeData con Material 3 (colores, tipografía) aplicado a toda la app',
      'Detecta la plataforma en runtime y muestra un widget Cupertino en iOS y Material en Android para un mismo componente',
      'Agrega Semantics con labels apropiados a elementos sin texto visible, para soporte de TalkBack/VoiceOver',
      'Implementa soporte de dark mode completo, probando ambos modos en un dispositivo real',
    ],
    ['¿Por qué adaptar Material/Cupertino según la plataforma hace que una app Flutter se sienta más nativa?', '¿Qué revela activar un lector de pantalla en tu propia app que no notarías de otra forma?'],
    ['Material 3'],
    'App con theming consistente, dark mode y accesibilidad auditada.'),
  m(11, 'Publicación en App Store y Google Play', 'Publicación', 'Experto', '2 h', '#02569b',
    'Lleva una sola base de código a las dos tiendas de aplicaciones.',
    ['Build de release para Android (App Bundle)', 'Build de release para iOS (Archive)', 'Configuración de iconos y splash screens', 'CI/CD con Codemagic/Fastlane'],
    [
      'Genera un build de release para Android con flutter build appbundle',
      'Genera un build de release para iOS con flutter build ipa (requiere macOS/Xcode)',
      'Configura el ícono de la app y el splash screen con flutter_launcher_icons / flutter_native_splash',
      'Configura un pipeline básico con Codemagic o Fastlane que automatice ambos builds',
    ],
    ['¿Qué pasos de publicación son específicos de cada tienda y cuáles son comunes gracias a una sola base de código?', '¿Qué ventaja da automatizar ambos builds con un solo pipeline en vez de generarlos manualmente?'],
    ['Fastlane'],
    'Builds de release generados para Android e iOS listos para subir a sus tiendas.'),
  m(12, 'Proyecto integrador: app Flutter completa', 'Proyecto final', 'Experto', '7 h', '#02569b',
    'Une widgets, estado, networking y persistencia en una app real multiplataforma.',
    ['Arquitectura por features', 'Gestión de estado con Riverpod/Bloc', 'Persistencia offline-first', 'Tests de widgets clave', 'Clean Architecture: capas Domain, Data y Presentation', 'Internacionalización con intl y flutter_localizations'],
    [
      'Organiza el proyecto por features (lib/features/tareas/, lib/features/auth/) en vez de por tipo de archivo',
      'Implementa gestión de estado con Riverpod o Bloc para toda la app, sin setState disperso',
      'Implementa persistencia offline-first sincronizada con una API real',
      'Escribe widget tests de al menos las 2 pantallas más críticas',
      'Genera los builds de release para Android e iOS',
    ],
    ['¿Qué decisión de arquitectura cambiarías si el equipo creciera a 5 personas trabajando en paralelo?', '¿Qué parte del ecosistema Flutter (widgets, estado, platform channels) te resultó más distinta a lo que conocías de otros frameworks?'],
    ['Flutter', 'Riverpod', 'dio'],
    'App Flutter con datos reales, persistencia offline y tests, corriendo en Android e iOS.'),
  m(13, 'Flutter en producción: seguridad, isolates y operación', 'Producción', 'Experto', '4 h', '#02569b',
    'Opera una aplicación multiplataforma segura, fluida y observable más allá del happy path.',
    ['Modelo de amenazas por plataforma', 'Secretos y almacenamiento seguro', 'Isolates, frame budget y memoria', 'Offline, telemetría y releases'],
    ['Audita permisos, enlaces, plugins y secretos', 'Mueve trabajo CPU-bound fuera del isolate de UI', 'Implementa outbox idempotente y conflictos', 'Define métricas, símbolos, migración y rollback'],
    ['¿Qué riesgo introduce un plugin aunque su API Dart sea segura?', '¿Cuándo un isolate mejora la experiencia y cuándo solo añade complejidad?'],
    ['Flutter DevTools', 'Dart isolates', 'secure storage'],
    'Dossier de producción multiplataforma con pruebas, perfiles y runbook.'),
];
