import { CourseModule, createModule as m } from '../course-module.model';

export const FOUNDATIONS_MODULES: CourseModule[] = [
  m(0, 'Cómo funciona tu entorno de desarrollo', 'Computador y terminal', 'Fundamentos', '4 h', '#6d5dfc',
    'Empieza desde cero absoluto: entiende qué es un computador, cómo organiza archivos el sistema operativo, qué hace una terminal y cómo ejecutar tu primer programa sin copiar comandos a ciegas.',
    [
      'Hardware, sistema operativo, programa y proceso',
      'Archivos, carpetas, rutas absolutas y relativas',
      'Terminal, shell, comando, argumento y código de salida',
      'Editor, archivo fuente, intérprete y salida del programa',
    ],
    [
      'Identifica CPU, memoria, almacenamiento y sistema operativo de tu equipo',
      'Crea desde la terminal una carpeta academia, entra en ella y comprueba la ruta actual',
      'Crea y ejecuta un programa mínimo, explica cada línea y provoca un error deliberado',
      'Documenta el procedimiento en un README con comandos y resultados verificables',
    ],
    [
      '¿Qué diferencia hay entre un programa guardado y un proceso en ejecución?',
      '¿Por qué una ruta relativa depende de la carpeta actual?',
      '¿Qué información aporta el código de salida de un comando?',
    ],
    ['Sistema operativo', 'Terminal', 'Git', 'Visual Studio Code'],
    'Carpeta de trabajo creada desde terminal con primer programa ejecutado, error diagnosticado y README de evidencia.'),
  m(1, 'Pensamiento computacional y programación', 'Lógica y programación', 'Fundamentos', '6 h', '#6d5dfc',
    'Aprende a convertir un problema cotidiano en datos, decisiones, repeticiones y funciones verificables antes de entrar en programación orientada a objetos o frameworks.',
    [
      'Problema, algoritmo, entrada, proceso, salida y casos de prueba',
      'Variables, tipos, expresiones y estado',
      'Condiciones, bucles y trazado manual',
      'Funciones, parámetros, retorno, alcance y descomposición',
    ],
    [
      'Diseña en papel el algoritmo para calcular el precio final de una compra',
      'Implementa el algoritmo en Python con validación de entradas',
      'Extrae funciones pequeñas y comprueba cada una con casos normales, límite e inválidos',
      'Construye desde carpeta vacía una calculadora de presupuesto por consola',
    ],
    [
      '¿Qué diferencia hay entre algoritmo y programa?',
      '¿Por qué un caso límite puede revelar errores que el caso feliz no muestra?',
      '¿Qué beneficio aporta una función que hace una sola cosa?',
    ],
    ['Python', 'Pseudocódigo', 'Git'],
    'Calculadora de presupuesto por consola, dividida en funciones, validada con una tabla de casos y documentada.'),
  m(2, 'Estructuras de datos, algoritmos y complejidad', 'Datos y algoritmos', 'Fundamentos', '8 h', '#6d5dfc',
    'Organiza información con listas, diccionarios, pilas y colas; implementa búsquedas y ordenamientos; y compara soluciones usando corrección, tiempo y memoria.',
    [
      'Listas, tuplas, conjuntos y diccionarios',
      'Pilas, colas y modelos de uso',
      'Búsqueda lineal, búsqueda binaria y precondiciones',
      'Ordenamiento, recursión, complejidad temporal y espacial',
    ],
    [
      'Modela un inventario y justifica la estructura elegida para cada operación',
      'Implementa búsqueda lineal y binaria sin usar funciones de biblioteca',
      'Mide experimentalmente el crecimiento con diferentes tamaños de entrada',
      'Construye un gestor de inventario con persistencia JSON y reporte de rendimiento',
    ],
    [
      '¿Por qué una estructura adecuada puede mejorar más que una microoptimización?',
      '¿Qué precondición exige la búsqueda binaria?',
      '¿Qué diferencia hay entre complejidad temporal y tiempo medido?',
    ],
    ['Python', 'JSON', 'Git'],
    'Gestor de inventario con estructuras justificadas, búsquedas comparadas, persistencia JSON y análisis reproducible.'),
  m(3, 'Fundamentos de web, redes y accesibilidad', 'Web y redes', 'Fundamentos', '8 h', '#6d5dfc',
    'Comprende qué ocurre al abrir una URL y construye una web semántica, responsive y accesible antes de utilizar frameworks de frontend o backend.',
    [
      'Cliente, servidor, IP, puerto, DNS, URL y TCP',
      'HTTP: métodos, headers, estados, cuerpo, caché y HTTPS',
      'HTML semántico, formularios, DOM y validación',
      'CSS: cascada, box model, layout responsive y accesibilidad',
    ],
    [
      'Traza desde una URL hasta una respuesta HTTP',
      'Inspecciona peticiones y respuestas con curl y DevTools',
      'Construye una página semántica sin estilos y comprueba su estructura',
      'Convierte la página en un sitio responsive y accesible con pruebas de teclado',
    ],
    [
      '¿Qué diferencia hay entre dominio, IP y puerto?',
      '¿Por qué un código HTTP 404 sigue siendo una respuesta válida?',
      '¿Qué aporta HTML semántico que no aporta una colección de div?',
    ],
    ['HTML', 'CSS', 'HTTP', 'DevTools', 'curl'],
    'Sitio responsive y accesible servido localmente, con informe de red, auditoría de teclado y evidencia HTTP.'),
  m(4, 'Modelado de datos, SQL y persistencia', 'Datos y SQL', 'Aplicación', '10 h', '#6d5dfc',
    'Pasa de archivos JSON a una base relacional: modela entidades y relaciones, consulta con SQL, protege integridad con transacciones y compara responsablemente SQL con NoSQL.',
    [
      'Entidades, atributos, claves, relaciones y normalización',
      'SQL: DDL, CRUD, filtros, agregaciones y JOIN',
      'Índices, planes de consulta y restricciones',
      'Transacciones, ACID, concurrencia y criterios SQL/NoSQL',
    ],
    [
      'Diseña un modelo entidad-relación para inventario y movimientos',
      'Crea el esquema SQLite desde un archivo de migración',
      'Implementa consultas parametrizadas y reportes con JOIN',
      'Demuestra rollback, restricciones e impacto de un índice',
    ],
    [
      '¿Qué diferencia hay entre clave primaria y foránea?',
      '¿Por qué un índice mejora lecturas pero tiene un coste?',
      '¿Qué garantiza una transacción que varias sentencias aisladas no garantizan?',
    ],
    ['SQLite', 'SQL', 'Python', 'Git'],
    'Sistema de inventario persistente con esquema versionado, consultas seguras, transacciones, reportes y análisis SQL/NoSQL.'),
  m(5, 'Testing, depuración, Git y CI', 'Calidad y colaboración', 'Aplicación', '10 h', '#6d5dfc',
    'Convierte código funcional en software confiable: diagnostica con evidencia, automatiza pruebas, trabaja con ramas y revisiones, y ejecuta controles de calidad en CI.',
    [
      'Depuración, hipótesis, debugger, logs y reproducción mínima',
      'Pruebas unitarias, integración, E2E, dobles y cobertura',
      'Git: commits, ramas, merge, conflictos y pull requests',
      'Calidad estática, revisión de código e integración continua',
    ],
    [
      'Reproduce y corrige un defecto mediante una prueba de regresión',
      'Crea una suite pytest con unidades e integración SQLite',
      'Resuelve un conflicto de merge explicando la intención de ambos cambios',
      'Configura CI para ejecutar formato, análisis y pruebas en cada pull request',
    ],
    [
      '¿Qué diferencia hay entre probar una unidad y una integración?',
      '¿Por qué cobertura alta no implica pruebas valiosas?',
      '¿Qué debe comunicar un commit además de cambiar archivos?',
    ],
    ['pytest', 'Git', 'GitHub Actions', 'Ruff'],
    'Repositorio colaborativo del inventario con regresiones, pruebas aisladas/integradas, pipeline CI y revisión documentada.'),
  m(6, 'Seguridad, privacidad y modelado de amenazas', 'Seguridad aplicada', 'Integración', '10 h', '#6d5dfc',
    'Integra seguridad desde requisitos: identifica activos y amenazas, protege identidades y secretos, aplica criptografía mediante primitivas confiables y prueba que acciones no autorizadas fallan.',
    [
      'Activos, actores, límites de confianza, amenazas, riesgo y STRIDE',
      'Autenticación, autorización, sesiones, contraseñas y mínimo privilegio',
      'Hash, MAC, cifrado, TLS, gestión de claves y secretos',
      'Validación, inyección, XSS, CSRF, privacidad, logging y respuesta',
    ],
    [
      'Construye un diagrama de flujo de datos y threat model del inventario',
      'Implementa contraseñas con scrypt, usuarios y autorización por roles',
      'Elimina secretos del repositorio y verifica detección en CI',
      'Añade pruebas negativas, audit log y plan de respuesta a incidentes',
    ],
    [
      '¿Qué diferencia hay entre autenticación y autorización?',
      '¿Por qué una contraseña se hashea y no se cifra para almacenarla?',
      '¿Qué convierte una amenaza en un riesgo priorizable?',
    ],
    ['Python', 'SQLite', 'pytest', 'OWASP'],
    'Inventario endurecido con threat model, credenciales seguras, roles, auditoría, pruebas de abuso y runbook de incidentes.'),
  m(7, 'Requisitos, diseño, arquitectura y mantenimiento', 'Ingeniería de software', 'Integración', '12 h', '#6d5dfc',
    'Diseña software como sistema mantenible: convierte necesidades en requisitos verificables, prioriza atributos de calidad, define límites arquitectónicos y documenta decisiones y evolución.',
    [
      'Stakeholders, requisitos funcionales/no funcionales, historias y criterios',
      'Atributos de calidad, arquitectura, dependencias y diagramas C4',
      'Cohesión, acoplamiento, SOLID, patrones y refactoring',
      'ADRs, documentación, deuda técnica, mantenimiento y evolución',
    ],
    [
      'Entrevista un caso, redacta historias y criterios verificables',
      'Modela contexto, contenedores y componentes del inventario',
      'Refactoriza hacia dominio, aplicación e infraestructura con pruebas',
      'Crea ADRs, roadmap de deuda y plan de evolución compatible',
    ],
    [
      '¿Qué vuelve verificable a un requisito?',
      '¿Por qué una arquitectura depende de atributos de calidad?',
      '¿Cuándo un patrón mejora el diseño y cuándo añade complejidad accidental?',
    ],
    ['C4', 'ADRs', 'Python', 'Git'],
    'Inventario modular con especificación, diagramas, ADRs, refactoring protegido por pruebas y plan de mantenimiento.'),
  m(8, 'Sistemas operativos, concurrencia, Linux y contenedores', 'Ejecución y contenedores', 'Integración', '12 h', '#6d5dfc',
    'Comprende cómo el sistema operativo ejecuta y aísla programas, razona sobre memoria y concurrencia, administra un servicio Linux y empaqueta la aplicación acumulativa en un contenedor reproducible y observable.',
    [
      'Kernel, procesos, archivos, permisos, señales y llamadas al sistema',
      'Memoria, procesos, hilos, condiciones de carrera, bloqueo y sincronización',
      'Shell Linux, procesos, servicios, logs, puertos y diagnóstico operativo',
      'Máquinas virtuales, imágenes, contenedores, namespaces, cgroups y persistencia',
    ],
    [
      'Inspecciona procesos, descriptores, permisos, señales y códigos de salida',
      'Reproduce una condición de carrera y corrígela con una sección crítica mínima',
      'Opera el inventario como servicio, diagnostica logs, salud, recursos y apagado',
      'Construye una imagen reproducible, no root, con volumen, healthcheck y límites',
    ],
    [
      '¿Qué diferencia existe entre programa, proceso e hilo?',
      '¿Por qué una operación aparentemente simple puede fallar bajo concurrencia?',
      '¿Qué aísla un contenedor y qué comparte necesariamente con el host?',
    ],
    ['Linux', 'Python', 'Docker', 'SQLite', 'Git'],
    'Inventario contenerizado con usuario no root, almacenamiento persistente, healthcheck, límites, apagado limpio, prueba concurrente y runbook operativo.'),
  m(9, 'Matemáticas discretas, lógica y probabilidad para software', 'Razonamiento cuantitativo', 'Experto', '12 h', '#6d5dfc',
    'Usa lógica, conjuntos, relaciones, combinatoria, grafos y probabilidad para especificar reglas, demostrar propiedades, diseñar pruebas y tomar decisiones técnicas con datos en lugar de intuición.',
    [
      'Proposiciones, predicados, cuantificadores, equivalencias e invariantes',
      'Conjuntos, funciones, relaciones, inducción y estructuras discretas',
      'Combinatoria, grafos, árboles, recorridos y dependencias',
      'Probabilidad, variables aleatorias, distribuciones, muestreo e inferencia básica',
    ],
    [
      'Formaliza reglas del inventario y encuentra contraejemplos automáticamente',
      'Demuestra por inducción una propiedad de un algoritmo y documenta sus supuestos',
      'Modela dependencias como grafo y detecta ciclos con un recorrido implementado',
      'Diseña un experimento reproducible y comunica incertidumbre sin falsear precisión',
    ],
    [
      '¿Cuál es la diferencia entre probar muchos casos y demostrar una propiedad?',
      '¿Cómo ayuda un grafo a detectar un ciclo de dependencias?',
      '¿Por qué correlación no implica causalidad?',
    ],
    ['Python', 'Hypothesis', 'Graphviz', 'Jupyter', 'Git'],
    'Cuaderno reproducible del inventario con especificaciones lógicas, pruebas generativas, análisis de grafos y experimento probabilístico con conclusiones limitadas por evidencia.'),
  m(10, 'Sistemas distribuidos, resiliencia y observabilidad', 'Sistemas distribuidos', 'Experto', '14 h', '#6d5dfc',
    'Evoluciona el inventario hacia componentes que se comunican por red y aprende a diseñar bajo fallos parciales, mensajes duplicados, relojes imperfectos y dependencias lentas mediante invariantes, idempotencia y evidencia operativa.',
    [
      'Fallos parciales, latencia, tiempo, orden causal y límites de red',
      'Replicación, particiones, consistencia, consenso y compromisos CAP',
      'Mensajería, entrega, idempotencia, reintentos, outbox y sagas',
      'Resiliencia, SLI/SLO, logs, métricas, trazas y respuesta a incidentes',
    ],
    [
      'Simula latencia, timeout, pérdida, duplicación y reordenamiento de mensajes',
      'Define invariantes y el modelo de consistencia requerido por cada operación',
      'Implementa un consumidor idempotente y publicación transaccional con outbox',
      'Instrumenta el flujo, define un SLO y conduce un game day con postmortem',
    ],
    [
      '¿Por qué un timeout no demuestra que la operación no ocurrió?',
      '¿Qué diferencia existe entre consistencia fuerte y disponibilidad?',
      '¿Cómo impide la idempotencia que un reintento duplique un efecto?',
    ],
    ['Python', 'Docker Compose', 'OpenTelemetry', 'Prometheus', 'SQLite'],
    'Inventario distribuido mínimo con outbox, consumidor idempotente, fallos inyectados, telemetría correlacionada, SLO medible, runbook y postmortem sin culpables.'),
];
