import { CourseModule, createModule as m } from '../course-module.model';

export const IOS_MODULES: CourseModule[] = [
  m(0, 'Fundamentos de Swift', 'Fundamentos', 'Fundamentos', '2 h 30 min', '#0a84ff',
    'Swift es un lenguaje moderno con tipado fuerte y seguridad ante nil incorporada desde el diseño.',
    ['Optionals y unwrapping seguro', 'struct vs class: value types vs reference types', 'Protocolos y extensiones', 'Enums con valores asociados'],
    [
      'Declara una variable opcional (String?) e intenta usarla sin desenvolverla — observa el error del compilador',
      'Desenvuelve un optional de forma segura con if let, guard let y el operador ?? (nil coalescing)',
      'Crea un struct Punto y una class Contador, modifica una copia de cada uno y observa la diferencia (value type vs reference type)',
      'Define un protocolo Describible con un método describir() y haz que dos tipos distintos lo implementen',
      'Modela un estado con un enum con valores asociados: enum Resultado { case exito(String); case error(String) }',
    ],
    ['¿Qué problema de NullPointerException previene el sistema de optionals de Swift?', '¿Cuándo elegirías struct sobre class para un modelo de datos?'],
    ['Swift'],
    'Modelo de dominio usando structs, enums con valores asociados y sin force-unwrap.'),
  m(1, 'SwiftUI: vistas y layout declarativo', 'SwiftUI', 'Fundamentos', '3 h', '#0a84ff',
    'Describe la UI como una función del estado, con la sintaxis declarativa nativa de Apple.',
    ['View protocol y composición de vistas', 'Modificadores y orden de aplicación', 'Layout con VStack/HStack/ZStack', 'Previews para iterar rápido', 'didSet/willSet y @propertyWrapper personalizados', 'LazyVGrid y ScrollView'],
    [
      'Crea una vista TarjetaTarea que reciba un título como parámetro y la componga dentro de otra vista',
      'Aplica dos modificadores en distinto orden (.padding().background() vs .background().padding()) y observa la diferencia visual',
      'Construye un layout combinando VStack, HStack y ZStack',
      'Usa el sistema de Previews de Xcode para iterar en una vista sin recompilar la app completa',
      'Extrae una sub-vista reutilizable a partir de un bloque de código repetido en dos pantallas',
    ],
    ['¿Por qué el orden de los modificadores (.padding antes o después de .background) cambia el resultado visual?', '¿Qué ventaja da el sistema de Previews frente a ejecutar la app completa en el simulador para cada cambio?'],
    ['SwiftUI'],
    'Pantalla SwiftUI compuesta a partir de al menos 3 vistas reutilizables propias.'),
  m(2, 'Estado y data flow', 'Estado', 'Fundamentos', '2 h 30 min', '#0a84ff',
    'SwiftUI reacciona a cambios de estado de forma automática; entiende qué property wrapper usar en cada caso.',
    ['@State, @Binding', '@Observable (Observation framework moderno)', '@Environment para inyección de dependencias', 'Identidad vs valor en SwiftUI'],
    [
      'Usa @State en una vista para un contador local y verifica que la vista se redibuja al cambiarlo',
      'Pasa ese estado a una vista hija con @Binding y modifícalo desde el hijo',
      'Crea una clase con @Observable que represente el estado de una pantalla compartido entre varias vistas',
      'Inyecta una dependencia (ej. un servicio) vía @Environment en vez de pasarla manualmente por cada inicializador',
    ],
    ['¿Qué diferencia hay entre @State (estado propio de una vista) y @Binding (referencia al estado de otra)?', '¿Qué resuelve @Observable que ObservableObject + @Published resolvía antes, de forma más simple?'],
    ['SwiftUI'],
    'Formulario con estado compartido entre vistas padre/hijo usando @Binding.'),
  m(3, 'Navegación', 'Navegación', 'Aplicación', '2 h', '#0a84ff',
    'Estructura una app con múltiples pantallas usando las APIs de navegación modernas.',
    ['NavigationStack y NavigationPath', 'Sheets y full screen covers', 'TabView', 'Deep linking', 'Form, Picker, DatePicker, Toggle y Slider', '.swipeActions() y .onDelete() en listas'],
    [
      'Construye un NavigationStack con al menos 3 niveles de profundidad (lista → detalle → sub-detalle)',
      'Usa NavigationPath para navegar programáticamente sin depender de NavigationLink en cada vista',
      'Presenta una vista modal con .sheet() y otra con .fullScreenCover(), y explica cuándo usarías cada una',
      'Construye una TabView con al menos 3 pestañas, cada una con su propio NavigationStack',
    ],
    ['¿Qué ventaja da NavigationPath sobre el manejo de navegación basado en NavigationLink anidados del SwiftUI antiguo?', '¿Cuándo usarías un sheet en vez de un full screen cover?'],
    ['SwiftUI Navigation'],
    'App con navegación tipo stack, una tab bar y al menos un sheet modal.'),
  m(4, 'Concurrencia moderna: async/await', 'Concurrencia', 'Aplicación', '3 h', '#0a84ff',
    'Swift Concurrency reemplaza GCD y callbacks con un modelo estructurado y seguro ante data races.',
    ['async/await y Task', 'Actors para aislar estado mutable', 'Structured concurrency (TaskGroup)', 'MainActor y actualización segura de UI'],
    [
      'Escribe una función async que simule una llamada de red con Task.sleep',
      'Lánzala desde una vista con .task { } y muestra el resultado cuando llega',
      'Crea un actor que encapsule estado mutable compartido y verifica que el compilador previene el acceso no seguro desde fuera',
      'Combina dos llamadas async en paralelo con un TaskGroup y junta sus resultados',
      'Marca una clase con @MainActor y explica por qué garantiza que las actualizaciones de UI ocurren en el hilo principal',
    ],
    ['¿Qué problema de concurrencia (data races) previene un actor que una clase normal no previene?', '¿Por qué async/await es más fácil de razonar que el "callback hell" de versiones anteriores de Swift?'],
    ['Swift Concurrency'],
    'Función async que combina dos llamadas de red en paralelo con TaskGroup.'),
  m(5, 'Networking con URLSession', 'Networking', 'Aplicación', '2 h 30 min', '#0a84ff',
    'Consume APIs REST reales con manejo de errores tipado.',
    ['URLSession con async/await', 'Codable para parsear JSON', 'Manejo de errores con tipos propios', 'Reintentos y cancelación de tareas'],
    [
      'Haz una petición GET con URLSession.shared.data(from:) usando async/await contra una API pública',
      'Define un struct Codable que represente la respuesta y decodifícala con JSONDecoder',
      'Define un enum de error propio (ErrorRed) y lanza el caso apropiado según el código de estado HTTP',
      'Implementa cancelación de una Task en curso cuando el usuario inicia una nueva búsqueda',
      'Agrega reintentos con backoff simple ante un error de red transitorio',
    ],
    ['¿Por qué Codable elimina gran parte del parsing manual de JSON que existía antes en Objective-C/Swift clásico?', '¿Qué ventaja da modelar errores con un enum propio frente a propagar NSError genérico?'],
    ['URLSession'],
    'Cliente de red que consume una API real con manejo de errores tipado.'),
  m(6, 'Persistencia con SwiftData', 'SwiftData', 'Integración', '2 h 30 min', '#0a84ff',
    'Persiste datos localmente con el framework moderno de Apple sobre Core Data.',
    ['@Model y el esquema de SwiftData', 'Queries con @Query', 'Migraciones de esquema', 'Relación con Core Data (cuándo usar cada uno)'],
    [
      'Define un modelo con @Model (ej. Tarea) y configura el ModelContainer en el punto de entrada de la app',
      'Usa @Query en una vista para observar automáticamente los cambios en los datos persistidos',
      'Inserta, actualiza y elimina registros a través del ModelContext y verifica que la vista se actualiza sola',
      'Agrega un campo nuevo al modelo y documenta cómo SwiftData maneja la migración de esquema',
    ],
    ['¿Qué simplifica SwiftData frente a configurar Core Data manualmente (NSManagedObject, NSFetchRequest)?', '¿Cuándo seguirías prefiriendo Core Data directamente sobre SwiftData?'],
    ['SwiftData'],
    'App con persistencia local en SwiftData y una vista que reacciona a cambios.'),
  m(7, 'Combine y programación reactiva', 'Combine', 'Integración', '2 h', '#0a84ff',
    'Antes de async/await, Combine resolvía flujos de datos asíncronos en el ecosistema Apple — sigue presente en mucho código real.',
    ['Publishers y Subscribers', 'Operadores clave (map, debounce, combineLatest)', 'Combine vs async/await: cuándo usar cada uno', 'Integración de Combine con SwiftUI'],
    [
      'Crea un @Published var texto: String en un ObservableObject y observa sus cambios con un sink',
      'Implementa un buscador con debounce(for:scheduler:) sobre los cambios de un campo de texto',
      'Combina dos Publishers con combineLatest y reacciona cuando cualquiera de los dos emite',
      'Documenta en qué casos seguirías usando Combine en vez de async/await en código nuevo',
    ],
    ['¿En qué se parece y en qué difiere Combine de RxJS/RxSwift?', '¿Por qué muchos equipos prefieren async/await para código nuevo y reservan Combine para flujos continuos (streams de eventos)?'],
    ['Combine'],
    'Buscador con debounce implementado con Combine.'),
  m(8, 'Arquitectura MVVM', 'MVVM', 'Integración', '2 h 30 min', '#0a84ff',
    'Organiza una app SwiftUI de tamaño real sin mezclar lógica de negocio con vistas.',
    ['ViewModel observable en SwiftUI', 'Separación de capas (vista, dominio, datos)', 'Inyección de dependencias en SwiftUI', 'Cuándo MVVM es suficiente y cuándo no'],
    [
      'Extrae la lógica de una vista "gorda" (con fetching y validación mezclados con UI) a un @Observable ViewModel',
      'Separa el proyecto en capas: Vistas, ViewModels, Servicios/Repositorios',
      'Inyecta un servicio en el ViewModel a través de su inicializador, no como un singleton global',
      'Documenta un caso donde MVVM simple no alcanza y considerarías una capa adicional (ej. casos de uso)',
    ],
    ['¿Qué problema concreto resuelve separar la lógica de negocio de la vista en SwiftUI?', '¿Cuándo MVVM empieza a quedarse corto para una app que crece?'],
    ['Swift'],
    'App reestructurada en capas (vista/viewmodel/datos) con dependencias inyectadas.'),
  m(9, 'Testing en iOS', 'Testing', 'Experto', '2 h 30 min', '#0a84ff',
    'Prueba lógica y vistas con las herramientas nativas de Xcode.',
    ['XCTest: unit tests clásicos', 'Swift Testing (el nuevo framework de pruebas)', 'Testing de código async/await', 'UI Tests básicos'],
    [
      'Escribe un test con XCTest para una función pura de tu capa de dominio',
      'Reescribe el mismo test con el nuevo framework Swift Testing (@Test, #expect) y compara la sintaxis',
      'Escribe un test de una función async con await dentro del test',
      'Escribe un UI Test básico con XCUITest que verifique que un botón existe y es tappable',
    ],
    ['¿Qué ventaja de legibilidad ofrece Swift Testing sobre XCTest clásico?', '¿Por qué un UI Test es más lento y frágil que un unit test de la capa de dominio?'],
    ['XCTest', 'Swift Testing'],
    'Suite de tests sobre la capa de dominio usando Swift Testing.'),
  m(10, 'Performance, accesibilidad y HIG', 'Performance y HIG', 'Experto', '2 h', '#0a84ff',
    'Una app rápida y accesible que respeta las Human Interface Guidelines se siente "nativa" de verdad.',
    ['Instruments para medir performance', 'Accesibilidad con VoiceOver', 'Human Interface Guidelines esenciales', 'Dynamic Type y dark mode', '@ViewBuilder y .matchedGeometryEffect()', 'Interop con UIKit: UIViewRepresentable y UIViewControllerRepresentable', 'Novedades recientes: Liquid Glass, layouts volumétricos y WebView nativo'],
    [
      'Graba una sesión con Instruments (Time Profiler) sobre una interacción lenta de tu app',
      'Activa VoiceOver en el simulador y navega tu app solo con gestos de accesibilidad',
      'Agrega .accessibilityLabel a elementos sin texto visible que VoiceOver no pudo describir',
      'Verifica que tu app se ve correctamente con Dynamic Type en su tamaño más grande y en modo oscuro',
    ],
    ['¿Qué revela Instruments que el simulador "se ve fluido" no revela?', '¿Por qué seguir las Human Interface Guidelines hace que una app "se sienta" nativa, más allá de usar SwiftUI?'],
    ['Instruments'],
    'Auditoría de accesibilidad (VoiceOver) de una pantalla con mejoras aplicadas.'),
  m(11, 'Publicación en App Store', 'Publicación', 'Experto', '2 h', '#0a84ff',
    'Lleva tu app del simulador a usuarios reales a través de TestFlight y la App Store.',
    ['Certificados y provisioning profiles', 'TestFlight para pruebas beta', 'App Store Connect: metadata y revisión', 'Versionado y builds'],
    [
      'Configura un certificado de distribución y un provisioning profile en tu cuenta de desarrollador',
      'Archiva la app en Xcode (Product > Archive) y súbela a App Store Connect',
      'Configura un grupo de pruebas en TestFlight y agrégate como tester',
      'Completa la metadata básica en App Store Connect (descripción, capturas, política de privacidad)',
      'Incrementa el número de build siguiendo una convención clara antes de cada subida',
    ],
    ['¿Qué diferencia hay entre un certificado de desarrollo y uno de distribución?', '¿Qué ventaja da probar con TestFlight antes de enviar la app a revisión de la App Store?'],
    ['App Store Connect'],
    'Build subido a TestFlight listo para pruebas internas.'),
  m(12, 'Proyecto integrador: app SwiftUI completa', 'Proyecto final', 'Experto', '7 h', '#0a84ff',
    'Une SwiftUI, concurrencia moderna, networking y persistencia en una app real.',
    ['Arquitectura MVVM', 'Networking con async/await', 'Persistencia con SwiftData', 'Tests de la capa de dominio'],
    [
      'Diseña la arquitectura MVVM completa: Vistas SwiftUI, ViewModels @Observable, Servicios/Repositorios',
      'Implementa networking real con URLSession + async/await y manejo de errores tipado',
      'Persiste datos localmente con SwiftData, sincronizados con la API',
      'Escribe tests de la capa de dominio con Swift Testing',
      'Sube un build a TestFlight para pruebas internas',
    ],
    ['¿Qué decisión de arquitectura te resultó más natural en SwiftUI comparado con otros frameworks que conozcas?', '¿Qué parte del proyecto (concurrencia, persistencia, testing) requirió más iteración para sentirse "correcta"?'],
    ['SwiftUI', 'Swift Concurrency', 'SwiftData'],
    'App iOS con SwiftUI, datos reales, persistencia local y tests.'),
  m(13, 'iOS en producción: seguridad, sincronización y operación', 'Producción', 'Experto', '4 h', '#0a84ff',
    'Endurece y opera una app iOS real ante enlaces hostiles, pérdida de red, datos sensibles y releases imperfectos.',
    ['Sandbox, entitlements y Universal Links', 'Keychain, Data Protection y privacidad', 'Sincronización offline y conflictos', 'MetricKit, Instruments y releases seguros'],
    [
      'Construye un modelo de amenazas y audita entitlements, permisos y Universal Links',
      'Protege credenciales con Keychain y define una política de datos, logs, backups y capturas',
      'Implementa una outbox persistente con idempotencia y resolución explícita de conflictos',
      'Instrumenta signposts y MetricKit, y ensaya migración, rollback y despliegue gradual',
      'Entrega evidencias verificables mediante pruebas y una rúbrica de preparación operativa',
    ],
    ['¿Por qué el sandbox no vuelve confiable un Universal Link?', '¿Qué diferencia hay entre reintentar una petición y garantizar idempotencia?'],
    ['Keychain', 'BackgroundTasks', 'MetricKit', 'Instruments'],
    'Dossier de preparación para producción con amenaza, sincronización, telemetría y plan de release.'),
  m(14, 'SwiftUI Master: pruebas, animación e interoperabilidad', 'SwiftUI Master', 'Experto', '9 h', '#0a84ff',
    'Prueba flujos SwiftUI, domina Combine e integra UIKit con animaciones accesibles y rendimiento medido.',
    ['XCTest, expectations y Swift Testing', 'ViewInspector con criterio', 'Combine publishers, operators y schedulers', 'withAnimation, transition y matchedGeometryEffect', 'UIViewRepresentable', 'UIViewControllerRepresentable y coordinators'],
    ['Prueba async', 'Inspecciona estado', 'Controla scheduler', 'Anima transición', 'Integra vista UIKit', 'Evita ciclo de retención'],
    ['¿Qué prueba es frágil con ViewInspector?', '¿Quién posee el coordinator?'], ['XCTest','Combine','ViewInspector','UIKit','SwiftUI'], 'Feature SwiftUI probada con Combine controlado, transición e interoperabilidad UIKit.'),
];
