import { CourseModule, createModule as m } from '../course-module.model';

export const JAVA_MODULES: CourseModule[] = [
  m(0, 'Sintaxis, tipos y el modelo de la JVM', 'Fundamentos', 'Fundamentos', '2 h 30 min', '#5382a1',
    'Java compila a bytecode y corre sobre una máquina virtual. Entiende ese modelo antes de escribir tu primera clase.',
    ['Tipos primitivos vs referencias', 'Compilación a bytecode y JVM', 'public static void main: qué significa cada palabra', 'JDK vs JRE vs JVM'],
    [
      'Escribe un Hola.java con public static void main, compílalo con javac y ejecútalo con java — observa el .class generado',
      'Declara variables de los 8 tipos primitivos de Java (int, long, double, char, boolean, etc.) y un String (tipo referencia)',
      'Lee un número del usuario con Scanner, valida que sea un entero válido y maneja el caso de entrada incorrecta',
      'Investiga la diferencia entre JDK, JRE y JVM y documenta cuál necesitas para desarrollar vs solo ejecutar Java',
      'Usa javap -c Hola.class para ver el bytecode generado por tu programa',
    ],
    ['¿Por qué Java compila a bytecode en vez de código máquina nativo directamente?', '¿Qué significa cada palabra de public static void main(String[] args)?'],
    ['Java'],
    'Programa de consola que procesa entrada del usuario con validación de tipos.'),
  m(1, 'Programación orientada a objetos', 'POO', 'Fundamentos', '3 h', '#5382a1',
    'Las cuatro bases de la POO aplicadas con la sintaxis y convenciones reales de Java.',
    ['Clases, herencia e interfaces', 'Polimorfismo y sobrecarga vs sobreescritura', 'Modificadores de acceso', 'Clases abstractas vs interfaces'],
    [
      'Crea una clase Animal con un método hablar() y una subclase Perro que lo sobreescriba (@Override)',
      'Define una interfaz Volador con un método volar() e impleméntala en una clase Pajaro',
      'Crea una clase abstracta Forma con un método abstracto area() y dos subclases concretas (Circulo, Cuadrado)',
      'Sobrecarga un método sumar() con distintas firmas (int, int) y (double, double) y demuestra la diferencia con sobreescritura',
      'Aplica los modificadores private, protected y public a campos de una clase y explica cuándo usar cada uno',
    ],
    ['¿Qué diferencia hay entre sobrecargar (overload) y sobreescribir (override) un método?', '¿Cuándo usarías una clase abstracta y cuándo una interfaz?'],
    ['Java'],
    'Jerarquía de clases con al menos una interfaz y una clase abstracta.'),
  m(2, 'Colecciones y genéricos', 'Colecciones', 'Fundamentos', '2 h 30 min', '#5382a1',
    'El Java Collections Framework es la base de cualquier programa real: elige la estructura correcta para cada caso.',
    ['List, Set, Map y sus implementaciones', 'Genéricos: <T> y wildcards', 'Comparable vs Comparator', 'Iteradores y for-each', 'Queue, Deque y ConcurrentHashMap', 'Type erasure y @SafeVarargs'],
    [
      'Compara ArrayList vs LinkedList insertando 100,000 elementos al inicio de cada uno y midiendo el tiempo',
      'Usa un HashSet para eliminar duplicados de una lista y un TreeSet para mantenerla ordenada automáticamente',
      'Crea una clase genérica Caja<T> que almacene y devuelva un valor de cualquier tipo',
      'Implementa Comparable en una clase Persona (por edad) y luego ordénala de forma distinta con un Comparator externo (por nombre)',
      'Recorre un Map<String, Integer> con un for-each usando entrySet()',
    ],
    ['¿Cuándo elegirías un LinkedList sobre un ArrayList?', '¿Qué diferencia hay entre implementar Comparable y pasar un Comparator?'],
    ['Java Collections'],
    'Estructura de datos propia genérica (ej. cola de prioridad) con tests.'),
  m(3, 'Excepciones y manejo de recursos', 'Excepciones', 'Fundamentos', '2 h', '#5382a1',
    'Maneja errores de forma explícita y libera recursos sin fugas.',
    ['Checked vs unchecked exceptions', 'try-with-resources', 'Excepciones personalizadas', 'Buenas prácticas: no tragar excepciones'],
    [
      'Provoca una excepción checked (IOException) y una unchecked (NullPointerException) y explica la diferencia en cómo el compilador las trata',
      'Lee un archivo con try-with-resources y verifica que el recurso se cierra automáticamente incluso si ocurre un error',
      'Crea una excepción personalizada SaldoInsuficienteException que extienda RuntimeException',
      'Escribe un catch que "trague" silenciosamente una excepción (catch vacío) y explica por qué es una mala práctica',
      'Corrige el ejemplo anterior registrando el error apropiadamente antes de decidir si relanzarlo o manejarlo',
    ],
    ['¿Por qué el compilador obliga a manejar las checked exceptions y no las unchecked?', '¿Qué problema causa un catch vacío que "traga" la excepción?'],
    ['Java'],
    'Lector de archivos con manejo robusto de excepciones y try-with-resources.'),
  m(4, 'Streams y programación funcional', 'Streams', 'Aplicación', '3 h', '#5382a1',
    'Desde Java 8, procesa colecciones con un estilo declarativo cercano al funcional.',
    ['Stream API: map/filter/reduce/collect', 'Lambdas y referencias a métodos', 'Optional: evitar null de forma explícita', 'Streams paralelos: cuándo ayudan', 'peek, distinct, sorted, limit y skip', 'Collectors: groupingBy, partitioningBy y joining', '@FunctionalInterface y sus reglas'],
    [
      'Dada una lista de Personas, usa stream().filter().map().collect(Collectors.toList()) para obtener los nombres de los mayores de 18',
      'Usa reduce() para sumar los salarios de una lista de empleados',
      'Reemplaza una lambda verbosa por una referencia a método (Persona::getNombre)',
      'Cambia un método que devuelve null por uno que devuelve Optional<Persona> y maneja el caso vacío con orElseThrow',
      'Compara el tiempo de procesar una lista de 10 millones de elementos con stream() vs parallelStream()',
    ],
    ['¿Por qué Optional reemplaza con ventaja a devolver null directamente?', '¿Cuándo un stream paralelo realmente mejora el rendimiento y cuándo lo empeora?'],
    ['Java Streams'],
    'Pipeline de procesamiento de datos con Streams que reemplaza loops manuales.'),
  m(5, 'Concurrencia: hilos y virtual threads', 'Concurrencia', 'Aplicación', '3 h 30 min', '#5382a1',
    'Java moderno (21+) cambia el juego de la concurrencia con virtual threads de bajo costo.',
    ['Thread, Runnable y ExecutorService', 'CompletableFuture', 'Virtual threads (Project Loom, Java 21)', 'Condiciones de carrera y sincronización', 'ReentrantLock, Semaphore, CountDownLatch y CyclicBarrier', 'ScheduledExecutorService e invokeAll()'],
    [
      'Crea y lanza un Thread manualmente, luego repite lo mismo con un ExecutorService de un pool fijo',
      'Provoca intencionalmente una condición de carrera (dos hilos incrementando un contador sin sincronizar) y corrígela con synchronized',
      'Compón dos llamadas asíncronas con CompletableFuture.thenCompose y maneja errores con exceptionally',
      'Crea 100,000 virtual threads (Java 21+) con Executors.newVirtualThreadPerTaskExecutor() y compara el uso de memoria contra threads de plataforma',
      'Mide la latencia de procesar 1000 tareas con I/O bloqueante usando threads de plataforma vs virtual threads',
    ],
    ['¿Qué hace a los virtual threads tan baratos comparados con los threads de plataforma tradicionales?', '¿Por qué una condición de carrera puede no manifestarse en pruebas pero sí en producción?'],
    ['Java Concurrency'],
    'Servicio concurrente que procesa N tareas en paralelo usando virtual threads.'),
  m(6, 'I/O, NIO.2 y serialización', 'I/O', 'Aplicación', '2 h', '#5382a1',
    'Lee, escribe y serializa datos de forma eficiente con la API moderna de archivos.',
    ['java.nio.file: Path y Files', 'Serialización con Jackson/Gson', 'Lectura de archivos grandes con buffers', 'Recursos en el classpath'],
    [
      'Lee y escribe un archivo de texto usando Files.readString y Files.writeString (NIO.2)',
      'Serializa un objeto Java a JSON con Jackson y deserialízalo de vuelta, verificando que los datos coinciden',
      'Lee un archivo grande con un BufferedReader línea por línea, sin cargarlo completo en memoria',
      'Carga un archivo de configuración desde el classpath con getResourceAsStream',
      'Maneja correctamente el caso donde el archivo a leer no existe, con un mensaje de error claro',
    ],
    ['¿Qué ventaja da java.nio.file.Path sobre la antigua clase File?', '¿Por qué leer un archivo grande con buffer evita problemas de memoria que readAllBytes no evita?'],
    ['Jackson'],
    'Utilidad que lee/escribe JSON desde y hacia disco con manejo de errores.'),
  m(7, 'Records, sealed classes y pattern matching', 'Java moderno', 'Integración', '2 h 30 min', '#5382a1',
    'Las features de Java 17-21 reducen boilerplate y hacen el modelado de datos más expresivo.',
    ['record para modelos inmutables', 'sealed classes/interfaces', 'Pattern matching en switch e instanceof', 'Text blocks'],
    [
      'Define un record Punto(int x, int y) y verifica que genera automáticamente equals, hashCode y toString',
      'Define una sealed interface Forma permits Circulo, Cuadrado y modela ambas como records',
      'Escribe un switch con pattern matching que maneje exhaustivamente todos los casos de la sealed interface, sin un default',
      'Usa pattern matching para instanceof: if (obj instanceof Circulo c) en vez del casteo manual clásico',
      'Escribe un bloque de texto multilínea con text blocks (""") para una consulta SQL larga',
    ],
    ['¿Qué garantiza el compilador cuando usas switch exhaustivo sobre una sealed interface?', '¿Qué boilerplate elimina record comparado con una clase POJO tradicional?'],
    ['Java 21'],
    'Modelo de dominio inmutable usando records y sealed interfaces con pattern matching.'),
  m(8, 'Build tools: Maven y Gradle', 'Maven/Gradle', 'Integración', '2 h', '#5382a1',
    'Gestiona dependencias y el ciclo de build de un proyecto Java real.',
    ['pom.xml vs build.gradle.kts', 'Ciclo de vida de build', 'Gestión de dependencias y scopes', 'Multi-módulo'],
    [
      'Crea un proyecto con Maven (mvn archetype:generate) y otro con Gradle (gradle init) y compara la estructura generada',
      'Agrega una dependencia externa (ej. Jackson) en ambos formatos y ejecuta el build',
      'Ejecuta el ciclo de vida completo de Maven: mvn clean compile test package',
      'Configura un scope test-only para una dependencia (ej. JUnit) que no debe ir al artefacto final',
      'Estructura un proyecto multi-módulo con un módulo core y un módulo api que dependa de core',
    ],
    ['¿Qué ventaja tiene Gradle (Kotlin DSL) sobre el XML de Maven, y qué desventaja?', '¿Por qué separar dependencias por scope (compile, test, runtime) importa para el tamaño del artefacto final?'],
    ['Maven', 'Gradle'],
    'Proyecto multi-módulo con Gradle (o Maven) y dependencias bien acotadas.'),
  m(9, 'Testing con JUnit 5 y Mockito', 'Testing', 'Integración', '2 h 30 min', '#5382a1',
    'Prueba lógica de negocio aislada de sus dependencias externas.',
    ['JUnit 5: anotaciones y ciclo de vida', 'Mockito: mocks, stubs y verify', 'Tests parametrizados', 'Cobertura con JaCoCo', '@CsvSource, @MethodSource y @TestFactory', 'AssertJ y Hamcrest como librerías de aserciones fluidas'],
    [
      'Escribe un test con @Test y assertEquals para un método simple',
      'Usa @BeforeEach para inicializar un objeto compartido antes de cada test',
      'Mockea una dependencia externa (ej. un repositorio) con Mockito y verifica que un servicio la llama correctamente con verify()',
      'Escribe un test parametrizado con @ParameterizedTest que pruebe la misma lógica con 5 conjuntos de datos distintos',
      'Configura JaCoCo y genera un reporte de cobertura, identificando una rama de código sin probar',
    ],
    ['¿Qué diferencia hay entre un mock y un stub en el contexto de Mockito?', '¿Por qué aislar el test de sus dependencias externas (con mocks) hace el test más rápido y confiable?'],
    ['JUnit 5', 'Mockito'],
    'Suite de pruebas unitarias con mocks para un servicio con dependencias externas.'),
  m(10, 'Módulos (JPMS) y proyectos grandes', 'JPMS', 'Experto', '2 h', '#5382a1',
    'Organiza aplicaciones grandes con límites explícitos entre módulos.',
    ['module-info.java', 'Encapsulación fuerte entre módulos', 'Migración de proyectos legacy sin módulos', 'Cuándo JPMS realmente aporta valor'],
    [
      'Crea dos módulos JPMS (core y app) con sus respectivos module-info.java',
      'Declara exports en core solo para el paquete que app necesita usar, y verifica que un paquete no exportado es inaccesible',
      'Declara una dependencia con requires en app hacia core',
      'Documenta qué pasos tomaría migrar un proyecto legacy grande (sin módulos) a JPMS de forma incremental',
    ],
    ['¿Qué encapsulación adicional da JPMS que los modificadores public/private de Java no daban antes?', '¿En qué tipo de proyecto JPMS realmente aporta valor frente a uno donde es complejidad innecesaria?'],
    ['Java Platform Module System'],
    'Proyecto dividido en al menos dos módulos JPMS con dependencias explícitas.'),
  m(11, 'JVM interna: GC, profiling y JIT', 'JVM interna', 'Experto', '3 h', '#5382a1',
    'Entiende qué hace la JVM por debajo para poder diagnosticar problemas de memoria y rendimiento.',
    ['Generaciones de memoria y recolectores (G1, ZGC)', 'Profiling con herramientas estándar (JFR)', 'JIT compilation', 'Flags de JVM más usados', 'jconsole, jvisualvm, jstat y jmap', 'WeakReference, SoftReference, PhantomReference y ReferenceQueue'],
    [
      'Ejecuta tu app con distintos recolectores de basura (-XX:+UseG1GC vs -XX:+UseZGC) y compara las pausas',
      'Graba una sesión de Java Flight Recorder (JFR) de tu aplicación bajo carga',
      'Analiza el reporte JFR e identifica el método que más tiempo de CPU consume',
      'Provoca intencionalmente un OutOfMemoryError con un programa que acumula objetos sin liberarlos, y analiza el heap dump generado',
      'Documenta qué hace el JIT compiler (compilación a código máquina en caliente para el código más ejecutado)',
    ],
    ['¿Por qué un recolector de basura con pausas más cortas (ZGC) puede tener throughput total menor que uno con pausas más largas (G1)?', '¿Qué información te da un heap dump que los logs normales no dan?'],
    ['JVM'],
    'Reporte de profiling de una aplicación propia identificando un cuello de botella real.'),
  m(12, 'Buenas prácticas y patrones de diseño', 'Patrones de diseño', 'Experto', '2 h 30 min', '#5382a1',
    'Los patrones clásicos siguen vigentes en código Java moderno e idiomático.',
    ['Builder, Factory, Strategy', 'Inyección de dependencias manual', 'Principios SOLID aplicados', 'Cuándo NO aplicar un patrón'],
    [
      'Implementa el patrón Builder para construir un objeto Pedido con muchos campos opcionales',
      'Implementa una Factory que devuelva distintas implementaciones de una interfaz según un parámetro',
      'Implementa Strategy para intercambiar algoritmos de descuento sin modificar la clase que los usa',
      'Refactoriza una clase que viola el Single Responsibility Principle, separando sus responsabilidades',
      'Identifica en tu propio código un lugar donde aplicar un patrón sería sobre-ingeniería, y documenta por qué',
    ],
    ['¿Qué problema concreto resuelve el patrón Builder frente a un constructor con 8 parámetros?', '¿Cómo reconoces cuándo NO aplicar un patrón de diseño?'],
    ['Java'],
    'Refactor de un módulo propio aplicando al menos dos patrones de diseño justificados.'),
  m(13, 'Proyecto integrador', 'Proyecto final', 'Experto', '6 h', '#5382a1',
    'Une POO, concurrencia, testing y build reproducible en una aplicación real de consola o servicio.',
    ['Arquitectura por capas', 'Concurrencia con virtual threads', 'Tests con JUnit y Mockito', 'Build reproducible con Gradle/Maven'],
    [
      'Diseña la arquitectura por capas de una aplicación de consola o servicio simple (ej. procesador de pedidos)',
      'Implementa procesamiento concurrente de tareas usando virtual threads',
      'Modela el dominio con records y sealed interfaces donde sea apropiado',
      'Escribe tests unitarios con JUnit 5 y Mockito para la lógica de negocio crítica',
      'Configura el build con Gradle o Maven de forma que cualquier persona pueda clonar y ejecutar con un solo comando',
    ],
    ['¿Qué decisión de diseño cambiarías si tuvieras que escalar esta aplicación a 10x el volumen de datos?', '¿Qué parte del proyecto te hizo apreciar más una feature de Java moderna (records, virtual threads, pattern matching)?'],
    ['Java 21', 'JUnit 5', 'Gradle'],
    'Aplicación Java con lógica concurrente, tests y build reproducible documentado.'),
  m(14, 'Java en producción: memoria, benchmarks y runtime seguro', 'Producción JVM', 'Experto', '7 h', '#5382a1',
    'Endurece el proyecto integrador comprendiendo visibilidad y publicación en el Java Memory Model, midiendo con JMH sin engañar al JIT, defendiendo fronteras de datos y construyendo un runtime mínimo, observable y actualizable.',
    [
      'Java Memory Model, happens-before, volatile, final y publicación segura',
      'JMH, warmup, dead-code elimination, escape analysis y medición responsable',
      'Validación, deserialización, secretos, criptografía y cadena de suministro',
      'jlink/jpackage, Class Data Sharing, contenedores, señales y actualización del runtime',
    ],
    [
      'Reproduce un error de visibilidad y demuestra la corrección mediante relaciones happens-before',
      'Construye un benchmark JMH y refuta una medición ingenua del mismo código',
      'Rechaza grafos y tipos no permitidos y sustituye serialización nativa cuando no es necesaria',
      'Genera una imagen de runtime mínima, no root, con JFR, límites y apagado probado',
    ],
    [
      '¿Por qué volatile aporta visibilidad pero no vuelve atómico a counter++?',
      '¿Cómo puede el JIT eliminar justamente el trabajo que intentas medir?',
      '¿Quién actualiza las vulnerabilidades de una imagen creada con jlink?',
    ],
    ['Java', 'JMH', 'jcstress', 'JFR', 'jlink'],
    'Servicio Java con publicación segura, pruebas de estrés concurrente, benchmark válido, entrada deserializada defensivamente, runtime modular mínimo y runbook de actualización/diagnóstico.'),
];
