import { CourseModule, createModule as m } from '../course-module.model';

export const JAVASCRIPT_MODULES: CourseModule[] = [
  m(0, 'Fundamentos del lenguaje y el entorno', 'Fundamentos', 'Fundamentos', '2 h', '#e9b400',
    'El primer contacto con JavaScript: consola del navegador, Node REPL, variables, tipos primitivos y coerción.',
    ['let/const vs var', 'Tipos primitivos y typeof', 'Coerción implícita y ===  vs ==', 'Plantillas de string (template literals)', 'Entorno: navegador vs Node.js', 'Truthy/falsy y operadores lógicos (&&, ||, ??)', 'Scope global, de función y de bloque; shadowing'],
    [
      'Abre la consola del navegador (F12) y declara una variable con let y otra con const; intenta reasignar ambas y observa el error',
      'Crea un archivo fundamentos.mjs y ejecútalo con node fundamentos.mjs — declara variables de los 7 tipos primitivos (string, number, boolean, null, undefined, symbol, bigint)',
      'Compara 1 == "1" contra 1 === "1" en la consola y explica por qué dan resultados distintos',
      'Escribe una plantilla de string que interpole 3 variables y una expresión matemática: `Total: ${precio * cantidad}`',
      'Usa typeof sobre los 7 tipos primitivos y sobre un array y un objeto — anota qué devuelve typeof null y por qué es un caso especial',
      'Declara la misma variable con let dentro de dos bloques {} distintos y demuestra que no chocan (scope de bloque)',
    ],
    ['¿Por qué typeof null devuelve "object" en vez de "null"?', '¿Qué diferencia real hay entre let y const más allá de la reasignación?', '¿Cuándo usarías == en vez de === de forma intencional?'],
    ['JavaScript'],
    'Script ejecutado en navegador y en Node que produce el mismo resultado.'),
  m(1, 'Operadores, control de flujo y funciones', 'Funciones', 'Fundamentos', '2 h', '#e9b400',
    'Las funciones son ciudadanos de primera clase en JavaScript: se pasan, se devuelven y se componen.',
    ['Funciones declaradas vs expresiones vs arrow functions', 'Parámetros por defecto y rest/spread', 'Funciones de orden superior', 'Control de flujo: if/switch/loops', 'IIFE y el objeto arguments', 'for...of, for...in y for await...of'],
    [
      'Escribe la misma función (sumar dos números) como function declaration, function expression y arrow function',
      'Crea una función con un parámetro por defecto y otra que reciba un número variable de argumentos con rest (...args)',
      'Usa spread para combinar dos arrays y para clonar un objeto sin mutarlo',
      'Escribe debounce(fn, ms): una función de orden superior que retrasa la ejecución de fn hasta que pase ms sin nuevas llamadas',
      'Escribe pipe(...fns) que componga funciones de izquierda a derecha: pipe(f, g, h)(x) === h(g(f(x)))',
      'Reescribe un switch de 4 casos como un objeto de mapeo (lookup table) y compara legibilidad',
    ],
    ['¿Por qué una arrow function no tiene su propio this?', '¿Qué ventaja tiene una función de orden superior frente a duplicar lógica?', '¿Cuándo usarías rest en vez de arguments?'],
    ['JavaScript'],
    'Biblioteca de funciones utilitarias (debounce, pipe, curry) sin dependencias externas.'),
  m(2, 'Scope, closures y el modelo de ejecución', 'Closures', 'Fundamentos', '2 h 30 min', '#e9b400',
    'Entiende qué pasa "por dentro" cuando se ejecuta tu código: call stack, hoisting y por qué un closure recuerda su entorno.',
    ['Scope léxico y closures', 'Hoisting y Temporal Dead Zone', 'Call stack y contexto de ejecución', 'this según el modo de invocación', 'Module pattern y factory functions', 'Execution Context, Scope Chain y Lexical Environment'],
    [
      'Escribe createCounter() que devuelva { increment, decrement, value } usando una variable privada capturada por closure',
      'Demuestra la Temporal Dead Zone: intenta leer una variable let antes de declararla y captura el ReferenceError',
      'Escribe un bucle for con var dentro de un setTimeout y observa el bug clásico (todas las iteraciones imprimen el mismo valor); arréglalo con let',
      'Crea un objeto con un método normal y un método arrow; invócalos como obj.metodo() y compara a qué apunta this en cada uno',
      'Usa call, apply y bind para invocar la misma función con distintos valores de this',
      'Provoca un stack overflow con una recursión sin caso base y lee el stack trace para identificar dónde ocurrió',
    ],
    ['¿Por qué un closure "recuerda" variables que ya deberían haber salido de scope?', '¿Qué problema real resuelve la Temporal Dead Zone?', '¿Qué determina el valor de this: dónde se define la función o cómo se invoca?'],
    ['JavaScript'],
    'Implementación de un contador privado y un módulo con estado usando closures.'),
  m(3, 'Objetos, prototipos y clases', 'Objetos y clases', 'Fundamentos', '2 h 30 min', '#e9b400',
    'JavaScript es prototipal por debajo de la sintaxis de clases. Aprende ambos modelos y cuándo usar cada uno.',
    ['Prototype chain y Object.create', 'class, extends y super', 'Getters/setters y propiedades computadas', 'Encapsulación con campos privados (#campo)', 'Object.freeze, Object.seal y destructuring anidado', 'Object.groupBy y Object.fromEntries'],
    [
      'Crea un objeto con Object.create(prototipo) y demuestra que hereda un método sin copiarlo',
      'Define una clase Animal con un método hablar() y una clase Perro extends Animal que sobreescribe hablar() llamando a super.hablar()',
      'Agrega un campo privado #saldo a una clase CuentaBancaria y expón un getter saldo y un método depositar() que lo valide',
      'Usa Object.getPrototypeOf() para recorrer la cadena de prototipos de una instancia y verificar que llega hasta Object.prototype',
      'Crea una propiedad computada en un objeto literal usando una variable como nombre de clave: { [clave]: valor }',
      'Compara: implementa el mismo "Animal/Perro" con funciones constructoras + prototype (estilo pre-ES6) y luego con class — identifica qué es exactamente igual por debajo',
    ],
    ['¿Qué es realmente la palabra clave class en JavaScript?', '¿Por qué los campos privados (#campo) son distintos de una convención como _campo?', '¿Cuándo Object.create es más apropiado que una clase?'],
    ['JavaScript'],
    'Jerarquía de clases con herencia y encapsulación real (campos privados).'),
  m(4, 'Arrays y estructuras de datos funcionales', 'Arrays funcionales', 'Fundamentos', '2 h', '#e9b400',
    'Transforma colecciones de datos sin loops manuales: map/filter/reduce como bloque base de la programación funcional.',
    ['map, filter, reduce, find, some/every', 'Set y Map vs Array y Object', 'Inmutabilidad y spread para actualizar datos', 'Estructuras anidadas y normalización', 'WeakMap y WeakSet para prevenir memory leaks', 'Métodos inmutables modernos: toSorted, toReversed, toSpliced, with'],
    [
      'Dado un array de 20 pedidos {cliente, monto}, usa reduce para calcular el total agrupado por cliente',
      'Usa filter + map encadenados para obtener los nombres de los clientes con monto > 100, en una sola expresión',
      'Crea un Set a partir de un array con duplicados y conviértelo de vuelta a array para eliminar duplicados',
      'Usa un Map en vez de un objeto plano para contar ocurrencias de palabras en un texto largo, y explica por qué Map es mejor aquí',
      'Actualiza un objeto anidado (usuario.direccion.ciudad) sin mutar el original, usando spread en cada nivel',
      'Implementa un pipeline: CSV en string → split → map a objetos → filter → reduce a un resumen JSON final',
    ],
    ['¿Cuándo reduce es la herramienta correcta y cuándo es exceso de ingeniería?', '¿Qué ventaja real tiene Map sobre un objeto para claves dinámicas?', '¿Por qué la inmutabilidad facilita encontrar bugs?'],
    ['JavaScript'],
    'Pipeline de transformación de datos (CSV→JSON agregado) usando solo métodos funcionales.'),
  m(5, 'Asincronía I: Event Loop y Promesas', 'Event Loop', 'Aplicación', '3 h', '#e9b400',
    'El modelo de concurrencia de JavaScript es single-threaded pero no bloqueante. Entiende microtasks vs macrotasks.',
    ['Event Loop, call stack y task queue', 'Microtasks (Promesas) vs macrotasks (setTimeout)', 'Promise.all/allSettled/race', 'De callbacks a promesas', 'El motor V8: compilación JIT (Ignition + TurboFan) y AST', 'Stack vs Heap y Garbage Collection (Mark and Sweep, generacional)', 'queueMicrotask() y Promise.any()'],
    [
      'Escribe un script con console.log, setTimeout(...,0) y Promise.resolve().then(...) mezclados — predice el orden de salida antes de ejecutarlo',
      'Convierte una función basada en callback (estilo Node clásico) a una que devuelve una Promise con new Promise((resolve, reject) => ...)',
      'Usa Promise.all para lanzar 3 fetch en paralelo y mide cuánto tarda comparado con hacerlos secuenciales con await',
      'Usa Promise.allSettled cuando una de las 3 promesas falla intencionalmente, y observa que las otras igual completan',
      'Implementa una carrera con Promise.race entre una petición real y un timeout de 2 segundos',
      'Dibuja (en texto o imagen) el diagrama de call stack → microtask queue → macrotask queue para un script con anidamiento de 2 niveles',
    ],
    ['¿Por qué una Promise resuelta se ejecuta antes que un setTimeout(fn, 0)?', '¿Qué diferencia hay entre Promise.all y Promise.allSettled?', '¿Qué significa que JavaScript sea "single-threaded pero no bloqueante"?'],
    ['JavaScript'],
    'Diagrama y demo ejecutable que predice el orden exacto de ejecución de un script asíncrono.'),
  m(6, 'Asincronía II: async/await y fetch', 'Async/await', 'Aplicación', '2 h 30 min', '#e9b400',
    'Escribe código asíncrono que se lee como código síncrono, con manejo de errores explícito.',
    ['async/await sobre promesas', 'try/catch en flujos asíncronos', 'fetch API y AbortController', 'Reintentos y timeouts manuales', 'Generadores: function*, yield y yield*', 'Proxies y Reflect: traps get/set/has'],
    [
      'Reescribe una cadena de .then().then().catch() como una función async con try/catch equivalente',
      'Consume una API pública (por ejemplo https://jsonplaceholder.typicode.com/users) con fetch y muestra los resultados en consola',
      'Maneja un fetch que falla (URL inválida) con try/catch y muestra un mensaje de error claro al usuario',
      'Implementa cancelación de una petición en curso con AbortController cuando el usuario dispara una nueva búsqueda',
      'Escribe una función fetchConReintentos(url, intentos) que reintente hasta 3 veces con backoff antes de fallar definitivamente',
      'Implementa un timeout manual de 5 segundos para un fetch usando Promise.race entre el fetch y un temporizador',
    ],
    ['¿Qué pasa internamente cuando usas await — se "bloquea" el hilo?', '¿Por qué necesitas try/catch alrededor de un await si la promesa puede rechazar?', '¿Para qué sirve exactamente AbortController?'],
    ['Fetch API'],
    'Cliente que consume una API pública con reintentos, timeout y cancelación.'),
  m(7, 'Módulos modernos y herramientas de build', 'Módulos y build', 'Aplicación', '2 h 30 min', '#e9b400',
    'Organiza código en módulos reales y entiende qué hace un bundler antes de usarlo a ciegas.',
    ['ESM (import/export) vs CommonJS (require)', 'Tree-shaking y code-splitting', 'Vite/esbuild: dev server y build de producción', 'package.json: exports, type, scripts', 'import() dinámico e import.meta', 'Webpack, Rollup y Babel/SWC: cuándo cada herramienta tiene sentido'],
    [
      'Crea 3 archivos ESM (math.mjs, format.mjs, main.mjs) con exports nombrados y un export default, e impórtalos entre sí',
      'Crea el mismo ejemplo con CommonJS (require/module.exports) y compara la sintaxis y el momento de resolución',
      'Inicializa un proyecto con npm create vite@latest y observa qué genera: estructura, package.json, vite.config',
      'Ejecuta npm run build y abre el bundle final — identifica minificación y hashing de nombres de archivo',
      'Importa una función de una librería grande (ej. lodash-es) usando solo el método que necesitas y verifica con el analizador de bundle que el resto no entra (tree-shaking)',
      'Configura un alias de import (@/utils) en vite.config y úsalo en vez de rutas relativas largas',
    ],
    ['¿Por qué ESM permite tree-shaking y CommonJS no (o mucho peor)?', '¿Qué hace exactamente un bundler que el navegador no hace solo?', '¿Cuándo te conviene importar todo un paquete vs solo una función?'],
    ['Vite', 'ESM'],
    'Proyecto multi-módulo construido con Vite con bundle final auditado.'),
  m(8, 'El DOM y eventos del navegador', 'DOM y eventos', 'Aplicación', '2 h 30 min', '#e9b400',
    'Antes de cualquier framework, entiende cómo JavaScript manipula la página real.',
    ['Selección y manipulación del DOM', 'Delegación de eventos', 'Formularios y validación nativa', 'Web APIs: localStorage, IntersectionObserver', 'ResizeObserver y MutationObserver', 'requestAnimationFrame y requestIdleCallback'],
    [
      'Crea una lista <ul> vacía y agrégale 20 <li> dinámicamente desde un array con createElement y appendChild',
      'En vez de agregar un listener a cada <li>, agrega uno solo al <ul> padre y usa event.target para delegación de eventos',
      'Construye un formulario con validación nativa (required, pattern) y muestra los mensajes de error con setCustomValidity',
      'Guarda el texto de un input en localStorage en cada cambio y recupéralo al recargar la página',
      'Implementa scroll infinito básico usando IntersectionObserver sobre un elemento "sentinela" al final de la lista',
      'Construye una lista filtrable: un input de búsqueda que oculta/muestra los <li> según coincidencia de texto, sin frameworks',
    ],
    ['¿Por qué la delegación de eventos es más eficiente que un listener por elemento?', '¿Qué diferencia hay entre localStorage y sessionStorage?', '¿Cuándo usarías IntersectionObserver en vez de escuchar el evento scroll?'],
    ['DOM API'],
    'Componente de UI interactivo (lista filtrable) sin frameworks, solo DOM API.'),
  m(9, 'Testing y calidad de código', 'Testing', 'Integración', '2 h 30 min', '#e9b400',
    'El código sin pruebas es un borrador. Aprende a escribir pruebas rápidas y confiables.',
    ['Unit testing con Vitest/Jest', 'Mocks, spies y fakes', 'ESLint y Prettier en el flujo de trabajo', 'Cobertura de código: qué medir y qué ignorar'],
    [
      'Instala Vitest en un proyecto y escribe el primer test: expect(sumar(2,3)).toBe(5)',
      'Escribe tests para debounce() del módulo 1 usando vi.useFakeTimers() para simular el paso del tiempo sin esperar de verdad',
      'Usa vi.fn() para crear un spy y verificar que una función callback fue llamada con los argumentos correctos',
      'Mockea fetch global con vi.spyOn para probar fetchConReintentos() del módulo 6 sin hacer peticiones reales',
      'Configura ESLint + Prettier en el proyecto y corrige todos los warnings que aparezcan en el código ya escrito',
      'Corre el reporte de cobertura (vitest --coverage) sobre la biblioteca del módulo 1 y identifica qué rama de código no está cubierta',
    ],
    ['¿Qué diferencia hay entre un mock, un spy y un fake?', '¿Por qué 100% de cobertura no garantiza ausencia de bugs?', '¿Qué prueba primero: el caso feliz o los casos límite?'],
    ['Vitest', 'ESLint'],
    'Suite de pruebas con cobertura >80% sobre la biblioteca de funciones del módulo 1.'),
  m(10, 'Patrones avanzados y rendimiento', 'Rendimiento', 'Integración', '3 h', '#e9b400',
    'Cuando el código funciona pero es lento: identifica el cuello de botella antes de optimizar a ciegas.',
    ['Debounce y throttle', 'Memoización', 'Web Workers para trabajo pesado', 'Profiling con DevTools Performance tab', 'Core Web Vitals: LCP, CLS, INP', 'preload, prefetch, preconnect y carga async/defer de scripts', 'Seguridad básica: XSS, CSRF, CSP y CORS'],
    [
      'Implementa throttle(fn, ms) (distinto de debounce) y demuestra la diferencia con un evento de scroll',
      'Escribe memoize(fn) genérico que cachee resultados por argumentos, y aplícalo a una función recursiva costosa (ej. fibonacci)',
      'Mide con console.time/console.timeEnd la diferencia de rendimiento de fibonacci con y sin memoización para n=35',
      'Mueve un cálculo pesado (ej. ordenar 1 millón de números) a un Web Worker y verifica que la UI principal no se congela',
      'Abre la pestaña Performance de DevTools, graba una interacción lenta de tu propia app y encuentra la función que más tiempo consume',
      'Optimiza esa función identificada y vuelve a grabar para confirmar la mejora con números reales',
    ],
    ['¿Cuál es la diferencia práctica entre debounce y throttle — cuándo usarías cada uno?', '¿Por qué memoizar una función recursiva sin memoria del cálculo puede ser contraproducente?', '¿Qué tipo de trabajo SÍ puede mover a un Web Worker y qué tipo no?'],
    ['Web Workers'],
    'Optimización medible (antes/después con métricas) de una función costosa.'),
  m(11, 'TypeScript esencial para devs de JavaScript', 'TypeScript', 'Experto', '3 h', '#e9b400',
    'El puente hacia Angular, React con tipos y Node tipado: aprende lo justo para ser productivo desde el día uno.',
    ['Tipos básicos, interfaces y type aliases', 'Generics', 'Narrowing y union types', 'tsconfig esencial y modo strict'],
    [
      'Convierte un archivo .js a .ts y corrige todos los errores que aparezcan con strict: true activado',
      'Define una interface Usuario y un type alias EstadoPedido = "pendiente" | "enviado" | "entregado", y úsalos en una función',
      'Escribe una función genérica primero<T>(lista: T[]): T | undefined que funcione para arrays de cualquier tipo',
      'Usa narrowing (typeof, instanceof, in) para manejar un parámetro de tipo string | number de forma segura',
      'Tipa la respuesta de un fetch con una interface y usa un type guard para validar la forma del JSON recibido en runtime',
      'Activa noImplicitAny y corrige cada any implícito que el compilador señale en el código del módulo 1',
    ],
    ['¿Qué pierdes realmente si usas any en vez de tipar correctamente?', '¿Cuándo usarías un type alias en vez de una interface?', '¿Por qué TypeScript no protege contra datos mal formados que vienen de una API en runtime?'],
    ['TypeScript'],
    'Migración de un módulo JavaScript existente a TypeScript estricto sin usar any.'),
  m(12, 'Proyecto integrador: SPA sin framework', 'Proyecto final', 'Experto', '6 h', '#e9b400',
    'Demuestra que entiendes los fundamentos construyendo una aplicación real sin la ayuda de Angular, React ni Vue.',
    ['Routing manual con History API', 'Estado de aplicación con un store propio', 'Consumo de una API real con manejo de errores', 'Build de producción optimizado'],
    [
      'Implementa un router manual con history.pushState y window.onpopstate para al menos 3 rutas (/inicio, /detalle/:id, /404)',
      'Construye un store propio (objeto + listeners) que notifique a la UI cuando el estado cambia, sin ninguna librería',
      'Conecta el store a fetch real (la misma API pública del módulo 6) con estados de carga, error y datos',
      'Renderiza las vistas actualizando el DOM manualmente según la ruta activa y el estado del store',
      'Agrega manejo de errores visible al usuario cuando una petición falla o una ruta no existe',
      'Genera el build de producción con Vite y verifica el tamaño final del bundle, documentando qué se podría optimizar más',
    ],
    ['¿Qué hace exactamente un framework como Angular/React que tú tuviste que construir a mano aquí?', '¿Qué fue lo más difícil de mantener sincronizados estado y DOM sin un framework?', '¿En qué punto del proyecto un framework te habría ahorrado más tiempo?'],
    ['JavaScript', 'Vite'],
    'SPA funcional (varias vistas, estado compartido, datos reales) sin ningún framework de UI.'),
  m(13, 'JavaScript en producción: seguridad, memoria y compatibilidad', 'Producción', 'Experto', '6 h', '#e9b400',
    'Convierte la SPA funcional en software operable: delimita datos no confiables, previene XSS y contaminación de prototipos, encuentra fugas de memoria, captura errores con contexto y entrega una experiencia compatible e internacionalizada.',
    [
      'Modelo de amenazas del navegador, XSS, CSP, Trusted Types y dependencias',
      'Garbage collection, retención, listeners, timers y análisis de heap',
      'Errores síncronos/asíncronos, Error.cause, telemetría y source maps',
      'Feature detection, progressive enhancement, Intl y zonas horarias',
    ],
    [
      'Explota y corrige una inserción insegura sin ocultar el problema con sanitización casera',
      'Provoca una fuga navegando repetidamente y demuestra su corrección con snapshots',
      'Diseña fronteras de error y correlaciona una falla minificada con su fuente original',
      'Internacionaliza números, moneda y fechas y prueba zonas horarias y capacidades ausentes',
    ],
    [
      '¿Por qué escapar HTML depende del contexto donde se inserta el dato?',
      '¿Cómo puede existir una fuga si JavaScript tiene garbage collector?',
      '¿Por qué una fecha sin zona horaria es un requisito incompleto?',
    ],
    ['JavaScript', 'DevTools', 'CSP', 'Intl', 'Vitest'],
    'SPA endurecida con threat model, CSP, render seguro, auditoría de dependencias, prueba de memoria, telemetría de errores, compatibilidad e internacionalización verificadas.'),
  m(14, 'JavaScript Master: TypeScript, WASM y cómputo emergente', 'JavaScript Master', 'Experto', '10 h', '#e9b400',
    'Amplía JavaScript con TypeScript avanzado, workers, bundlers, accesibilidad, WebAssembly, Web3 y ML responsable en navegador.',
    ['TypeScript avanzado', 'Web Workers y Service Workers', 'Vite, Rollup, webpack y esbuild', 'ARIA y navegación por teclado', 'WebAssembly con Rust/C', 'Web3 y TensorFlow.js/ONNX/WebNN'],
    ['Modela tipos condicionales', 'Mueve CPU a worker', 'Compara bundles', 'Audita teclado', 'Mide frontera WASM', 'Evalúa modelo local y amenaza Web3'],
    ['¿Cuándo WASM no mejora rendimiento?', '¿Qué riesgos introduce firmar una transacción desde la web?'], ['TypeScript','WebAssembly','Vite','ARIA','TensorFlow.js'], 'Aplicación web accesible con workers, bundle medido y laboratorios aislados WASM, Web3 y ML.'),
];
