import { CourseModule, createModule as m } from '../course-module.model';

export const KOTLIN_MULTIPLATFORM_MODULES: CourseModule[] = [
  m(0, 'Fundamentos de Kotlin', 'Fundamentos', 'Fundamentos', '2 h 30 min', '#7f52ff',
    'Kotlin es conciso y null-safe por diseño. Aprende la sintaxis que vas a reutilizar en Android, backend y multiplataforma.',
    ['val/var, null safety (?, !!, ?:)', 'data class y sintaxis concisa', 'Funciones de extensión', 'when como expresión'],
    [
      'Declara variables con val y var y explica cuándo el compilador te obliga a usar cada una',
      'Declara una variable nullable (String?) e intenta usarla sin verificar null — observa el error de compilación',
      'Usa el operador Elvis (?:) para dar un valor por defecto cuando una variable es null',
      'Crea una data class Persona y verifica que genera automáticamente equals, hashCode, toString y copy()',
      'Escribe una función de extensión String.esEmailValido() que agregue comportamiento a la clase String sin heredar de ella',
      'Reemplaza una cadena de if/else if por un when usado como expresión que devuelve un valor',
    ],
    ['¿Por qué Kotlin distingue entre String y String? en el sistema de tipos?', '¿Qué evita en la práctica el null safety de Kotlin que Java no evita por defecto?'],
    ['Kotlin'],
    'Programa de consola sin un solo NullPointerException posible (null safety real).'),
  m(1, 'Programación funcional en Kotlin', 'Funcional', 'Fundamentos', '2 h', '#7f52ff',
    'Kotlin trata las funciones como ciudadanos de primera clase, similar a JavaScript pero con tipado estático.',
    ['Lambdas y funciones de orden superior', 'Scope functions (let, run, apply, also)', 'Sealed classes para modelar estados', 'Colecciones: map/filter/fold idiomático'],
    [
      'Escribe una función de orden superior que reciba una lambda y la aplique a cada elemento de una lista',
      'Usa let para ejecutar código solo si una variable nullable no es null, sin un if explícito',
      'Usa apply para configurar un objeto recién creado y devolverlo en una sola expresión',
      'Modela un estado de UI (Cargando, Exito, Error) con una sealed class y maneja todos los casos con when exhaustivo',
      'Transforma una lista de objetos con map, filter y fold encadenados en una sola expresión',
    ],
    ['¿Qué diferencia práctica hay entre let, run, apply y also?', '¿Por qué when sobre una sealed class no necesita una rama else para ser exhaustivo?'],
    ['Kotlin'],
    'Modelo de estado (loading/success/error) con sealed classes manejado exhaustivamente.'),
  m(2, 'Coroutines y Flow', 'Coroutines', 'Aplicación', '3 h', '#7f52ff',
    'La concurrencia estructurada de Kotlin reemplaza callbacks y threads manuales en Android e iOS compartido.',
    ['suspend functions y CoroutineScope', 'Structured concurrency', 'Flow vs StateFlow vs SharedFlow', 'Manejo de errores en coroutines', 'Mutex para exclusión mutua en corrutinas', 'kotlinx.atomicfu para estado atómico multiplataforma'],
    [
      'Escribe una función suspend que simule una llamada de red con delay() y devuelva un resultado',
      'Lanza dos coroutines en paralelo con async/await y combina sus resultados',
      'Provoca un error dentro de una coroutine y captúralo con try/catch alrededor de la llamada suspend',
      'Crea un Flow que emita valores periódicamente y recolecta sus valores con collect',
      'Implementa un StateFlow para representar el estado actual de una pantalla, observado desde un componente de UI',
    ],
    ['¿Qué garantiza la "concurrencia estructurada" que un callback o thread manual no garantiza?', '¿Cuándo usarías StateFlow en vez de un Flow normal para representar estado de UI?'],
    ['Kotlin Coroutines'],
    'Función suspendida que combina dos fuentes de datos con manejo de errores estructurado.'),
  m(3, 'Arquitectura de un proyecto KMP', 'Arquitectura KMP', 'Aplicación', '2 h 30 min', '#7f52ff',
    'Entiende cómo un mismo código Kotlin termina ejecutándose en Android e iOS.',
    ['Source sets: commonMain, androidMain, iosMain', 'expect/actual: declarar e implementar por plataforma', 'Gradle multiplataforma', 'Targets disponibles (JVM, Native, JS)'],
    [
      'Crea un proyecto KMP desde la plantilla oficial y explora la estructura de carpetas (commonMain, androidMain, iosMain)',
      'Escribe una función en commonMain que dependa de una implementación específica por plataforma usando expect/actual',
      'Implementa esa función actual en androidMain y en iosMain con código distinto',
      'Compila el módulo compartido para el target Android y verifica el .aar generado',
      'Compila el módulo compartido para el target iOS y verifica el framework .framework generado',
    ],
    ['¿Qué resuelve expect/actual que una simple interfaz común no resolvería igual de bien?', '¿Por qué el código en commonMain no puede usar APIs específicas de Android o iOS directamente?'],
    ['Kotlin Multiplatform'],
    'Proyecto KMP con un módulo compartido que compila para Android e iOS.'),
  m(4, 'Lógica de negocio compartida', 'Lógica compartida', 'Integración', '3 h', '#7f52ff',
    'El valor real de KMP: escribe la lógica una vez, úsala en ambas plataformas nativas.',
    ['Modelos de dominio compartidos', 'Casos de uso (use cases) independientes de plataforma', 'Repositorios con interfaces comunes', 'Inyección de dependencias multiplataforma (Koin)'],
    [
      'Define modelos de dominio (data classes) en commonMain que representen las entidades centrales de tu app',
      'Implementa un caso de uso (ej. ObtenerTareasPendientesUseCase) que dependa de una interfaz de repositorio, no de su implementación concreta',
      'Define la interfaz del repositorio en commonMain y dos implementaciones (una real, una fake para tests)',
      'Configura Koin para inyectar la implementación correcta del repositorio en cada plataforma',
    ],
    ['¿Por qué definir el caso de uso contra una interfaz de repositorio (no una implementación) facilita testear la lógica?', '¿Qué porcentaje de una app típica suele ser lógica de negocio compartible vs UI específica de plataforma?'],
    ['Koin'],
    'Capa de dominio compartida (modelos + casos de uso) sin código específico de plataforma.'),
  m(5, 'Networking compartido con Ktor Client', 'Ktor Client', 'Integración', '2 h 30 min', '#7f52ff',
    'Consume APIs HTTP desde el código común, sin duplicar clientes por plataforma.',
    ['Ktor Client multiplataforma', 'Serialización con kotlinx.serialization', 'Manejo de errores de red', 'Interceptores y autenticación'],
    [
      'Configura un HttpClient de Ktor en commonMain con el plugin de serialización JSON',
      'Define un modelo @Serializable y consume un endpoint real, deserializando la respuesta automáticamente',
      'Maneja explícitamente errores de red (timeout, sin conexión) con un resultado tipado (sealed class Resultado)',
      'Agrega un interceptor que incluya un header de autenticación en cada request saliente',
    ],
    ['¿Qué evita tener que duplicar (URLSession en iOS, OkHttp en Android) al usar Ktor Client desde commonMain?', '¿Por qué modelar errores de red como un tipo de retorno explícito es mejor que dejar que las excepciones se propaguen sin control?'],
    ['Ktor'],
    'Cliente HTTP compartido que consume una API real desde Android e iOS.'),
  m(6, 'Persistencia compartida con SQLDelight', 'SQLDelight', 'Integración', '2 h 30 min', '#7f52ff',
    'Persiste datos localmente con SQL tipado y verificado en tiempo de compilación.',
    ['Esquemas SQLDelight y generación de código', 'Queries tipadas', 'Migraciones de base de datos', 'Drivers por plataforma'],
    [
      'Define un esquema .sq con una tabla Tarea y queries básicas (insertar, listar, actualizar)',
      'Genera el código Kotlin tipado a partir del esquema y úsalo desde commonMain',
      'Configura el driver de SQLDelight específico para Android y para iOS (expect/actual)',
      'Agrega una migración de esquema (.sqm) que añada una columna nueva sin perder datos existentes',
    ],
    ['¿Qué error detecta SQLDelight en tiempo de COMPILACIÓN que un ORM dinámico solo detectaría en runtime?', '¿Por qué necesitas un driver distinto por plataforma aunque las queries sean compartidas?'],
    ['SQLDelight'],
    'Capa de persistencia compartida con al menos una migración de esquema.'),
  m(7, 'Compose Multiplatform: UI compartida', 'Compose Multiplatform', 'Experto', '3 h', '#7f52ff',
    'Comparte no solo lógica sino también UI declarativa entre Android, iOS y desktop.',
    ['Compose Multiplatform vs Jetpack Compose', 'Theming compartido', 'Navegación multiplataforma', 'Limitaciones actuales en iOS', 'Compose Multiplatform para Desktop y Web, no solo móvil'],
    [
      'Crea una pantalla simple con Compose Multiplatform en commonMain (no androidMain)',
      'Ejecuta esa misma pantalla en un emulador Android y en un simulador iOS',
      'Define un theme compartido (colores, tipografía) usado por ambas plataformas',
      'Implementa navegación entre dos pantallas usando una librería de navegación compatible con KMP',
      'Documenta al menos una limitación real que encontraste al correr Compose Multiplatform en iOS comparado con Android',
    ],
    ['¿Qué gana un equipo al compartir UI (no solo lógica) entre Android e iOS, y qué riesgo asume?', '¿Por qué Compose Multiplatform en iOS es relativamente más nuevo/limitado que en Android?'],
    ['Compose Multiplatform'],
    'Pantalla compartida en Compose Multiplatform renderizada en Android e iOS.'),
  m(8, 'Interoperabilidad con iOS', 'Interop con iOS', 'Experto', '2 h 30 min', '#7f52ff',
    'Conecta el módulo Kotlin compartido con una app SwiftUI real.',
    ['Kotlin/Native y el framework generado para iOS', 'Mapeo de tipos Kotlin ↔ Swift', 'Manejo de coroutines desde Swift', 'CocoaPods vs Swift Package Manager para el framework KMP'],
    [
      'Genera el framework .framework de tu módulo compartido y agrégalo a un proyecto Xcode',
      'Llama a una función Kotlin desde código Swift y verifica el tipo resultante en Swift',
      'Llama a una función suspend de Kotlin desde Swift usando su callback/async equivalente generado',
      'Configura la distribución del framework con Swift Package Manager en vez de CocoaPods',
    ],
    ['¿Cómo se mapea una sealed class de Kotlin al lado de Swift?', '¿Qué cambia para Swift al llamar una función suspend de Kotlin comparado con una función normal?'],
    ['Kotlin/Native'],
    'App SwiftUI consumiendo el módulo compartido KMP a través del framework generado.'),
  m(9, 'Testing multiplataforma', 'Testing', 'Experto', '2 h', '#7f52ff',
    'Prueba la lógica compartida una sola vez y confía en que se comporta igual en ambas plataformas.',
    ['kotlin.test en código común', 'Fakes para dependencias de plataforma', 'Testing de coroutines (runTest)', 'Cobertura de la capa compartida'],
    [
      'Escribe un test con kotlin.test en commonTest que pruebe un caso de uso, sin depender de Android ni iOS',
      'Usa una implementación fake del repositorio (en vez de mockear) para aislar la prueba',
      'Testea una función suspend con runTest, controlando el tiempo virtual sin esperas reales',
      'Ejecuta la misma suite de tests apuntando al target Android y al target iOS, y confirma que ambos pasan',
    ],
    ['¿Por qué testear la capa común una sola vez te da confianza de que se comporta igual en ambas plataformas?', '¿Cuándo usarías un fake en vez de un mock para una dependencia de plataforma?'],
    ['kotlin.test'],
    'Suite de tests sobre el módulo common que corre igual en Android e iOS.'),
  m(10, 'CI/CD para KMP', 'CI/CD', 'Experto', '2 h 30 min', '#7f52ff',
    'Automatiza build y distribución de un proyecto que compila a múltiples plataformas.',
    ['Pipeline Gradle multiplataforma en CI', 'Distribución a TestFlight/Play Console', 'Fastlane para automatizar releases', 'Versionado compartido entre apps'],
    [
      'Configura un pipeline de CI que compile el módulo compartido para ambos targets (Android e iOS) en cada push',
      'Agrega la ejecución de los tests de commonTest como parte obligatoria del pipeline',
      'Configura Fastlane para automatizar el build y firma de la app Android',
      'Documenta cómo extenderías el pipeline para subir automáticamente a TestFlight (iOS) y a un track interno de Play Console (Android)',
    ],
    ['¿Por qué validar ambos targets en CI en cada push, y no solo antes de un release?', '¿Qué automatiza Fastlane que sería tedioso hacer manualmente en cada release?'],
    ['Fastlane'],
    'Pipeline CI que compila el módulo compartido para Android e iOS en cada push.'),
  m(11, 'Proyecto integrador: app KMP completa', 'Proyecto final', 'Experto', '7 h', '#7f52ff',
    'Une lógica, networking, persistencia y UI compartida en una app real para Android e iOS.',
    ['Arquitectura compartida por capas', 'Networking y persistencia comunes', 'UI nativa o Compose Multiplatform', 'CI que valida ambas plataformas'],
    [
      'Diseña la arquitectura compartida: dominio, casos de uso, repositorios con Ktor + SQLDelight',
      'Implementa la UI en Compose Multiplatform o nativa por plataforma (Jetpack Compose en Android, SwiftUI en iOS) consumiendo el módulo compartido',
      'Sincroniza datos remotos (Ktor) con caché local (SQLDelight) en el repositorio compartido',
      'Configura CI que compile y testee ambos targets en cada push',
    ],
    ['¿Qué porcentaje real de tu código terminó siendo compartido vs específico de plataforma?', '¿Qué decisión de arquitectura te ahorró más tiempo al final del proyecto?'],
    ['Kotlin Multiplatform', 'Ktor', 'SQLDelight'],
    'App con lógica de negocio, networking y persistencia compartidos, funcionando en Android e iOS.'),
];
