import { CourseModule, createModule as m } from '../course-module.model';

export const NODE_MODULES: CourseModule[] = [
  m(0, 'El runtime de Node: V8, libuv y el Event Loop', 'Runtime de Node', 'Fundamentos', '2 h', '#3c873a',
    'Node no es "JavaScript en el servidor" sin más: es un runtime con I/O no bloqueante construido sobre libuv.',
    ['Diferencias entre el Event Loop del navegador y el de Node', 'Fases del Event Loop (timers, poll, check)', 'process, global y módulos core', 'npx y la CLI de Node', 'Módulos core: os, buffer, crypto, util, child_process y cluster', 'Event-driven architecture y non-blocking I/O'],
    [
      'Crea un script y ejecútalo con node script.js — luego abre el REPL con node a secas y prueba comandos sueltos',
      'Escribe un script que mezcle console.log, setTimeout, setImmediate y process.nextTick y predice el orden antes de ejecutarlo',
      'Imprime process.version, process.platform y process.argv para entender qué expone el objeto process',
      'Usa process.env para leer una variable de entorno propia: PORT=4000 node script.js',
      'Compara la salida del ejemplo anterior corriéndolo dentro de un callback de fs.readFile vs en el nivel superior del script',
    ],
    ['¿Por qué setImmediate y setTimeout(fn, 0) no siempre se ejecutan en el mismo orden?', '¿Qué hace que Node pueda manejar miles de conexiones con un solo hilo?', '¿Qué diferencia hay entre el Event Loop del navegador y el de Node?'],
    ['Node.js'],
    'Script que demuestra el orden de ejecución entre setImmediate, setTimeout y process.nextTick.'),
  m(1, 'Módulos, npm/pnpm y gestión de dependencias', 'npm/pnpm', 'Fundamentos', '1 h 30 min', '#3c873a',
    'Gestiona dependencias de forma reproducible y entiende qué instala realmente cada comando.',
    ['package.json y semver', 'Lockfiles y instalación reproducible', 'Workspaces (monorepo) con npm/pnpm', 'Scripts de ciclo de vida (postinstall, etc.)'],
    [
      'Inicializa un proyecto con npm init -y y observa la estructura mínima de package.json generada',
      'Instala una dependencia con npm install y otra como devDependency con npm install -D — explica la diferencia en package.json',
      'Modifica manualmente una versión en package.json a un rango distinto (^, ~, exacta) y ejecuta npm install para ver el efecto',
      'Borra node_modules y reinstala con npm ci — compara el comportamiento con npm install respecto al lockfile',
      'Crea un monorepo mínimo con dos paquetes usando npm workspaces y enlaza uno como dependencia del otro',
      'Agrega un script "postinstall" a package.json que imprima un mensaje y verifica que corre automáticamente tras npm install',
    ],
    ['¿Qué problema real resuelve un lockfile (package-lock.json)?', '¿Por qué npm ci es más seguro que npm install en un pipeline de CI?', '¿Cuándo te conviene un monorepo con workspaces frente a paquetes separados?'],
    ['npm', 'pnpm'],
    'Monorepo con dos paquetes propios enlazados vía workspaces.'),
  m(2, 'Sistema de archivos y streams', 'FS y streams', 'Fundamentos', '2 h 30 min', '#3c873a',
    'Procesa archivos grandes sin cargarlos completos en memoria: el patrón que usa Node por dentro para todo.',
    ['fs/promises vs callbacks', 'Streams legibles, escribibles y transform', 'Backpressure', 'pipeline() para componer streams de forma segura'],
    [
      'Lee un archivo con fs.readFileSync, luego con fs/promises y luego con el callback clásico fs.readFile — compara las tres formas',
      'Genera un archivo CSV de 500k líneas con un script y mide cuánta memoria usa leerlo completo con readFileSync',
      'Lee el mismo archivo con un stream (fs.createReadStream) y procesa línea por línea sin cargarlo completo en memoria',
      'Escribe un Transform stream que convierta cada línea CSV a un objeto JSON',
      'Compón los tres streams (lectura → transform → escritura) usando stream/promises pipeline y maneja errores correctamente',
      'Provoca backpressure intencionalmente (escritura mucho más lenta que lectura) y observa cómo el stream se autorregula',
    ],
    ['¿Por qué cargar un archivo completo en memoria no escala para archivos grandes?', '¿Qué es backpressure y por qué pipeline() lo maneja mejor que pipe() encadenado a mano?', '¿Cuándo usarías fs/promises en vez de streams?'],
    ['Node.js streams'],
    'Script que transforma un archivo CSV grande a JSON usando streams, sin cargarlo completo en RAM.'),
  m(3, 'Servidores HTTP nativos', 'HTTP nativo', 'Aplicación', '2 h', '#3c873a',
    'Antes de Express, entiende qué hace un framework por debajo construyendo un servidor con el módulo http puro.',
    ['Modelo request/response', 'Routing manual', 'Parsing de body y headers', 'Códigos de estado y content negotiation'],
    [
      'Crea un servidor con node:http que responda "Hola Node" en GET / y arráncalo con node servidor.js',
      'Agrega routing manual: GET /tareas devuelve un array JSON, POST /tareas agrega un elemento al array en memoria',
      'Parsea el body de un POST acumulando chunks del stream request y haciendo JSON.parse al final',
      'Responde con los códigos de estado correctos: 201 al crear, 404 para rutas no encontradas, 400 para JSON inválido',
      'Lee el header Accept y responde JSON o texto plano según lo que el cliente pida (content negotiation básica)',
      'Prueba el servidor con curl -X POST -d \'{"titulo":"Tarea 1"}\' -H "Content-Type: application/json" localhost:3000/tareas',
    ],
    ['¿Qué hace exactamente Express que tú tuviste que escribir a mano aquí?', '¿Por qué el body de un POST llega como stream y no como objeto ya parseado?', '¿Qué decide el código de estado HTTP correcto para cada situación?'],
    ['Node.js http'],
    'Servidor HTTP nativo con 3 rutas y manejo de errores, sin frameworks.'),
  m(4, 'Express/Fastify: routing y middleware', 'Express/Fastify', 'Aplicación', '3 h', '#3c873a',
    'El patrón middleware es la base de casi todos los frameworks web de Node.',
    ['Middleware: orden de ejecución y next()', 'Routers anidados', 'Manejo centralizado de errores', 'Validación de entrada (zod/joi)', 'express-validator como alternativa', 'Diferencias clave Express vs Fastify: hooks y JSON Schema nativo'],
    [
      'Crea una API Express con GET /tareas y POST /tareas, usando express.json() como middleware',
      'Escribe un middleware de logging propio que imprima método, ruta y tiempo de respuesta de cada request',
      'Organiza las rutas de tareas en un express.Router() separado y móntalo con app.use("/tareas", router)',
      'Agrega validación de entrada con zod: si el body no cumple el schema, responde 400 con los errores específicos',
      'Implementa un middleware de manejo de errores centralizado (4 parámetros) que capture errores de cualquier ruta',
      'Repite el ejercicio con Fastify y compara: rendimiento, ergonomía de schemas, y cómo declara middleware',
    ],
    ['¿Por qué el orden en que declaras middleware en Express importa tanto?', '¿Qué pasa si olvidas llamar next() dentro de un middleware?', '¿Qué ventaja real ofrece validar con zod en vez de revisar el body a mano?'],
    ['Express', 'Fastify'],
    'API REST con middleware de logging, validación y manejo de errores centralizado.'),
  m(5, 'Bases de datos: drivers y ORMs', 'Bases de datos', 'Aplicación', '3 h', '#3c873a',
    'Conecta tu API a una base real y aprende cuándo un ORM ayuda y cuándo estorba.',
    ['PostgreSQL/MongoDB desde Node', 'Prisma: schema, migraciones y queries tipadas', 'Pool de conexiones', 'Transacciones', 'Mongoose: Schemas, Models y population', 'Sequelize y TypeORM como alternativas a Prisma'],
    [
      'Levanta PostgreSQL en Docker y conéctate con el driver pg puro ejecutando un SELECT 1',
      'Instala Prisma, define un modelo Tarea en schema.prisma y corre prisma migrate dev para crear la tabla',
      'Usa el cliente generado por Prisma para crear, listar y actualizar tareas desde tu API Express',
      'Provoca intencionalmente una condición de carrera (dos requests que descuentan stock al mismo tiempo) sin transacción, y luego corrígela con prisma.$transaction',
      'Configura un pool de conexiones y observa en logs cuántas conexiones simultáneas abre la app bajo carga',
      'Compara la misma consulta (tareas con su usuario) escrita con SQL crudo, con el driver pg, y con Prisma',
    ],
    ['¿Cuándo un ORM como Prisma te ahorra tiempo y cuándo te estorba?', '¿Por qué necesitas un pool de conexiones en vez de abrir una conexión por request?', '¿Qué problema resuelve una transacción que un query individual no resuelve?'],
    ['Prisma', 'PostgreSQL'],
    'API con persistencia real en PostgreSQL usando Prisma y migraciones versionadas.'),
  m(6, 'Autenticación y autorización', 'Auth', 'Integración', '2 h 30 min', '#3c873a',
    'Implementa login seguro sin reinventar criptografía desde cero.',
    ['Hashing de contraseñas (bcrypt/argon2)', 'JWT: access y refresh tokens', 'Sesiones vs tokens', 'OAuth 2.0 con un proveedor externo', 'Passport.js y sus estrategias de autenticación', 'Cookies seguras, sesiones y protección CSRF'],
    [
      'Implementa registro de usuario con contraseña hasheada usando bcrypt — nunca guardes contraseñas en texto plano',
      'Implementa login que verifica la contraseña con bcrypt.compare y devuelve un access token JWT de corta duración',
      'Agrega un refresh token de larga duración guardado de forma segura, y un endpoint /refresh que emite un nuevo access token',
      'Crea un middleware de autenticación que valide el JWT del header Authorization y rechace con 401 si es inválido',
      'Agrega control de roles: un middleware que solo permita acceder a una ruta si el usuario tiene rol "admin"',
      'Investiga y documenta (sin implementar completo) cómo sería integrar login con Google usando OAuth 2.0',
    ],
    ['¿Por qué nunca debes guardar contraseñas en texto plano, ni siquiera cifradas (en vez de hasheadas)?', '¿Qué diferencia hay entre un access token y un refresh token?', '¿Por qué NO deberías construir tu propio algoritmo de hashing de contraseñas?'],
    ['JWT', 'OAuth2'],
    'API protegida con JWT, refresh tokens y rutas con control de roles.'),
  m(7, 'Testing e integración continua', 'Testing', 'Integración', '2 h 30 min', '#3c873a',
    'Prueba endpoints HTTP reales, no solo funciones aisladas.',
    ['Vitest + Supertest', 'Bases de datos de prueba (Testcontainers)', 'Mocks de servicios externos', 'Pipeline de CI para una API Node', 'Jest, Mocha, Chai y Sinon como alternativas', 'Debugging con --inspect y Chrome DevTools'],
    [
      'Escribe un test con Supertest que haga un GET /tareas real contra tu app Express y verifique el código de estado y el body',
      'Escribe un test que haga POST /tareas con un body inválido y verifique que responde 400 con el mensaje de error esperado',
      'Configura Testcontainers para levantar un PostgreSQL real y efímero solo durante los tests',
      'Escribe un test de integración completo: crea una tarea, la consulta, la actualiza y verifica el estado final en la base real',
      'Mockea una llamada a un servicio externo (ej. un proveedor de email) para que los tests no dependan de internet',
      'Crea un pipeline de CI (GitHub Actions) que instale dependencias, levante la base de prueba y corra los tests en cada push',
    ],
    ['¿Por qué un test de integración con base real da más confianza que uno con mocks de la base?', '¿Qué ventaja tiene Testcontainers sobre apuntar a una base de datos compartida de "test"?', '¿Qué deberías mockear siempre en un test, sin excepción?'],
    ['Vitest', 'Supertest'],
    'Suite de pruebas de integración que levanta la API contra una base de datos real en Docker.'),
  m(8, 'Patrones asíncronos avanzados', 'Async avanzado', 'Experto', '3 h', '#3c873a',
    'Cuando una sola instancia de Node no alcanza: workers, clustering y colas de trabajo.',
    ['Worker threads para CPU-bound', 'Cluster module y balanceo entre procesos', 'Colas de trabajo con BullMQ + Redis', 'Procesamiento en background', 'pm2 en modo cluster y --max-old-space-size', 'Heap snapshots y detección de memory leaks', 'Redis: cache-aside, idempotencia y Pub/Sub'],
    [
      'Identifica una tarea CPU-bound (ej. procesar una imagen grande) y muévela a un worker_thread para no bloquear el event loop principal',
      'Usa el módulo cluster para levantar un proceso por núcleo de CPU y balancear requests entre ellos',
      'Levanta Redis en Docker y configura una cola con BullMQ',
      'Encola un job de "enviar email" en vez de procesarlo en el request, y procésalo desde un worker separado',
      'Configura reintentos automáticos con backoff exponencial para jobs que fallan en la cola',
      'Mide la diferencia de latencia del endpoint que encola el job vs el que procesaba todo de forma síncrona',
    ],
    ['¿Cuándo un worker_thread es la herramienta correcta y cuándo es una cola de trabajo?', '¿Qué gana tu API al mover trabajo pesado fuera del request-response?', '¿Por qué cluster no comparte memoria entre procesos como sí lo hace un worker_thread?'],
    ['BullMQ', 'Redis'],
    'Cola de procesamiento en background (envío de emails) con reintentos y backoff.'),
  m(9, 'Observabilidad y manejo de errores en producción', 'Observabilidad', 'Experto', '2 h 30 min', '#3c873a',
    'Diagnostica un proceso Node en producción sin adivinar.',
    ['Logging estructurado (pino/winston)', 'Correlation ID por request', 'Manejo de excepciones no capturadas', 'Health checks y graceful shutdown', 'process.on("unhandledRejection") y manejo de promesas sin catch', 'Diseño de APIs: REST vs GraphQL (Apollo Server) vs gRPC', 'Métricas Prometheus y trazas distribuidas con OpenTelemetry'],
    [
      'Reemplaza console.log por pino y configura logs en formato JSON estructurado',
      'Agrega un middleware que genere un correlation ID (uuid) por request y lo incluya en todos los logs de esa request',
      'Provoca una excepción no capturada intencionalmente y configura un handler global (process.on("uncaughtException")) que la registre antes de cerrar el proceso',
      'Implementa un endpoint /health que verifique la conexión a la base de datos antes de responder 200',
      'Implementa graceful shutdown: al recibir SIGTERM, deja de aceptar nuevas conexiones, termina las en curso y luego cierra el proceso',
      'Simula una caída abrupta sin graceful shutdown y compara qué pasa con requests en curso',
    ],
    ['¿Por qué el correlation ID es esencial para diagnosticar un error en producción?', '¿Qué diferencia hay entre un error capturado y uno no capturado, en términos de qué debes hacer?', '¿Por qué importa el apagado ordenado (graceful shutdown) en un sistema con tráfico real?'],
    ['Pino'],
    'API con logging estructurado, correlation ID y apagado controlado (graceful shutdown).'),
  m(10, 'Seguridad en Node', 'Seguridad', 'Experto', '2 h', '#3c873a',
    'Los errores de seguridad más comunes en APIs Node y cómo evitarlos sistemáticamente.',
    ['OWASP API Security Top 10', 'helmet y cabeceras seguras', 'Rate limiting', 'Validación y sanitización de entrada'],
    [
      'Instala helmet en tu API Express y verifica con curl -I qué cabeceras de seguridad agrega',
      'Implementa rate limiting (ej. express-rate-limit) y prueba que tras N requests en poco tiempo, la API responde 429',
      'Provoca una inyección SQL intencional en un endpoint que concatena strings directamente, y luego corrígela con queries parametrizadas',
      'Valida y sanitiza un campo de texto libre que se va a renderizar luego en HTML, para prevenir XSS almacenado',
      'Revisa los 3 ítems más relevantes del OWASP API Security Top 10 para tu API y documenta cómo los mitigas',
      'Audita tus dependencias con npm audit y corrige las vulnerabilidades críticas encontradas',
    ],
    ['¿Por qué concatenar strings para construir SQL es peligroso incluso si "nunca vas a tener atacantes"?', '¿Qué problema real resuelve el rate limiting más allá de "verse profesional"?', '¿Qué cabeceras agrega helmet y por qué cada una importa?'],
    ['Helmet'],
    'API con rate limiting, cabeceras seguras y validación estricta de entrada.'),
  m(11, 'Despliegue y contenedores', 'Despliegue', 'Experto', '2 h', '#3c873a',
    'Empaqueta y despliega tu API Node de forma reproducible (conecta directo con el track DevOps).',
    ['Dockerfile para Node (multi-stage)', 'Variables de entorno por ambiente', 'PM2 vs contenedores para gestión de procesos', 'Zero-downtime deploys', 'Nginx como reverse proxy y balanceador', 'Serverless: AWS Lambda, Vercel y Azure Functions'],
    [
      'Escribe un Dockerfile multi-stage: una etapa de build (npm install + build) y una etapa final solo con node_modules de producción',
      'Construye la imagen y compara su tamaño con una versión de una sola etapa sin optimizar',
      'Configura variables de entorno distintas para development y production usando un archivo .env por ambiente',
      'Levanta el contenedor con docker run y verifica con docker logs que arranca correctamente',
      'Configura un healthcheck en el Dockerfile (HEALTHCHECK) que Docker use para saber si el contenedor está sano',
      'Documenta cómo harías un despliegue sin downtime (rolling update) con al menos dos instancias detrás de un balanceador',
    ],
    ['¿Por qué una imagen Docker multi-stage es más segura y liviana que una de una sola etapa?', '¿Qué ventaja da un healthcheck a nivel de Docker/Kubernetes?', '¿Qué necesitas para lograr un despliegue sin downtime?'],
    ['Docker'],
    'Imagen Docker de producción de la API, optimizada y sin dependencias de desarrollo.'),
  m(12, 'Proyecto integrador: API productiva', 'Proyecto final', 'Experto', '6 h', '#3c873a',
    'Une todo lo aprendido en una API lista para producción real.',
    ['Arquitectura por capas', 'Autenticación, persistencia y testing integrados', 'Observabilidad básica', 'Contenedor listo para desplegar', 'Qué sigue: microservicios, message queues (Kafka/RabbitMQ) y TypeScript con ts-node/tsx'],
    [
      'Diseña la arquitectura por capas: rutas → controladores → servicios → repositorio de datos, sin mezclar responsabilidades',
      'Implementa autenticación JWT completa (login, refresh, rutas protegidas) integrada con tu base de datos real',
      'Agrega persistencia con Prisma/PostgreSQL incluyendo al menos una relación uno-a-muchos',
      'Escribe tests de integración (Supertest + Testcontainers) que cubran el flujo crítico de principio a fin',
      'Agrega logging estructurado con correlation ID y un endpoint /health',
      'Construye el Dockerfile de producción multi-stage y documenta cómo desplegarías esta API a un proveedor real',
    ],
    ['¿Qué decisiones de arquitectura tomaste y por qué, en vez de copiar un boilerplate?', '¿Qué parte del proyecto te hizo reconsiderar una decisión de diseño anterior?', '¿Qué le falta a esta API para considerarla lista para tráfico real de producción?'],
    ['Express', 'Prisma', 'Docker'],
    'API REST con auth, base de datos real, tests de integración y Dockerfile de producción.'),
  m(13, 'TypeScript, contratos e integraciones confiables', 'Contratos y resiliencia', 'Experto', '7 h', '#3c873a',
    'Evoluciona la API productiva hacia un servicio con tipos estrictos, contratos HTTP verificables y efectos seguros frente a reintentos, caídas y entregas duplicadas.',
    [
      'TypeScript strict, tipos de dominio, Result y fronteras de datos',
      'OpenAPI, compatibilidad, versionado y contract testing',
      'OpenAPI como contrato ejecutable y documentación verificable',
      'Idempotency keys, concurrencia, transactional outbox y consumers',
      'Webhooks firmados, reintentos, deduplicación y reconciliación',
    ],
    [
      'Migra una vertical completa a TypeScript estricto sin any ni casts que oculten validación',
      'Genera y verifica OpenAPI contra requests y responses reales en CI',
      'Demuestra que un comando repetido o concurrente produce un único efecto',
      'Entrega webhooks firmados con outbox y recupera fallos mediante reconciliación',
    ],
    [
      '¿Por qué un tipo TypeScript no valida JSON recibido por red?',
      '¿Qué cambio compatible puede romper semánticamente a un consumidor?',
      '¿Por qué exactamente una vez se diseña como efecto y no como promesa del broker?',
    ],
    ['TypeScript', 'OpenAPI', 'Zod', 'PostgreSQL', 'Vitest'],
    'API tipada y contract-first con idempotencia transaccional, outbox, webhooks firmados, pruebas de duplicación y procedimiento de reconciliación.'),
  m(14, 'Node.js Master: GraphQL, eventos y entrega', 'Node Master', 'Experto', '10 h', '#3c873a',
    'Entrega servicios Node tipados en serverless y contenedores, con GraphQL federado, eventos, sagas y CI/CD verificable.',
    ['TypeScript nativo, tsx y configuración', 'GraphQL, DataLoader, directives y Federation', 'Kafka/RabbitMQ, SAGA y event-driven', 'AWS Lambda/Azure Functions/GCP Functions', 'Docker multi-stage, Alpine y PM2', 'GitHub Actions/Jenkins y despliegue'],
    ['Valida tipos en runtime', 'Evita N+1', 'Orquesta una saga', 'Mide cold start', 'Endurece imagen', 'Promueve artefacto inmutable'],
    ['¿Por qué Federation no resuelve límites de dominio?', '¿Cuándo PM2 sobra dentro de Kubernetes?'], ['TypeScript','Apollo Federation','Kafka','AWS Lambda','Docker','GitHub Actions'], 'Servicio Node federado y event-driven desplegado mediante pipeline con fallos probados.'),
];
