import { CourseModule, createModule as m } from '../course-module.model';

export const REACT_MODULES: CourseModule[] = [
  m(0, 'JSX, componentes y props', 'JSX y componentes', 'Fundamentos', '2 h', '#149eca',
    'React describe la UI como una función del estado. JSX es solo azúcar sintáctica sobre createElement.',
    ['JSX: expresiones embebidas y listas con key', 'Componentes de función y props', 'Composición vs herencia', 'Renderizado condicional', 'Fragments (<> </>) y children', 'Estilos: CSS Modules, Styled Components y Tailwind'],
    [
      'Crea un componente Boton que reciba texto y onClick como props y renderícenlo en App',
      'Renderiza una lista de 5 elementos con .map() y asigna una key estable (id, no el índice)',
      'Crea un componente Tarjeta que reciba children y los renderice envueltos en un contenedor con estilo',
      'Implementa renderizado condicional con && y con un operador ternario, y explica cuándo usar cada uno',
      'Compón 3 componentes pequeños (Avatar, Nombre, Tarjeta) dentro de un componente Usuario sin usar herencia',
    ],
    ['¿Por qué usar el índice del array como key puede causar bugs sutiles?', '¿Qué transforma JSX realmente por debajo (createElement)?'],
    ['React'],
    'Set de componentes de presentación reutilizables (botón, tarjeta, lista).'),
  m(1, 'Estado local y el ciclo de render', 'Estado y render', 'Fundamentos', '2 h 30 min', '#149eca',
    'Entiende cuándo y por qué React vuelve a renderizar un componente.',
    ['useState y actualizaciones funcionales', 'Render vs commit', 'Batching de actualizaciones', 'Listas controladas vs no controladas'],
    [
      'Crea un contador con useState y demuestra el bug de usar setCount(count + 1) tres veces seguidas vs la forma funcional setCount(c => c + 1)',
      'Construye un input controlado (value + onChange) y muestra el valor en tiempo real en otro lugar de la pantalla',
      'Agrega 3 setState seguidos en un mismo manejador de evento y confirma con console.log que React los agrupa (batching) en un solo render',
      'Implementa un formulario simple con 3 campos controlados y validación que se actualiza en cada tecla',
    ],
    ['¿Por qué setCount(count + 1) repetido tres veces no triplica el valor?', '¿Qué diferencia hay entre la fase de render y la fase de commit?'],
    ['React'],
    'Formulario controlado con validación en tiempo real basada en useState.'),
  m(2, 'Hooks esenciales', 'Hooks', 'Fundamentos', '3 h', '#149eca',
    'Los hooks son el mecanismo para "engancharse" al ciclo de vida y memoria de un componente de función.',
    ['useEffect: dependencias y limpieza', 'useRef para valores mutables sin re-render', 'useMemo y useCallback: cuándo realmente ayudan', 'Reglas de los hooks', 'useReducer: reducers, dispatch y action types', 'useImperativeHandle y forwardRef'],
    [
      'Crea un useEffect que se suscriba a un evento de window (resize) y verifica que se limpia correctamente al desmontar el componente',
      'Usa useRef para guardar el valor anterior de una prop sin causar un re-render adicional',
      'Mide con console.log cuántas veces se recalcula una función costosa sin useMemo, y luego confirma que useMemo evita recálculos innecesarios',
      'Envuelve un callback pasado a un hijo memoizado (React.memo) con useCallback y demuestra que evita un re-render innecesario del hijo',
      'Provoca intencionalmente una violación de las reglas de los hooks (un hook dentro de un if) y lee el error que React muestra',
    ],
    ['¿Por qué un useEffect sin array de dependencias se ejecuta en cada render?', '¿Cuándo useMemo/useCallback realmente mejoran el rendimiento y cuándo son ruido innecesario?'],
    ['React Hooks'],
    'Componente con un efecto de suscripción externa correctamente limpiado al desmontar.'),
  m(3, 'Formularios y eventos', 'Formularios', 'Aplicación', '2 h', '#149eca',
    'Maneja entradas de usuario complejas sin perder el control del estado.',
    ['Componentes controlados', 'Validación con bibliotecas (React Hook Form)', 'Manejo de eventos sintéticos', 'Formularios multi-paso'],
    [
      'Construye un formulario de registro con React Hook Form (register, handleSubmit, errors)',
      'Agrega validación con un schema de zod conectado a React Hook Form (resolver)',
      'Implementa un formulario multi-paso que conserve los datos de pasos anteriores al avanzar y retroceder',
      'Maneja un evento de submit previniendo el comportamiento por defecto del navegador (preventDefault)',
    ],
    ['¿Qué problema de rendimiento resuelve React Hook Form frente a manejar cada campo con useState individual?', '¿Por qué los eventos en React son "sintéticos" y no los eventos nativos del DOM?'],
    ['React Hook Form'],
    'Formulario multi-paso con validación y persistencia de datos entre pasos.'),
  m(4, 'Context API y composición', 'Context', 'Aplicación', '2 h', '#149eca',
    'Comparte estado entre componentes lejanos sin pasar props manualmente en cada nivel.',
    ['createContext y useContext', 'Cuándo Context es suficiente y cuándo no', 'Patrón de componentes compuestos', 'Render props vs hooks personalizados'],
    [
      'Crea un ThemeContext con valores "claro"/"oscuro" y un ThemeProvider que envuelva la app',
      'Consume el contexto desde un componente anidado 3 niveles abajo sin pasar props intermedias (sin prop drilling)',
      'Implementa un toggle que cambie el tema y verifica que todos los consumidores se actualizan',
      'Construye un componente compuesto (ej. Tabs/Tab) que comparta estado interno vía Context entre Tabs y sus Tab hijos',
    ],
    ['¿Por qué Context no es un reemplazo completo de un gestor de estado global como Redux?', '¿Cuándo el prop drilling es aceptable y cuándo es momento de usar Context?'],
    ['React Context'],
    'Theme switcher (claro/oscuro) implementado con Context, sin prop drilling.'),
  m(5, 'React Router: navegación', 'React Router', 'Aplicación', '2 h 30 min', '#149eca',
    'Estructura una SPA con múltiples vistas, rutas anidadas y carga perezosa.',
    ['Rutas anidadas y layouts compartidos', 'Loaders y acciones de datos', 'Rutas protegidas', 'Code-splitting por ruta'],
    [
      'Define rutas anidadas: un layout compartido (con navbar) que envuelva /tareas y /tareas/:id',
      'Usa un loader de React Router para cargar datos antes de renderizar una ruta',
      'Implementa una ruta protegida que redirija a /login si no hay sesión activa',
      'Carga una ruta pesada con React.lazy + Suspense y verifica en Network que el chunk se descarga solo al navegar ahí',
    ],
    ['¿Qué ventaja da un loader de ruta frente a hacer fetch dentro de un useEffect del componente?', '¿Por qué el code-splitting por ruta mejora el tiempo de carga inicial?'],
    ['React Router'],
    'Aplicación con rutas anidadas, una ruta protegida y carga perezosa de al menos una vista.'),
  m(6, 'Data fetching moderno', 'Data fetching', 'Integración', '3 h', '#149eca',
    'Deja de manejar loading/error a mano: usa una capa de datos pensada para eso.',
    ['TanStack Query: queries y mutations', 'Cache, invalidación y refetch', 'Estados de carga, error y datos obsoletos', 'Optimistic updates'],
    [
      'Reemplaza un useEffect + useState manual de fetching por useQuery de TanStack Query',
      'Observa en React Query Devtools cómo se cachea la respuesta y cuándo se vuelve "obsoleta" (stale)',
      'Implementa una mutación (useMutation) para crear un nuevo elemento, e invalida la query de la lista al completarse',
      'Implementa un optimistic update: actualiza la UI antes de que el servidor confirme, y revierte si la petición falla',
    ],
    ['¿Qué problemas de "loading hell" resuelve TanStack Query frente a manejar todo con useState/useEffect?', '¿Qué riesgo tiene un optimistic update y cómo lo mitigas?'],
    ['TanStack Query'],
    'Lista de datos con fetching, cache y mutaciones optimistas usando TanStack Query.'),
  m(7, 'Gestión de estado global', 'Estado global', 'Integración', '2 h 30 min', '#149eca',
    'Cuando el estado ya no cabe en un componente ni en Context, elige una herramienta dedicada.',
    ['Zustand: stores mínimos sin boilerplate', 'Redux Toolkit: slices y RTK Query', 'Cuándo NO necesitas una librería de estado global', 'Estado del servidor vs estado de cliente', 'Jotai (atoms) y Recoil (selectors) como alternativas atómicas', 'XState para máquinas de estado complejas'],
    [
      'Crea un store de Zustand para un carrito de compras (items, agregar, quitar, total)',
      'Consume el store de Zustand desde dos componentes no relacionados directamente',
      'Implementa el mismo carrito con Redux Toolkit (createSlice) y compara la cantidad de código',
      'Identifica en tu propio proyecto qué estado es "del servidor" (cacheable con TanStack Query) y cuál es "de cliente" (UI local, mejor en Zustand/Context)',
    ],
    ['¿Por qué mezclar estado del servidor con estado de cliente en el mismo store suele ser un error?', '¿Cuándo NO necesitas ninguna librería de estado global?'],
    ['Zustand', 'Redux Toolkit'],
    'Store global propio (carrito de compras o similar) con Zustand.'),
  m(8, 'Testing en React', 'Testing', 'Integración', '2 h 30 min', '#149eca',
    'Prueba componentes desde la perspectiva del usuario, no de la implementación.',
    ['React Testing Library: queries por rol/texto', 'Mocking de requests HTTP (MSW)', 'Testing de hooks personalizados', 'Vitest como runner'],
    [
      'Escribe un test con React Testing Library que renderice un componente y lo consulte por getByRole, no por clase CSS',
      'Simula un click de usuario con userEvent y verifica el resultado visible en pantalla',
      'Configura Mock Service Worker (MSW) para interceptar una llamada fetch en los tests sin red real',
      'Escribe un test de un flujo completo: llenar un formulario, enviarlo, y verificar el mensaje de éxito tras la respuesta mockeada',
      'Testea un hook personalizado con renderHook de Testing Library',
    ],
    ['¿Por qué Testing Library evita deliberadamente queries por clase CSS o estructura del DOM?', '¿Qué ventaja da MSW sobre mockear fetch directamente con vi.fn()?'],
    ['React Testing Library', 'Vitest'],
    'Suite de pruebas de un flujo completo (formulario + fetching) con MSW.'),
  m(9, 'Performance en React', 'Performance', 'Experto', '2 h 30 min', '#149eca',
    'Identifica y corrige renders innecesarios antes de optimizar a ciegas.',
    ['React DevTools Profiler', 'memo, useMemo y useCallback con criterio', 'Code-splitting con lazy/Suspense', 'Virtualización de listas largas', 'useTransition, useDeferredValue y startTransition', 'Fiber architecture y Reconciliation (algoritmo de diff)'],
    [
      'Graba una interacción con React DevTools Profiler y encuentra qué componente se re-renderiza sin necesidad',
      'Envuelve ese componente con React.memo y confirma con el Profiler que el render innecesario desaparece',
      'Implementa virtualización (ej. con react-window) sobre una lista de 10,000 elementos y compara el rendimiento de scroll',
      'Divide un bundle grande con React.lazy en al menos 2 chunks y verifica la mejora en el tiempo de carga inicial',
    ],
    ['¿Por qué optimizar sin medir primero con el Profiler suele ser tiempo perdido?', '¿Cuándo virtualizar una lista es necesario y cuándo es over-engineering?'],
    ['React DevTools'],
    'Optimización medible (antes/después con el Profiler) de una vista con listas largas.'),
  m(10, 'Server Components y Next.js', 'Next.js', 'Experto', '3 h', '#149eca',
    'El ecosistema React se mueve hacia renderizado en servidor por defecto.',
    ['Server Components vs Client Components', 'App Router de Next.js', 'Streaming y Suspense en el servidor', 'Server Actions'],
    [
      'Crea un proyecto Next.js con App Router y observa que los componentes son Server Components por defecto',
      'Marca un componente interactivo con "use client" y explica por qué lo necesita',
      'Implementa streaming de una sección lenta de la página con Suspense en el servidor',
      'Implementa una Server Action que procese un formulario sin necesidad de un endpoint API separado',
    ],
    ['¿Qué ventaja tiene un Server Component que nunca envía su JavaScript al navegador?', '¿Cuándo es obligatorio marcar un componente como "use client"?'],
    ['Next.js'],
    'Aplicación Next.js con App Router, Server Components y al menos una Server Action.'),
  m(11, 'TypeScript con React', 'TypeScript + React', 'Experto', '2 h', '#149eca',
    'Tipa props, estado y hooks personalizados para detectar errores antes de ejecutar.',
    ['Tipado de props y children', 'Generics en hooks personalizados', 'Tipado de eventos sintéticos', 'Componentes polimórficos tipados'],
    [
      'Tipa las props de un componente con una interface, incluyendo children: React.ReactNode',
      'Escribe un hook personalizado genérico useLocalStorage<T> que funcione para cualquier tipo de dato',
      'Tipa correctamente el evento de un input (React.ChangeEvent<HTMLInputElement>)',
      'Migra un componente existente del proyecto a TypeScript estricto sin usar any en ningún punto',
    ],
    ['¿Qué gana tu equipo al tipar props en vez de confiar en PropTypes o nada?', '¿Por qué un hook genérico es más reutilizable que uno con tipos fijos?'],
    ['TypeScript'],
    'Migración de un componente complejo a TypeScript estricto sin any.'),
  m(12, 'Proyecto integrador: SPA con datos reales', 'Proyecto final', 'Experto', '6 h', '#149eca',
    'Une routing, estado global y data fetching en una aplicación real con TypeScript.',
    ['Arquitectura por features', 'Estado de servidor con TanStack Query', 'Rutas protegidas y layouts', 'Tests de los flujos críticos'],
    [
      'Organiza el proyecto por features (tareas/, auth/) en vez de por tipo de archivo',
      'Implementa rutas protegidas con React Router y un layout compartido',
      'Conecta TanStack Query a una API real (puede ser la del track Node) con queries y mutations',
      'Agrega un store de Zustand solo para estado de UI puro (ej. sidebar abierta/cerrada), separado del estado de servidor',
      'Escribe tests con Testing Library + MSW de al menos el flujo crítico de la aplicación',
    ],
    ['¿Qué decisión de arquitectura te costó más definir: la separación de estado de cliente vs servidor?', '¿Qué parte del ecosistema React (Query, Router, TypeScript) tuvo el mayor impacto en la calidad del código final?'],
    ['React', 'TanStack Query', 'TypeScript'],
    'SPA en React + TypeScript con rutas, estado global, datos reales y tests.'),
  m(13, 'React en producción: resiliencia, accesibilidad y seguridad', 'Producción React', 'Experto', '7 h', '#149eca',
    'Endurece la SPA y su variante servidor: define fronteras de Suspense/error, evita estados y efectos inconsistentes, completa flujos accesibles, protege render y acciones, estabiliza hidratación e internacionaliza sin divergencias.',
    [
      'Pureza, efectos, Suspense, Error Boundaries, recuperación y telemetría',
      'Accesibilidad de componentes, routing, foco, formularios y pruebas de usuario',
      'XSS, dangerouslySetInnerHTML, CSP, Server Components/Actions y secretos',
      'Hidratación determinista, i18n, RTL, performance budgets y releases',
    ],
    [
      'Diseña fronteras de carga/error y prueba recuperación sin perder estado válido',
      'Completa un flujo con teclado y lector y automatiza regresiones por rol',
      'Explota/corrige un render inseguro y demuestra autorización en el servidor',
      'Elimina mismatches, construye dos locales y controla budgets y rollback',
    ],
    [
      '¿Qué errores no captura un Error Boundary?',
      '¿Por qué un componente visualmente clickable puede ser inaccesible?',
      '¿Por qué suppressHydrationWarning no corrige una divergencia de datos?',
    ],
    ['React', 'Next.js', 'Testing Library', 'Playwright', 'axe'],
    'Aplicación React resiliente con boundaries, flujo accesible, CSP, acciones autorizadas, hidratación estable, dos locales, medición por release y rollback probado.'),
  m(14, 'React Master: servidor, Next.js, a11y e i18n', 'React Master', 'Experto', '10 h', '#149eca',
    'Construye una experiencia full-stack con RSC, streaming, Actions, Next.js avanzado, accesibilidad e internacionalización.',
    ['Server Components, streaming y Suspense', 'Server Actions y autorización', 'ISR, Metadata y Middleware', 'Image/Font Optimization', 'ARIA, teclado y React Aria', 'react-i18next, pluralización y RTL'],
    ['Traza frontera server/client', 'Protege Action', 'Valida ISR', 'Mide LCP', 'Completa flujo con teclado', 'Prueba plural y RTL'],
    ['¿Por qué use server no autoriza?', '¿Cuándo ISR sirve datos obsoletos?'], ['React','Next.js','React Aria','react-i18next','Playwright'], 'Aplicación Next.js accesible, localizada, transmitida por streaming y autorizada en servidor.'),
];
