import { CourseModule, createModule as m } from '../course-module.model';

export const RUTAFLOW_MODULES: CourseModule[] = [
  m(0, 'RutaFlow desde cero: producto, entorno y dominio', 'Producto y dominio', 'Fundamentos', '8 h', '#f97316',
    'Crea desde carpeta vacía el monorepo de una plataforma de paquetería y comprende actores, procesos, estados, datos e invariantes antes de seleccionar frameworks.',
    ['Mapa del proceso logístico', 'Lenguaje del dominio y estados', 'Monorepo reproducible', 'Privacidad y threat model inicial'],
    ['Instala herramientas en Windows, macOS o Linux', 'Modela el ciclo de un envío', 'Crea contratos y ADR inicial', 'Ejecuta la primera prueba de dominio'],
    ['¿Por qué una coordenada no prueba una entrega?', '¿Qué diferencia existe entre estado y evento?'],
    ['Git', 'Docker', 'OpenAPI'], 'Monorepo RutaFlow reproducible con dominio, contratos, amenazas y primera vertical probada.'),
  m(1, 'Datos, geografía y contabilidad de una entrega', 'Datos y contabilidad', 'Aplicación', '10 h', '#f97316',
    'Diseña persistencia relacional, historial de eventos, coordenadas, direcciones, tarifas, recaudo y libro contable con integridad verificable.',
    ['PostgreSQL y migraciones', 'Índices geoespaciales', 'Ledger de doble partida', 'Auditoría y retención'],
    ['Crea esquema y constraints', 'Modela movimientos balanceados', 'Consulta tracking sin exponer PII', 'Mide índices con EXPLAIN'],
    ['¿Por qué no debe editarse un saldo?', '¿Qué precisión geográfica necesita realmente el negocio?'],
    ['PostgreSQL', 'PostGIS', 'SQL'], 'Base RutaFlow migrable con integridad, pruebas SQL, datos semilla y conciliación balanceada.'),
  m(2, 'Backend: envíos, asignación e idempotencia', 'Backend y eventos', 'Integración', '12 h', '#f97316',
    'Implementa una API modular para cotizar, crear, asignar y confirmar entregas con autorización, transacciones, outbox y consumidores idempotentes.',
    ['REST y OpenAPI', 'Autenticación y autorización', 'Transacciones y optimistic locking', 'Outbox, colas y deduplicación'],
    ['Implementa casos de uso', 'Prueba comandos duplicados', 'Publica eventos recuperables', 'Instrumenta trazas y métricas'],
    ['¿Qué ocurre si el commit sucede pero la respuesta se pierde?', '¿Dónde debe validarse una transición?'],
    ['Node.js', 'Spring Boot', 'PostgreSQL', 'OpenTelemetry'], 'API de envíos con contratos, seguridad, persistencia, outbox y pruebas de fallos.'),
  m(3, 'Frontend web: cliente y centro de operaciones', 'Web y mapas', 'Integración', '12 h', '#f97316',
    'Construye el portal del cliente y una consola operativa accesible con mapas, filtros, estados en tiempo real y tratamiento seguro de datos.',
    ['Angular y React', 'Mapas y clustering', 'Estado remoto y local', 'Accesibilidad, rendimiento y seguridad web'],
    ['Crea tracking público', 'Construye mapa operativo', 'Prueba estados y teclado', 'Mide bundle y render'],
    ['¿Qué información puede mostrar un tracking público?', '¿Cuándo conviene agrupar puntos en el mapa?'],
    ['Angular', 'React', 'MapLibre', 'WebSocket'], 'Portal y consola web con tracking seguro, mapa operativo, pruebas y budgets.'),
  m(4, 'Aplicación Flutter del conductor: GPS, batería y offline', 'Flutter conductor', 'Integración', '14 h', '#f97316',
    'Implementa la jornada del conductor con permisos, mapas, ruta, escaneo, prueba de entrega, ubicación en background y sincronización offline.',
    ['Flutter y arquitectura por features', 'GPS y background execution', 'Batería y muestreo adaptativo', 'SQLite, outbox y conflictos'],
    ['Descarga una ruta', 'Captura ubicación con política', 'Confirma offline', 'Sincroniza sin duplicar', 'Mide energía'],
    ['¿Por qué más frecuencia GPS no siempre mejora el producto?', '¿Cómo sobrevive una confirmación al cierre del proceso?'],
    ['Flutter', 'Dart', 'SQLite', 'MapLibre'], 'App Flutter del conductor operable offline con GPS medido, evidencia de entrega y sincronización idempotente.'),
  m(5, 'Rutas, mapas y seguimiento en tiempo real', 'Rutas y tiempo real', 'Experto', '12 h', '#f97316',
    'Conecta geocodificación, matrices de distancia, heurísticas de rutas, streaming GPS y estimaciones sin presentar aproximaciones como certezas.',
    ['Grafos y VRP', 'Geocoding y map matching', 'WebSocket/SSE y backpressure', 'ETA, precisión y datos tardíos'],
    ['Compara heurísticas', 'Simula mil conductores', 'Ordena eventos fuera de secuencia', 'Calcula ETA con intervalo'],
    ['¿Por qué la ruta más corta puede ser operativamente inválida?', '¿Cómo se procesa una posición tardía?'],
    ['Python', 'PostGIS', 'MapLibre', 'OpenTelemetry'], 'Simulador de rutas y tracking en tiempo real con métricas, incertidumbre y pruebas de carga.'),
  m(6, 'Facturación, recaudo, liquidaciones y fraude', 'Finanzas y riesgo', 'Experto', '12 h', '#f97316',
    'Implementa tarifas versionadas, factura, recaudo contra entrega, liquidación de conductores, conciliación y controles de riesgo auditables.',
    ['Tarifas y vigencia', 'Doble partida y reversos', 'Conciliación e impuestos', 'Señales de fraude y revisión humana'],
    ['Calcula una cotización reproducible', 'Registra recaudo balanceado', 'Concilia diferencias', 'Modela reverso y disputa'],
    ['¿Por qué una corrección contable es otro movimiento?', '¿Qué riesgo tiene bloquear automáticamente por GPS?'],
    ['Java', 'Spring Boot', 'PostgreSQL'], 'Subsistema financiero balanceado con tarifas, recaudo, liquidación, conciliación y auditoría.'),
  m(7, 'Producción: cloud, DevOps, seguridad y operación', 'Producción', 'Experto', '16 h', '#f97316',
    'Despliega RutaFlow con infraestructura como código, supply chain verificable, observabilidad, SLO, continuidad y respuesta a incidentes.',
    ['Terraform y Kubernetes', 'Secretos y supply chain', 'SLI/SLO y alertas', 'Backup, restore, DR y FinOps'],
    ['Construye pipeline', 'Firma imágenes', 'Ejecuta game day', 'Restaura datos', 'Mide coste por entrega'],
    ['¿Qué demuestra una firma y qué no?', '¿Cómo se prueba realmente un backup?'],
    ['Terraform', 'Kubernetes', 'OpenTelemetry', 'Floci', 'StackPort'], 'RutaFlow desplegado con CI/CD, políticas, SLO, restore probado, runbook y postmortem.'),
];
