import { CourseModule, createModule as m } from '../course-module.model';

export const SPRING_BOOT_MODULES: CourseModule[] = [
  m(0, 'Fundamentos de Spring: IoC y DI', 'IoC y DI', 'Fundamentos', '2 h 30 min', '#6db33f',
    'El contenedor de Spring gestiona el ciclo de vida de tus objetos. Entiende ese contrato antes de usar anotaciones a ciegas.',
    ['Inversión de control y el contenedor de Spring', 'Inyección por constructor vs por campo', '@Component, @Service, @Repository', 'Autoconfiguración: qué hace realmente "Boot"', '@Scope: singleton, prototype, request, session', '@Qualifier y @Primary cuando hay varias implementaciones'],
    [
      'Crea un proyecto Spring Boot mínimo con start.spring.io y arráncalo con ./mvnw spring-boot:run',
      'Define un @Service y un @Repository, e inyecta el repositorio en el servicio usando inyección por constructor',
      'Cambia la inyección a @Autowired por campo y documenta por qué la inyección por constructor es preferible (testabilidad, inmutabilidad)',
      'Agrega un println en el constructor de un bean y observa cuándo lo instancia el contenedor de Spring respecto al arranque de la app',
      'Investiga qué hace spring-boot-starter-web por debajo (qué dependencias trae y qué autoconfigura)',
    ],
    ['¿Qué problema resuelve la inversión de control frente a que cada clase cree sus propias dependencias?', '¿Por qué la inyección por constructor facilita escribir tests sin levantar el contenedor de Spring?'],
    ['Spring Framework'],
    'Aplicación Spring Boot mínima con dos beans inyectados por constructor.'),
  m(1, 'Spring Boot CLI y estructura de proyecto', 'Estructura de proyecto', 'Fundamentos', '1 h 30 min', '#6db33f',
    'Genera y entiende la estructura estándar de un proyecto Spring Boot productivo.',
    ['Spring Initializr y starters', 'application.yml vs application.properties', 'Perfiles (dev/test/prod)', 'Estructura por capas (controller/service/repository)'],
    [
      'Genera un proyecto desde start.spring.io con los starters web, data-jpa y postgresql',
      'Convierte application.properties a application.yml y compara la legibilidad',
      'Crea application-dev.yml y application-prod.yml con valores distintos, y arranca la app con --spring.profiles.active=dev',
      'Organiza el proyecto en paquetes controller/, service/, repository/, dto/',
      'Verifica con el endpoint /actuator/env (si está habilitado) qué perfil está activo',
    ],
    ['¿Qué ventaja da externalizar configuración por perfil en vez de tener un único application.properties?', '¿Qué responsabilidad debería tener (y NO tener) cada capa: controller, service, repository?'],
    ['Spring Boot'],
    'Proyecto Spring Boot con perfiles dev/prod y configuración externalizada.'),
  m(2, 'REST APIs con Spring Web', 'Spring Web', 'Aplicación', '3 h', '#6db33f',
    'Expón endpoints HTTP con validación y manejo de errores consistente.',
    ['@RestController y mapeo de rutas', 'DTOs y validación con Bean Validation', 'ResponseEntity y códigos de estado', '@ControllerAdvice para errores centralizados'],
    [
      'Crea un @RestController con GET /tareas y POST /tareas que devuelvan/reciban un DTO, no la entidad directamente',
      'Agrega validación con @Valid y anotaciones de Bean Validation (@NotBlank, @Min) en el DTO de entrada',
      'Devuelve ResponseEntity con el código de estado correcto: 201 al crear, 404 si no existe',
      'Crea un @ControllerAdvice con @ExceptionHandler que capture una excepción de negocio y devuelva un 400 con mensaje claro',
      'Prueba el endpoint con curl enviando un body inválido y verifica el mensaje de error estructurado',
    ],
    ['¿Por qué exponer DTOs en vez de entidades JPA directamente en la API?', '¿Qué ventaja da centralizar el manejo de errores en un @ControllerAdvice?'],
    ['Spring Web'],
    'API REST con validación de entrada y manejo centralizado de errores.'),
  m(3, 'Persistencia con Spring Data JPA', 'Spring Data JPA', 'Aplicación', '3 h 30 min', '#6db33f',
    'Persiste entidades sin escribir SQL repetitivo, sin perder de vista qué genera Hibernate por debajo.',
    ['Entidades y mapeo JPA', 'Repositorios derivados y @Query', 'Relaciones (OneToMany, ManyToMany) y N+1', 'Migraciones con Flyway/Liquibase', 'JPQL, Native Queries, Criteria API y QueryDSL', 'Paginación con Pageable y Page', '@Valid, @Validated y anotaciones de Bean Validation (@NotNull, @Size, @Email)'],
    [
      'Define una entidad @Entity Tarea con sus campos mapeados y un JpaRepository<Tarea, Long>',
      'Usa un método derivado (findByCompletadaFalse) y luego el equivalente con @Query para comparar',
      'Modela una relación @OneToMany entre Usuario y Tarea, y provoca intencionalmente el problema N+1 al listar usuarios con sus tareas',
      'Corrige el N+1 usando JOIN FETCH o @EntityGraph y mide la diferencia en queries ejecutadas',
      'Configura Flyway con una migración versionada (V1__crear_tabla_tareas.sql) en vez de dejar que Hibernate genere el esquema automáticamente',
    ],
    ['¿Por qué confiar en hibernate.ddl-auto=update es riesgoso en producción comparado con migraciones versionadas?', '¿Qué causa el problema N+1 y cómo lo detectas?'],
    ['Spring Data JPA', 'Hibernate'],
    'API con persistencia real en PostgreSQL y migraciones versionadas con Flyway.'),
  m(4, 'Spring Security', 'Spring Security', 'Integración', '3 h 30 min', '#6db33f',
    'Protege endpoints con autenticación y autorización declarativa.',
    ['SecurityFilterChain y configuración moderna (sin WebSecurityConfigurerAdapter)', 'JWT con Spring Security', 'Autorización basada en roles/permisos', 'CORS y CSRF', 'Versionado de APIs: por URI, por header y por content negotiation'],
    [
      'Configura un SecurityFilterChain con @Bean que requiera autenticación para /api/** y permita /public/** sin login',
      'Implementa un filtro JWT que valide el token del header Authorization en cada request',
      'Agrega @PreAuthorize("hasRole(\'ADMIN\')") a un endpoint y verifica que un usuario sin ese rol recibe 403',
      'Configura CORS para permitir requests solo desde el origen de tu frontend',
      'Documenta cuándo CSRF es relevante (apps con sesiones basadas en cookies) y por qué suele deshabilitarse en APIs stateless con JWT',
    ],
    ['¿Por qué una API stateless con JWT generalmente no necesita protección CSRF?', '¿Qué diferencia hay entre autenticación (quién eres) y autorización (qué puedes hacer)?'],
    ['Spring Security'],
    'API protegida con JWT y rutas con autorización por rol.'),
  m(5, 'Configuración, perfiles y manejo de errores', 'Configuración', 'Integración', '2 h', '#6db33f',
    'Externaliza configuración sensible y maneja errores de forma consistente entre entornos.',
    ['@ConfigurationProperties tipado', 'Perfiles y configuración por entorno', 'Manejo global de excepciones', 'Validación de configuración al arranque'],
    [
      'Crea una clase con @ConfigurationProperties("app.jwt") que mapee valores tipados desde application.yml',
      'Agrega @Validated a esa clase de configuración para que la app falle al arrancar si falta un valor obligatorio',
      'Provoca intencionalmente esa falla de validación (borra un valor requerido) y observa el error de arranque',
      'Centraliza el manejo de una excepción de negocio para que SIEMPRE devuelva el mismo formato de error JSON',
    ],
    ['¿Por qué preferir @ConfigurationProperties tipado sobre leer valores sueltos con @Value?', '¿Qué ventaja da que la app falle al ARRANCAR por configuración inválida, en vez de fallar más tarde en producción?'],
    ['Spring Boot'],
    'Configuración tipada y validada al arranque, sin valores hardcodeados.'),
  m(6, 'Testing en Spring Boot', 'Testing', 'Integración', '3 h', '#6db33f',
    'Prueba desde unit tests aislados hasta tests de integración contra una base real.',
    ['@SpringBootTest vs slices (@WebMvcTest, @DataJpaTest)', 'MockMvc para probar controllers', 'Testcontainers para bases de datos reales en CI', 'Mockito en el ecosistema Spring', '@MockBean, @SpyBean y TestRestTemplate', 'ArgumentCaptor y AssertJ para aserciones expresivas'],
    [
      'Escribe un test unitario de un servicio con @Mock/@InjectMocks de Mockito, sin levantar el contexto de Spring',
      'Escribe un test de slice con @WebMvcTest que pruebe solo la capa del controller, mockeando el servicio',
      'Usa MockMvc para simular una petición HTTP completa y verificar el código de estado y el JSON de respuesta',
      'Configura Testcontainers con un PostgreSQL real para un test de integración con @DataJpaTest',
      'Escribe un test con @SpringBootTest que levante el contexto completo y verifique un flujo end-to-end',
    ],
    ['¿Por qué un test de slice (@WebMvcTest) es más rápido que uno con @SpringBootTest completo?', '¿Qué ventaja da Testcontainers sobre una base de datos H2 en memoria para tests de integración?'],
    ['Testcontainers', 'JUnit 5'],
    'Suite de tests de integración con Testcontainers contra PostgreSQL real.'),
  m(7, 'Observabilidad con Actuator', 'Actuator', 'Experto', '2 h', '#6db33f',
    'Expón métricas y health checks listos para cualquier sistema de monitoreo.',
    ['Spring Boot Actuator: endpoints clave', 'Micrometer y métricas custom', 'Health checks personalizados', 'Logging estructurado'],
    [
      'Agrega spring-boot-starter-actuator y expón /actuator/health y /actuator/metrics',
      'Crea un health indicator personalizado que verifique la conexión a un servicio externo',
      'Define una métrica de negocio custom con Micrometer (ej. contador de pedidos creados) y verifica que aparece en /actuator/metrics',
      'Configura logging estructurado en JSON para que sea consumible por un sistema de logs centralizado',
    ],
    ['¿Qué diferencia hay entre un health check de "liveness" y uno de "readiness" en el contexto de Actuator + Kubernetes?', '¿Por qué exponer métricas de negocio (no solo técnicas) le da valor al equipo de producto, no solo a infraestructura?'],
    ['Actuator', 'Micrometer'],
    'API con Actuator expuesto y al menos una métrica de negocio custom.'),
  m(8, 'Mensajería: Kafka/RabbitMQ', 'Mensajería', 'Experto', '3 h', '#6db33f',
    'Desacopla servicios con mensajería asíncrona desde Spring.',
    ['Spring Kafka: producers y consumers', 'Spring AMQP (RabbitMQ)', 'Serialización de mensajes', 'Manejo de errores y dead-letter'],
    [
      'Levanta Kafka en Docker Compose y configura un KafkaTemplate para publicar un evento desde tu API',
      'Implementa un @KafkaListener que consuma esos eventos y procese su contenido',
      'Serializa los mensajes como JSON con un serializer configurado explícitamente',
      'Configura una estrategia de reintentos y una dead-letter queue para mensajes que fallan repetidamente al procesarse',
      'Repite un ejercicio simple equivalente con RabbitMQ (Spring AMQP) y compara los modelos de entrega',
    ],
    ['¿Qué problema de acoplamiento resuelve publicar un evento en vez de llamar directamente a otro servicio?', '¿Qué pasa con un mensaje que falla repetidamente sin una dead-letter queue configurada?'],
    ['Spring Kafka'],
    'Servicio que publica y consume eventos vía Kafka con manejo de errores.'),
  m(9, 'Programación reactiva con WebFlux', 'WebFlux', 'Experto', '3 h', '#6db33f',
    'El modelo no bloqueante de Spring para alta concurrencia con recursos limitados.',
    ['Mono y Flux', 'WebClient reactivo', 'Cuándo WebFlux vale la complejidad frente a MVC', 'R2DBC para acceso reactivo a datos'],
    [
      'Crea un endpoint reactivo que devuelva Mono<Tarea> y otro que devuelva Flux<Tarea>',
      'Usa WebClient (no RestTemplate) para componer dos llamadas HTTP externas de forma no bloqueante con flatMap',
      'Compara con un código equivalente en Spring MVC tradicional (bloqueante) y documenta la diferencia de modelo mental',
      'Conecta a una base de datos con R2DBC y ejecuta una query reactiva',
    ],
    ['¿Cuándo el modelo no bloqueante de WebFlux realmente justifica su complejidad adicional frente a Spring MVC?', '¿Qué pasa si mezclas código bloqueante (ej. JDBC tradicional) dentro de un flujo reactivo?'],
    ['Spring WebFlux'],
    'Endpoint reactivo que compone múltiples llamadas no bloqueantes con WebClient.'),
  m(10, 'Microservicios con Spring Cloud', 'Spring Cloud', 'Experto', '3 h 30 min', '#6db33f',
    'Coordina múltiples servicios Spring Boot: configuración centralizada, descubrimiento y gateway.',
    ['Config Server', 'Service discovery (Eureka)', 'Spring Cloud Gateway', 'Resiliencia con Resilience4j (circuit breaker)', '@Retry, @RateLimiter, @Bulkhead y @TimeLimiter', 'Spring Cloud Bus y @RefreshScope para config dinámica'],
    [
      'Levanta dos microservicios Spring Boot simples que se comuniquen entre sí vía HTTP',
      'Registra ambos en Eureka y haz que se descubran por nombre de servicio en vez de URL hardcodeada',
      'Configura Spring Cloud Gateway como punto de entrada único que enrute a ambos servicios',
      'Agrega un circuit breaker con Resilience4j a la llamada entre servicios y simula que uno falla para ver el fallback en acción',
    ],
    ['¿Qué problema de configuración resuelve un Config Server centralizado en un sistema de muchos microservicios?', '¿Qué hace un circuit breaker y por qué es mejor que dejar que las llamadas fallidas se acumulen sin control?'],
    ['Spring Cloud'],
    'Dos microservicios Spring Boot comunicándose vía gateway con circuit breaker.'),
  m(11, 'Empaquetado y despliegue', 'Despliegue', 'Experto', '2 h', '#6db33f',
    'Empaqueta tu servicio Spring Boot de forma óptima para producción.',
    ['Fat JAR vs capas de Docker', 'GraalVM native image: arranque en milisegundos', 'Variables de entorno en producción', 'Health checks para Kubernetes'],
    [
      'Genera el fat JAR con ./mvnw package y ejecútalo directamente con java -jar',
      'Construye una imagen Docker usando capas de Spring Boot (spring-boot:build-image o un Dockerfile en capas) y compara el tamaño con un JAR simple',
      'Compila la app a GraalVM native image y mide el tiempo de arranque comparado con la JVM tradicional',
      'Configura un health check de Actuator como readiness/liveness probe de un manifiesto de Kubernetes',
    ],
    ['¿Qué ventaja real da un arranque en milisegundos (GraalVM native) para un sistema con autoscaling agresivo?', '¿Por qué empaquetar por capas reduce el tamaño de las actualizaciones de imagen en cada deploy?'],
    ['Docker', 'GraalVM'],
    'Imagen Docker de un servicio Spring Boot optimizada por capas.'),
  m(12, 'Proyecto integrador: microservicio productivo', 'Proyecto final', 'Experto', '7 h', '#6db33f',
    'Une persistencia, seguridad, observabilidad y tests en un microservicio real.',
    ['Arquitectura por capas', 'Seguridad con JWT', 'Persistencia con migraciones', 'Tests de integración con Testcontainers', 'Qué sigue: Arquitectura Hexagonal/DDD, CQRS y Event Sourcing, OIDC/Keycloak para SSO'],
    [
      'Diseña la arquitectura por capas del microservicio (controller/service/repository/dto)',
      'Implementa persistencia real con Spring Data JPA y migraciones versionadas con Flyway',
      'Protege los endpoints sensibles con Spring Security + JWT y autorización por rol',
      'Expón Actuator con al menos una métrica de negocio custom',
      'Escribe tests de integración con Testcontainers que cubran el flujo crítico de principio a fin',
    ],
    ['¿Qué decisión de arquitectura tomarías distinto si este microservicio tuviera que escalar a 100x el tráfico actual?', '¿Qué parte del ecosistema Spring (Security, Data JPA, Testcontainers) te resultó más compleja de dominar?'],
    ['Spring Boot', 'Spring Security', 'Spring Data JPA'],
    'Microservicio Spring Boot con auth, persistencia real, Actuator y tests de integración.'),
  m(13, 'Consistencia, contratos y operación distribuida', 'Producción distribuida', 'Experto', '8 h', '#6db33f',
    'Convierte el microservicio funcional en un sistema verificable ante rollback, self-invocation, requests duplicados, doble escritura, cambios de contrato y dependencias lentas mediante transacciones explícitas, outbox, contratos y SLO.',
    [
      '@Transactional, proxies, propagación, aislamiento, rollback y locks',
      'Idempotencia, optimistic locking, outbox, Kafka y consumidores deduplicados',
      'OpenAPI, Problem Details, Spring Cloud Contract y evolución compatible',
      'Micrometer Observation, trazas, SLI/SLO, resiliencia e incidentes',
    ],
    [
      'Demuestra commit/rollback y el fallo de self-invocation con una prueba de integración',
      'Fuerza requests/eventos duplicados y prueba un único efecto de negocio',
      'Rompe un contrato deliberadamente y haz que CI detenga al proveedor',
      'Inyecta latencia/caída, sigue una traza y recupera mediante runbook y postmortem',
    ],
    [
      '¿Por qué llamar un método @Transactional desde el mismo bean puede evitar el proxy?',
      '¿Qué garantiza Kafka exactly-once y qué efecto queda fuera de esa frontera?',
      '¿Por qué una métrica con userId como tag puede derribar el monitoreo?',
    ],
    ['Spring Boot', 'PostgreSQL', 'Kafka', 'Spring Cloud Contract', 'OpenTelemetry'],
    'Microservicio con límites transaccionales probados, idempotencia, outbox, consumidor deduplicado, contrato ejecutable, trazas correlacionadas, SLO y recuperación de fallos ensayada.'),
];
